### ISSUE TITLE
Using "solve" tactic yields INTERNAL ERROR

### ISSUE THREAD

**Issue by rpglover64** [idris-lang/Idris-dev#1043]
```
INTERNAL ERROR: Not a guess ? {hole2} : Prelude.Vect.Vect Prelude.Nat.Z a. {hole2}
([{hole2},{hole1},{hole0}],?? {hole0} : (a : Type `) -> a -> Prelude.Vect.Vect Prelude.Nat.Z a = \ a : Type ` => ?? {hole1} : a -> Prelude.Vect.Vect Prelude.Nat.Z a = \ x : a => ? {hole2} : Prelude.Vect.Vect Prelude.Nat.Z a. {hole2} in {hole1} in {hole0})
```

In particular, the file I am working over is
```
module main

repeat : (n : Nat) -> a -> Vect n a
repeat Z x = ?result --x :: repeat (n - 1) x
repeat (S n) x = ?main.repeat_rhs_1
```
and the sequence of commands entered is
```
:p main.result
intros
solve
```

**Comment by edwinb** [comment]
This no longer gives an INTERNAL ERROR - not that the error it gives (Incomplete Term [__]) is particularly great but it is at least accurate in that there's nothing in the current term that counts as a solution.

I'm inclined to close since the tactics system is deprecated and the precise issue itself is resolved.
