### ISSUE TITLE
Named instances need some attention

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris-dev#1118]
This issue is mostly meant as a placeholder to remind me to write some proper tests, and make sure they work as intended.

It would also be nice to extend the 'with' construct to help choose a named instance.

**Comment by edwinb** [comment]
I now believe named instances work as intended, but I haven't written all the test cases so I'm leaving this open until I do.

Currently (by design) named instances can only be used to resolve a class by being named explicitly, even if there is no normal instance. This is deliberate, but should it stay this way?

My reasoning for this was that named instances should always be a special case - if there's a named instance, but you then add a normal instance, it could change the behaviour of code in surprising ways. Unless there's a compelling argument I haven't thought of, I'd like to keep it as it is. I note that this behaviour isn't documented anywhere, in any case.

**Comment by treeowl** [comment]
I don't see a way to use a named instance to satisfy a superclass constraint, even of another named instance. For example, I can write

```idris
instance [addSemNat] Semigroup Nat where
  (<+>) = (+)
```
but then there doesn't seem to be any way to get
```idris
instance [addMonNat] Monoid Nat where
  neutral = 0
```
because the `Semigroup` superclass constraint is not satisfied. Since the superclass instance is just another field in the dictionary, shouldn't it be reasonable to just let me stick one I want in there?

**Comment by chamini2** [comment]
@treeowl, this has been reported in #1881

**Comment by jfdm** [comment]
I would like to see this issue closed but I do not know the tests cases @edwinb is think about. Can we get those cases added here so that either myself, @edwinb, or some enthusiastic person can contribute them?
