### ISSUE TITLE
Inappropriate strictness in libraries

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#1121]
Found at: http://www.reddit.com/r/haskell/comments/243fm4/erik_meijer_the_curse_of_the_excluded_middle/ch3d7w8

We have various places where we should add laziness in the library. Examples on that Reddit thread include:
1. `list : (nil : a) -> (cons : a -> List a -> a) -> (xs : List a) -> a`
2. `&&` and `||` do not short-circuit

Someone should go through the library and find places where laziness should be added, then add it. This would be a good hackathon project for a new community member.

**Comment by edwinb** [comment]
This is somewhat open ended, and something we have to be constantly aware of, so I'm inclined to close. If there are specific strictness issues, it would be good to report separately.

Incidentally, these days Idris is quite aggressive at inlining small things, and therefore && and || short circuit even without the Lazy annotation. I'd even prefer to omit Lazy annotations where possible because it makes reasoning easier - also sometimes [static] annotations are more likely to be what we want for control structure functions now that they work on higher order and polymorphic functions. Some brief notes here: http://stackoverflow.com/questions/32908745/is-idris-really-strictly-evaluated/32922365#32922365

This all needs more documentation, of course, but I think it needs more thought than liberally scattering Lazy annotations around.
