### ISSUE TITLE
Report totality errors more aggressively

### ISSUE THREAD

**Issue by walkie** [idris-lang/Idris-dev#1437]
(This is a follow-up to #1436.)

A totality error can cause a unification error in a later function, but Idris only reports the unification error, not the totality error. To fix such errors, it would be really helpful to report both.

Here's some buggy code illustrating the problem:

    %default total
    using (n : Nat, ts : Vect n Type)
    
      data AB : Vect n Type -> Type where
        A : (i : Fin n) -> index i ts -> AB ts
        B : AB ts
    
      isA : AB ts -> Bool
      isA (A _ _) = True
      isA  B      = False
      
      fstA : (ab : AB ts)
          -> {default refl p : isA ab = True}
          -> Fin n
      fstA (A i _) = i
    
      sndA : (ab : AB ts)
          -> {default refl p : isA ab = True}
          -> index (fstA ab {p}) ts
      sndA (A _ x) = x

The type constructor `AB` takes a vector of types `ts`. The `A` case contains an index `i` and a value of type `index i ts`. The function `fstA` returns the index, given a proof that it's the `A` case. The function `sndA` returns the value, given a proof that it's the `A` case.

Idris reports the following unification error:

    When elaborating right hand side of sndA:
    Can't unify
            index i ts
    with
            index (fstA (A i x)) ts
    
    Specifically:
            Can't unify
                    index i ts
            with
                    index (fstA (A i x)) ts

Idris doesn't reduce the application of `fstA` since it is missing cases. However, Idris doesn't report the totality error in the presence of the unification error. This masks the "real error", making it difficult to identify and fix.

If the definition of `sndA` is removed, Idris complains that `fstA` is not total.

Ideally both errors would be reported in the original program.

**Comment by edwinb** [comment]
Sorry for not getting to this sooner. There seems to be a batch of issues I haven't even noticed from about this time...

Anyway - at the moment, Idris only reports totality errors at the end, which is irritating for other reasons too. It waits until it's done the entire file because mutual definitions can affect the result of totality checking, but it should still report whether the rest of the file was successful or not. It turns out to have an easy fix, at least, coming shortly...
