### ISSUE TITLE
"No such variable" on referencing imported value referencing private value in its type signature

### ISSUE THREAD

**Issue by Ralith** [idris-lang/Idris-dev#144]
Reproducible with the following test case:

Main.idr
```haskell
module Main

import Foo

main : IO ()
main = putStrLn $
       case bar of
         Nothing => "Nothing"
         Just x => show x
```
Foo.idr
```haskell
module Foo

baz : Type
baz = Int

public
bar : Maybe baz
bar = Just 42
```

**Comment by david-christiansen** [comment]
Still an issue in the latest master, immediately prior to release of 0.9.18

**Comment by identicalsnowflake** [comment]
I'm experiencing this now. My current solution is to make everything public with the most ominous sounding names possible for stuff I intended to be private.

**Comment by edwinb** [comment]
It's now an error for a public definition (i.e. something that will be fully exported) to use a private name, since that would cause the private name to leak into the interface.

Something marked "export", that is, something where just the type is exported, can happily use private names (just not in its type, since that would be exported).
