### ISSUE TITLE
Small syntactic improvements when working with dependent pairs

### ISSUE THREAD

**Issue by ahmadsalim** [idris-lang/Idris-dev#1476]
There are currently a few forms of dependent pairs (`Sigma`, `Exists`, `Subset`), depending on which argument gets erased.
I suggest to extend the current dependent pair syntax to support the new types as follows:

*  `(a : A ** B)` still acts as syntax for `Sigma`
* `(a : A .** B)` acts as new syntax for `Exists` (alternatively `(.a : A ** B)` as @david-christiansen suggests)
* `(a : A **. B)` acts as new syntax for `Subset`

The mnemonic is that the dot is on the side that is getting erased.
Obviously, a question that comes up if there should be a fourth type of dependent pair representing a some kind of dependent "and" where both arguments are erased: `(a : A .**. B)`.

Naturally, there should also be equivalent to these for constructing and destructing relevant values, like `(a0 ** b0)` is used today.

Another part of this suggestion aims to make it easier to use nested dependent pairs, like it is easy to use nested ordinary pairs. I believe a desired feature would be if one could write something like:
`(a : A ** b : B ** C)` and get `(a : A ** (b : B ** C))` for free similar how to pairs are today.

Naturally, it might be better if one could combine the different types of dependent pairs e.g.
`(a : A .** b : B ** c : C **. D)` becoming `(a : A .** (b : B ** (c : C **. D)))`.

**Comment by cbiffle** [comment]
Hello from a year later!

I was surprised this evening to learn that the `(x ** y)` syntax is specific to `Sigma`, and that there is still no (documented) syntax for `Exists` or `Subset`.

**Comment by ahmadsalim** [comment]
Maybe, I should try to implement this proposal at some point since there is some interest. 
There is still no special syntax for Exists or Subset as far as I remember.

**Comment by cbiffle** [comment]
If there were a good way of telling, as a programmer, that the second term in a Sigma such as `(result ** ProofOf result)` were erased, I don't think I would have much interest in `Subset`.  I find its naming and notation a little awkward.  But the application I'm working on produces *very large* proof terms that tend to appear in that position, and I'm currently going through rewriting it to explicitly use `Subset` so that I don't have to worry about using O(n^2) memory.

We can almost get to your original proposal using syntax extensions.  The only thing we can't appear to do is "pun" the same syntax for both types and patterns.  I'm not sure I consider this a bad thing -- Sigma's punning of type and value syntax was confusing for me as a n00b, and still seems error prone.

    syntax {x} "**." [e] = (_ `Subset` (\x -> e))
    syntax {x} "**.:" [e] = (_ `Element` (\x -> e))  -- slightly ugly operator

**Comment by ahmadsalim** [comment]
Basically, the name Subset comes from the fact that it can be seen as a subset of a type, e.g. `Subset x (\x : a => P)` is equivalent to `{ x : a | P }` (that is the type of all elements which are of type `a` and `P` holds).

The reason one may want to extend the parser and not just use syntax declarations, is that to avoid ambiguity with the main language and get better error messages.

**Comment by david-christiansen** [comment]
I believe the name goes back to the early work on Nuprl, where the subset type `{x : a | P x}` is like a sigma type as far as its proof obligations go, but whose runtime witnesses contain only what would have been the left projection.

**Comment by cbiffle** [comment]
Thanks for the clarification.  I think that, with the sugar proposed by @ahmadsalim, the name `Subset` would make more sense, because (as in @david-christiansen 's set notation example) the subset term would appear on both sides.

I agree that an ad-hoc syntax extension is the wrong way to solve this in general, but it does make for a useful band-aid for now, because of the ability to bind and reuse the witness's name.  Given these two options, I find the second far clearer precisely *because* of its correspondence with set notation.

    RegisterState `Subset` WeakestPrecond op post
    (r **. WeakestPrecond op post r)

So it sounds like we're all arguing the same side of this. :-)

**Comment by ahmadsalim** [comment]
To be honest, no one has complained about the current names and I am probably not going to implement this feature request. So I am closing it.
