### ISSUE TITLE
Implicit and explicit function types are sometimes not distinguished

### ISSUE THREAD

**Issue by andreasabel** [idris-lang/Idris-dev#1536]
The following code is accepted:
```idris
K : {A : Type} -> A -> {B : Type} -> B -> A
K = \ x => \ B => \ y => x
```
Is this a bug or a feature?

It might be related to #27.
```idris
issue27 : (a : Int) -> (b : Int) -> Int
issue27 {a = a} {b = b} = a 
```
Here, one can give explicit arguments as implicit ones.

**Comment by edwinb** [comment]
I've finally got around to looking at this. We've had implicit lambdas for a while, but they didn't work right for top level implicits, because they worked in a slightly different way which I'm slowly changing.

Essentially, if the elaborator sees that the target type is an implicit bi binding, it will always, with no exceptions, add an implicit lambda. Implicit lambdas can never be written by hand. My goal is to make implicits behave like Haskell forall, but I wouldn't be surprised if some devious user could find a way in which they don't :).

There's still some display issues with implicits, which are annoyingly tricky to fix. I'll try to get to them shortly.
