### ISSUE TITLE
Spinning out `base` into separate repository.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1814]
Taken from a recent mailing list discussion. The `base` package contains useful libraries that can aid, but are not crucial, to development of Idris programs. However, the `base` package should ideally be spun out into its own repository e.g. `idris-contribs`, that is under the `idris-lang` organisation control. Secondly, this new repository does not necessarily have to be monolithic and could be broken down further into other packages. 

If spinning out `base` the relevant tests from `test` need to be extracted as well, and linked into the travis builds.

**Comment by edwinb** [comment]
I think it would be nice at least to organise base into some meaningful packages rather than treating it as a dumping ground for things that are likely to be useful. This is as much to help organise documentation as anything. It would also be good, while we're at it, to think a bit more about package management - .ipkg files are just a quick hack.

It probably isn't so useful to have separate repositories, at least not at the moment.

**Comment by david-christiansen** [comment]
I definitely agree that meaningful packages is useful, especially now that tools are improving to deal with them.

I wrote code this morning to add IdrisDoc to modules, but I'm not satisfied with it and I'm going to redo it before submitting. Package docs as separate Markdown files that Idris can search and/or display will also make this nicer.

**Comment by jfdm** [comment]
Regarding the separate repository idea. I think that in future we might want to consider the use of git submodules so that the `libs/` can be spun out *and* kept integrated within the project. This way for a minimal overhead we get the best of both worlds. Moreover, I suggest that *if* base and other libs are to be spun out we do such that [the version history is kept](http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository/17864475#17864475).

As for splitting `base` into separate packages, taking inspiration from [Apache Commons](http://commons.apache.org) I think the following split might be useful:

+ `data` for everything in `Data/`.
+ `lang` for code that affects the language e.g. `Syntax.idr`, `Providers.idr`, `Decidable/`
+ `comms` for code that deals with system IO and network IO i.e. communication.
+ `utils` for utilities that do not fit into the above packages. i.e. Debug and System.

Finally thinking about it if we were to spin out the new 'base' a better name for the package/repository might be either:

+ `commons` as in code that is commonly used but not necessary.
+ `contribs` the (AFAIK) standard FP name to detail contributed but not required code.

**Comment by jfdm** [comment]
oh @david-christiansen your comment about package docs as separate `Markdown` files reminds me of a nice piece of functionality from [Doxygen](http://www.doxygen.org) in which the documentation's main page can be taken from a given `Markdown` file. I think as well as having the ability to document a module using the `|||` syntax, i think we should also look into adding an entry into the `ipkg` file for a packages main file to be taken from a specified `Markdown` formatted file. 

Also unless it you have implemented already a good convention for module documentation maybe: For a given module `x`, `IdrisDoc` should automatically read in files named `x.md` iff they are placed along side the  `x.idr`file. Maybe any `x.md` file should override any given module documentation within `x.idr`?

**Comment by david-christiansen** [comment]
Certainly we should use submodules and keep history if we do a split, but I haven't seen a single convincing argument for why such a split is beneficial. Good arguments might be things like:

* the ability to have more committers than the core, if we consider it less important
* the ability to clone only those, if the main repo were too huge

I don't think either of those are actually useful though.

What do you see as the utility of that split? What specific problems does it solve and how does it solve them?

**Comment by david-christiansen** [comment]
WRT module documentation: the `master` branch of Idris supports docstrings for module headers using the normal triple-pipe syntax. It also includes it in generated HTML IdrisDoc as of yesterday. So that problem is solved.

What I want to have separate help files for is to document things that aren't really API _per se_ but instead are larger concerns. For example, a description of how to accomplish certain tasks by coordinating multiple modules, a high-level description of the modules of some package and how they fit together, a description of a language feature, or a (part of) a tutorial. These things would benefit from having the Idris pretty-printer to highlight code samples, and it's nice to have the docs for an app built in. They should also, of course. show up in HTML IdrisDoc because some people prefer to read their docs in their browser.

**Comment by david-christiansen** [comment]
Basically, I want `idris-mode` and any other editors to be as nice to work in as writing Emacs Lisp in Emacs. We're maybe 50% there, and online pervasive access to documentation is a big part of it. The `|||` docs get you the functionality of `describe-function` and friends, while I would like these other docs to give the functionality of `info`.

**Comment by jfdm** [comment]
Concerning spinning out base, I am sitting on either side of the fence on this. I was only reporting what I consider to be an important a line of discussion from the mailing list into a more visible and appropriate place such that it won't be forgotten.
