### ISSUE TITLE
Cons operator

### ISSUE THREAD

**Issue by jimcrayne** [idris-lang/Idris-dev#1839]
It has been years, and I still have cognitive load when i see :: used as cons in Idris code. 
I propose we deprecate the use of (::) as a cons operator, and instead simply use Cons.

I can program my brain to read : as type easily, but for some reason to unprogram it from reading (::) as type is very difficult.

**Comment by edwinb** [comment]
:: is inherited from various ML derived languages, including SML, OCaml and F# at least.

I realise various things are going to be difficult, not only in syntax but in the type system, but everyone is different and everyone finds different things difficult. Personally I'd find it inconvenient and ugly to use 'Cons'.

**Comment by jimcrayne** [comment]
1) It doesn't really occur that often, and cons is more readable. Pretty much everyone in the functional programming community knows what a cons cell is.
2) Those other languages don't look anything like haskell, where as idris looks enough like it that they could concievably evolve into one language unless people are just pig-headedly opposed to such a thing. 
3) Thanks to the [,,...] sugar, the need for an infix operator is over rated.
4) if you want an infix operator, for some situation, it is trivial to define one.
5) Since the infix operator thing is not really my objection at all, just propose a different symbol and you'd address my concern just fine.

**Comment by soimort** [comment]
As an Idris user, I think I might be able to explain this a little bit from a beginner's (rather than language designers') perspective,

> 1) It doesn't really occur that often, and cons is more readable. Pretty much everyone in the functional programming community knows what a cons cell is.

By suggesting `Cons` as an alternative to `::`, it implies that your `Cons` is equivalent to a Lisp cons cell; actually they are very **different**. In Lisp, you can concatenate two arbitrary values to make a pair: `(cons 1 2) => (1 . 2)`; In a statically-typed language like Idris, a list cons should only concatenate an element and a list (that's what makes it static typing).

> 2) Those other languages don't look anything like haskell

The infix `(::)` is a convention used in *almost every* statically typed language: ML, Scala, Agda and Coq. I don't see why you have a problem with it. (So the choice of `:` is pretty much a "Haskell thing".)

> 3) Thanks to the [,,...] sugar, the need for an infix operator is over rated

No, it's not. We have things like `x::xs` in pattern matching all the time; it is obviously clumsy to write `Cons` instead.

> 4) if you want an infix operator, for some situation, it is trivial to define one

It's also trivial to define your own `Cons`, isn't it? : )

**Comment by david-christiansen** [comment]
I don't think the reasons presented in this issue are sufficient to make the backwards-incompatible breaking change here, so I'm going to close the issue. Feel free to re-open if any new, very strong arguments come to light.
