### ISSUE TITLE
Use named instances for other instances

### ISSUE THREAD

**Issue by chamini2** [idris-lang/Idris-dev#1881]
Hi,

I'm trying to make a `Semigroup` and `VerifiedSemigroup` instance on *my custom Bool* `data` both on operator `&&` and operator `||`:

    %case data Lógico = Cierto | Falso

    (&&) : Lógico -> Lógico -> Lógico
    (&&) Cierto Cierto = Cierto
    (&&) _ _ = Falso

    (||) : Lógico -> Lógico -> Lógico
    (||) Falso Falso = Falso
    (||) _ _ = Cierto

So I first make a *named instance* for `Semigroup` over the  `&&` operator:

    -- Todos
    instance [TodosSemigroup] Semigroup Lógico where
        (<+>) a b = a && b

But when making the `VerifiedSemigroup` instance, how do I tell Idris to use the `TodosSemigroup` instance of `Lógico`?

    instance [TodosVerifiedSemigroup] VerifiedSemigroup Lógico where
        semigroupOpIsAssociative l c r = ?vsemigroupTodos

That code gives me the following error:

> When elaborating type of Prelude.Algebra.Main.TodosVerifiedSemigroup, method semigroupOpIsAssociative:
> Can't resolve type class Semigroup Lógico

**Comment by edwinb** [comment]
Sorry for being really slow at this - we're not very systematic about the issue tracker and we really should be!

Sadly, I think what you want to do is not currently possible, and we'll need to think a bit carefully about how to do it right, if indeed it's possible at all. To be honest, I'm still in two minds as to whether named instances are a good idea, partly due to problems like this.

It might be that type classes are the wrong way to approach this, if you really want this level of control. Perhaps records would be a better bet?

I've tagged this "Feature request" anyway, because that's sort of what it is, underneath.

**Comment by edwinb** [comment]
You can now do this in master by adding a `using` clause to the instance declaration. e.g.:

    [PlusNatSemi] Semigroup Nat where
      (<+>) x y = x + y
  
    [MultNatSemi] Semigroup Nat where
      (<+>) x y = x * y
  
    -- 'using' gives the names of any parent implementations an implementation might need
    [PlusNatMonoid] Monoid Nat using PlusNatSemi where
      neutral = 0
  
    [MultNatMonoid] Monoid Nat using MultNatSemi where
      neutral = 1
