### ISSUE TITLE
Strange Error Message

### ISSUE THREAD

**Issue by JulianBirch** [idris-lang/Idris-dev#1888]
...on extremely broken code.

Here's basic.idr:
```idris
module Basic

data Divides : (n, m : Nat) -> Type where
  DivZ : Divides (S n) 0
  DivM : Divides (S n) m -> Divides (S n) ((S n) + m)

divides : (n, m : Nat) -> Dec (n `Divides` m)
divides Z Z = No ?x
```

Now in interactive mode
```
idris basic.idr
:p x
induction Divides

INTERNAL ERROR: Unkown type for induction
This is probably a bug, or a missing error message.
Please consider reporting at https://github.com/idris-lang/Idris-dev/issues
```

**Comment by peterohanley** [comment]
This is the same issue as #1789 and probably several others. I think the tutorial mentions that you must use %elim, but either way no one is finding out about it.

The code is at
https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/Core/ProofState.hs#L707

Just adding "to generate an eliminator, use %elim" or something should do it.

Is there any reason not to just generate eliminators for all inductive types? That would handle this once and for all.

**Comment by JulianBirch** [comment]
Yeah, it is indeed on eliminator mention on induction, but
* It doesn't explain what an eliminator is or what it's used for.
* It doesn't explain how to use it

And as previously mentioned, the error message is unhelpful.

But the ideal solution would be not even needing to understand it/worry about it.

**Comment by JulianBirch** [comment]
Sorry to go on, but also
* There's no other reference to modifiers in the entire manual

and neither
```
data %elim Divides : (n, m : Nat) -> Type where
```
nor
```
%elim data Divides : (n, m : Nat) -> Type where
```

actually seems to make the problem go away.

**Comment by edwinb** [comment]
The `induction` tactic is still experimental. I've added a note to the manual to make this clear, but we are aware of these issues.

If you want to do an inductive proof, the intention has always been that you write it in a pattern matching form. Tactics are intended to help build proof search mechanisms, rather than for programmers to use directly (unlike, say, in Coq) which is part of the reason they don't get so much attention in documentation and development.
