### ISSUE TITLE
Sleep in Effect.StdIO

### ISSUE THREAD

**Issue by eborden** [idris-lang/Idris-dev#1890]
Is there any reason sleep isn't included in StdIO? I could see not wanting to permit a function to hang the whole proces without express permission, possibly a seperate effect, SleepIO.

```
import Effects
import Control.IOExcept
import System

data SleepIO : Effect where
        Sleep : Int -> {()} SleepIO ()
  
instance Handler SleepIO IO where
  handle () (Sleep s) k = do usleep s; k () ()
  
instance Handler SleepIO (IOExcept a) where
  handle () (Sleep s) k = do ioe_lift $ usleep s; k () ()
  
SLEEPIO : EFFECT
SLEEPIO = MkEff () SleepIO
  
sleep : Int -> {[SLEEPIO]} Eff ()
sleep s = call $ Sleep s
```

**Comment by jfdm** [comment]
@eborden The reason that sleep is not in the `STDIO` effect, I contend, is that it is an effectual operation provided by the system. Thus it should be an operation provided by the `SYSTEM` effect. [Checking the (albeit out-of-dated) documentation](http://www.idris-lang.org/docs/effects_doc/docs/Effect.System.html) reveals that it is not there. That is most likely due to programmer error.

You are welcome to submit a PR for the `SYSTEM` effect adding a sleep function.

**Comment by edwinb** [comment]
Effects can be quite fine-grained - StdIO is meant to capture console IO 
only. Also the effects library is still quite experimental so there's 
lots of things missing, especially in system interaction.

At the moment, it might be most appropriate as part of the System 
effect, rather than being on its own.

Effects are still likely to change a bit while we work out the best and 
most efficient way of doing things, so I don't want to put too much 
effort into thinking about organisation quite yet. Still, at some stage 
it'd be nice to have a more complete library of system calls, at a good 
level of granularity (whatever that means).

**Comment by eborden** [comment]
The system reasoning is totally sound. I'll gladly put a PR together.
