### ISSUE TITLE
Strange behavior in implicit function argument

### ISSUE THREAD

**Issue by rmonascal** [idris-lang/Idris-dev#1896]
Hi everyone!

I write on behalf of a group of people from Venezuela that decided to explore Idris and its implementation of dependant types. In the Idris tutorial, chapter 8, we found a definition for a theorem that states that `Z : Nat` is a right identity for function `plus : Nat -> Nat -> Nat`.

```
plusReducesZ : (n : Nat) -> n = plus n Z
plusReducesZ Z = refl
plusReducesZ (S k) = cong (plusReducesZ k)
```

The signature of function `cong` is: `{f : t -> u} -> a = b -> f a = f b`, so `f` is passed as an implicit argument.

After analyzing the definition of `plusReducesZ`, we concluded that the implicit argument `f` must be `S` (the successor constructor for `Nat`). So, writing `cong {f = S} (plusReducesZ k)` should be just as valid, and Idris does allow it.

The problem is that almost any function we tried of the form `Nat -> Nat` does the trick, including `(+2)`, `(-1)`, `pred`, `(*2)`, etc. Oddly, `(div 4)` does *not* pass the typecheck, but `\x => div 4 x` does. We think there could be something wrong with typechecking at this point. Or maybe there is something we are not quite understanding yet.

Any help or comment will be most appreciated. Thank you!

**Comment by edwinb** [comment]
Typechecking the final program is fine, but the curious thing is that 
it's decided to replace the explicit 'f' you give with 'S' (which is 
what makes typechecking succeed). You can see the exact thing it's 
filled by using :set showimplicits then :printdef

I don't know why it's doing this because if you give something 
explicitly, unification is supposed to leave it alone. It's possible 
that a recent change has caused a regression so I'll take a look.

By the way, are you using the most up to date Idris? The 'refl' 
constructor is now called 'Refl' which suggests you might be using a 
fairly old version.

Edwin.

**Comment by rmonascal** [comment]
Hi Edwin!

   Thanks for your help! Yes, we were using Idris 0.9.14.2. We'll update everything to keep up with the latest version.
