### ISSUE TITLE
Implicit argument to rank-n type for type-class member requires passing explicit argument

### ISSUE THREAD

**Issue by puffnfresh** [idris-lang/Idris-dev#1899]
The following code compiles but shouldn't:

```idris
%default total

InterpBool : () -> Type
InterpBool () = {x : Type} -> x -> Nat

class IdrisBug (u : ()) where
  idrisBug : InterpBool u

instance IdrisBug () where
  idrisBug _ = Z

f : Nat
f = idrisBug {u = ()} Char 'a'
```

Notice the explicit `Char` type being supplied to `idrisBug`, that is an explicit argument required for the implicit `x` type in `InterpBool ()`.

I have no idea why Idris requires it to be explicit! Seems like `f` should only work like so:

```idris
f : Nat
f = idrisBug {u = ()} {x = Char} 'a'
```

But maybe not. I'm unsure what the semantics should be.

**Comment by edwinb** [comment]
That's very odd. I wonder if the knowledge of implicitness of the binder 
is getting dropped somewhere. I'll take a closer look.

Thanks for trying this and reporting - being new, I wouldn't be 
surprised if there's a few odd corners here that I've overlooked.

**Comment by edwinb** [comment]
Okay, not sure I'll get to this today (I will try) but here's what I've 
found - it's more a note to myself than anything else.

The scoped implicits get added by the elaborator on encountering a 
function application. At that point, it looks at the the of the function 
and checks for any Pi binders marked implicit, and adds argument as 
required.

Unfortunately, here, at that point the type is
```(u : Unit) -> Main.IdrisBug u -> Main.InterpBool u```

because it hasn't elaborated the `u` argument yet, so it doesn't know 
that `InterpBool u` is expecting an implicit. Oops.

I hope this helps future-me (or whoever) fix this, as well as explaining 
what's going on :).

I should have guessed that this feature wouldn't be quite as simple as 
the implementation turned out to be!

**Comment by edwinb** [comment]
I'm not entirely happy with my fix for this (it's a bit of a hack, checking the type of the result and going around again if there are still implicits to be added at the end...) but it does fix the problem above.

There is still a corner case that doesn't quite work with scoped implicits: if your function returns something with a type of the form {imp : Ty} -> Foo (i.e., there are *only* implicit arguments) you will still get surprising behaviour. I'll fix that one shortly.
