### ISSUE TITLE
Instance of constructor guarding seems to fail totality checker

### ISSUE THREAD

**Issue by puffnfresh** [idris-lang/Idris-dev#1923]
Quick go at encoding a partiality monad:

```idris
%default total

data Partiality : Type -> Type where
  Roll : Inf (Partiality a) -> Partiality a
  Pure : a -> Partiality a

instance Functor Partiality where
  map f fa = Roll (map f fa)

instance Applicative Partiality where
  (<$>) fa fb = Roll (fa <$> fb)
  pure a = Pure a

instance Monad Partiality where
  (>>=) fa f = Roll (fa >>= f)

mcarthy91 : Nat -> Partiality Nat
mcarthy91 n = if n > 100
              then Pure (n - 10)
              else Roll (Delay (mcarthy91 (n + 11) >>= mcarthy91))
```

The McCarthy 91 function gives:

```
Type checking /tmp/Partiality.idr
/tmp/Partiality.idr:19:1:
Main.mcarthy91 is possibly not total due to recursive path Main.mcarthy91
```

But it seems like my definition has delay which is actually constructor guarded. Am I wrong?

**Comment by edwinb** [comment]
This is correct behaviour according to the rules currently used to 
decide productivity, because 'if...then...else' is desugared into a 
function so there is a function call between the guard and the left hand 
side.

If you use 'case' instead then it will work (although I'm not completely 
convinced it should given the way case is desugared, I need to poke this 
more closely).

In any case, this is a common pattern (I've run into it recently 
myself), so maybe it's okay to teach the checker about it.

Edwin.

**Comment by puffnfresh** [comment]
You mean to use case on the Bool? That doesn't seem to work:

```idris
mcarthy91 : Nat -> Partiality Nat
mcarthy91 n = case n > 100 of
                True => Pure (n - 10)
                False => Roll (Delay (mcarthy91 (n + 11) >>= mcarthy91))
```

I'm confused why it would, because `if` desugars to `boolElim`, right? Does totality checking happen before that is inlined?

**Comment by puffnfresh** [comment]
Also, that just makes the error message tell us less about the error:

```
Type checking /tmp/Partiality.idr
/tmp/Partiality.idr:18:1:
Main.mcarthy91 is possibly not total due to: Main.case block in mcarthy91
```

**Comment by edwinb** [comment]
On 16/02/2015 19:39, Brian McKenna wrote:
> I'm confused why it would, because |if| desugars to |boolElim|, right?
> Does totality checking happen before that is inlined?

Yes. And inlining isn't going to happen here anyway because it'll still 
get stuck on the Bool it's looking at which isn't in canonical form.

More importantly, I notice also that the calls to mcarthy91 aren't 
actually constructor guarded, because they're under the >>=.

Edwin.

**Comment by puffnfresh** [comment]
I managed to encode the function by taking @edwinb's IRC suggestion to encode a fixpoint:

```idris
%default total

data Partiality : Type -> Type where
  Roll : Inf (Partiality a) -> Partiality a
  Pure : a -> Partiality a

instance Functor Partiality where
  map f fa = Roll (map f fa)

instance Applicative Partiality where
  (<$>) fa fb = Roll (fa <$> fb)
  pure a = Pure a

instance Monad Partiality where
  (>>=) fa f = Roll (fa >>= f)

never : Partiality a
never = Roll never

fix' : (a -> Partiality b) -> ((a -> Partiality b) -> a -> Partiality b) -> a -> Partiality b
fix' f g x with (g f x)
  | Roll d = Roll (fix' (g f) g x) 
  | Pure b' = Pure b'

fix : ((a -> Partiality b) -> a -> Partiality b) -> a -> Partiality b
fix = fix' (const never)

mcarthy91' : (Nat -> Partiality Nat) -> Nat -> Partiality Nat
mcarthy91' fn n = if n > 100
                  then Pure (n - 10)
                  else Roll (Delay (fn (n + 11) >>= fn))

mcarthy91 : Nat -> Partiality Nat
mcarthy91 = fix mcarthy91'
```

I worked off an example presented here:

http://article.gmane.org/gmane.comp.lang.agda/218
