### ISSUE TITLE
make test_c: strange error on Windows

### ISSUE THREAD

**Issue by Heather** [idris-lang/Idris-dev#1936]
``` shell
make -C test IDRIS=../dist/build/idris
make[1]: Entering directory `/c/H/P/Idris-dev/test'
Running basic001...
sh: -c: line 0: syntax error near unexpected token `('
```

By the way: why `make test` including `doc` task?

**Comment by david-christiansen** [comment]
I made `make test` run Haddock because I was tired of cleaning up after commits that caused Haddock to stop working, so the default test script checks that they in fact work. If you run the more specific test targets (like `test_c`) it gets skipped, for reasons of fast execution.

As far as the Windows error goes, I don't have a Windows machine with Haskell handy - perhaps @melted has seen this before?

**Comment by melted** [comment]
This should be fixed now with this batch of commits

**Comment by david-christiansen** [comment]
Thanks!
