### ISSUE TITLE
Roll back on type class resolution

### ISSUE THREAD

**Issue by defanor** [idris-lang/Idris-dev#1986]
Once Idris finds an instance satisfying one of type class constraints, it infers more data from it, and then doesn't roll back to try to find another instance, if it fails to resolve other constraints with the first found one.
Here's an example:

```idris
class Foo a b where
  foo : a -> b
instance Foo a a where
  foo = id
instance Foo Bool Nat where
  foo x = Z

class Bar a where
  bar : a -> a -> a
instance Bar Nat where
  bar x y = x + y
instance Bar Bool where
  bar x y = x && y

baz : (Foo a c, Foo b c, Bar c) => a -> b -> c
baz x y = bar (foo x) (foo y)
```
And in the REPL:
```idris
λΠ> baz True Z
0 : Nat
λΠ> baz Z True
-- Can't resolve type class Foo Nat Bool
λΠ> baz {c=Nat} Z True
0 : Nat
```
There is a workaround that involves some amount of copypasted code (adding a typeclass without methods, which groups those three, and setting its instances for every `c` manually), but would be nice to solve it in the compiler.

Related code: [ElabTerm.hs#L58-L75](https://github.com/idris-lang/Idris-dev/blob/c9b1759d6167688b837a3d9469d952ecf8ffca0d/src/Idris/ElabTerm.hs#L58-L75) and [ElabTerm.hs#L1376-L1470](https://github.com/idris-lang/Idris-dev/blob/c9b1759d6167688b837a3d9469d952ecf8ffca0d/src/Idris/ElabTerm.hs#L1376-L1470).

**Comment by edwinb** [comment]
The main reason for not doing this has been that it would potentially 
get extremely slow if there was a lot of backtracking, so type class 
resolution deliberately commits early.

It might be possible to do something similar to proof search to improve 
this - proof search doesn't even try searching if there are 
metavariables in the type.

**Comment by edwinb** [comment]
I just took a close look at this - I think "baz Z True" *should* fail to work at the REPL, but not for the reason it is failing. It should fail because the target type c isn't known - metavariables shouldn't be instantiated due to type class resolution.

I'm changing type class resolution to give the right behaviour - that is, it shouldn't search for an instance if there are still metavariables in the goal, but should postpone the search instead. Hopefully this won't break anything else, and will get the desired behaviour without any backtracking.
