### ISSUE TITLE
No actual web docs available

### ISSUE THREAD

**Issue by suhr** [idris-lang/Idris-dev#1987]
Provide something like http://doc.rust-lang.org/std/ for the standard library documentation.

**Comment by LeifW** [comment]
We have http://www.idris-lang.org/docs/ (generated from comments in source).
That could probably be made more discoverable and pretty, though.

**Comment by suhr** [comment]
This seems to be outdated (for example, it uses _|_ instead of Void).

>  That could probably be made more discoverable and pretty, though.

Some kind of search would be super nice.

**Comment by jfdm** [comment]
As @LeifW has mentioned there is: http://www.idris-lang.org/docs/ . IIRC, the version of the docs was part of a prerelease to gauge peoples reaction to them. We do plan to keep the docs more inline with released versions of Idris. 

As for search these docs, have you played around with the Idris REPL, we do have the `:apropos` and `:search` commands. The former behaviours similarly to the apropos terminal command,and the latter more akin to google.

**Comment by edwinb** [comment]
If someone can provide a script which will build docs as part of the 
release process, then I will upload them and link them.

Also, if someone can find a way to take the :search and :apropos and 
make them searchable via the web, I will also see what I can do about 
putting them on the web site (this is harder though due to hosting 
limitations)
