### ISSUE TITLE
Type class unexpected behavior

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#1993]
The following type checks
````
> import Control.Monad.Identity
> %default total 

> class Monad m => ContainerMonad (m : Type -> Type) where
>   Elem    : a -> m a -> Type
>   ret     : a -> m a
>   ret     = pure
>   spec1   : {x : a} -> Elem {a = a} x (pure {a = a} x)

> instance ContainerMonad Identity where
>   Elem a1 (Id a2) = a1 = a2
>   spec1 = Refl
```
But replacing 
````
>   spec1   : {x : a} -> Elem {a = a} x (pure {a = a} x)
```
with
````
>   spec1   : {x : a} -> Elem {a = a} x (ret {a = a} x)
```
yields
````
- + Errors (1)
 `-- typeClasses2.lidr line 12 col 8:
     When elaborating right hand side of Main.Main.Identity instance of Main.ContainerMonad, method spec1:
     Can't unify
             x1 = x1
     with
             Main.Identity instance of Main.ContainerMonad, method Elem a x (Main.Identity instance of Main.ContainerMonad, method ret a x)
```
Is this the expected behavior ? How can I say that `Identity` is an instance of `ContainerMonad` when `spec1` is defined in terms of `ret` ? Thanks, Nicola

**Comment by edwinb** [comment]
Curiously, if you give an explicit definition of 'ret' rather than using the default, this works fine (at least it does after I fixed a thing which arose from the recent type class fixes). This suggests default instances are not quite working as they should in the presence of dependent type classes, in that reduction is being blocked.
