### ISSUE TITLE
Named instances with constraints don't seem to work correctly

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#2026]
The following code can be loaded without problems:
```
instance [mine] (Monad m) => Functor m where
```
It gives the following metavar:
```
Metavariables:
- + Docs.mine [P]
 `--          m : Type -> Type
      constrarg : Monad m
     --------------------------
      Docs.mine : Functor m
```

However, when I have Idris fill out the body of the instance and reload, I get an error. The generated code is:
```
instance [mine] (Monad m) => Functor m where
    map m x = ?Functor_rhs_1
```
and the error message is:
```
- + Errors (1)
 `-- Docs.idr line 91 col 9:
     When elaborating type of Prelude.Functor.Docs.mine, method map:
     Can't convert
             Type
     with
             a
```

**Comment by edwinb** [comment]
This turns out not to be named instances, but an issue of parameter naming. The following code exhibits exactly the same issue:

```
class MyFunctor (f : Type -> Type) where
    mymap : (m : a -> b) -> f a -> f b
  
instance MyFunctor m where
    mymap m x = ?Functor_rhs_1
```

This is a naming issue that I encountered ages ago, knew was still lurking, and have never encountered any code which reproduces it until now or been able to remember enough to contrive some code. So thanks for that! I'm on the case...
