### ISSUE TITLE
:search, :apropos should give feedback if nothing is found

### ISSUE THREAD

**Issue by JakobBruenker** [idris-lang/Idris-dev#2091]
Currently, :search doesn't return anything if there is nothing that matches the required type. It would be better if the user got some kind of feedback, like a message saying "No results" or something similar.

The same applies to :apropos, although :apropos returns two empty lines if nothing is found (which, obviously, is not much better than nothing.)

**Comment by david-christiansen** [comment]
If anyone is looking for a good first contribution to Idris, this is one. I'm happy to guide you through implementing this.

**Comment by david-christiansen** [comment]
The implementation of `:apropos` is `Repl.hs` [in the function `process`](https://github.com/idris-lang/Idris-dev/blob/0f86748e506f5da568423f363389554016235774/src/Idris/REPL.hs#L1223-L1242). The variables `mods` and `aproposInfo` are, together, the results that will be displayed, where the first is the found modules and the second is everything else. This is because modules are not first-class in Idris. To add a nice message, check that both of those lists are empty, and if so, use `iRenderResult` to say "Nothing found" or something similar. `iRenderResult` is kind of like `putStrLn` except it takes a pretty-printer document as its argument and it handles connected IDE clients as well as the command line.

**Comment by david-christiansen** [comment]
The relevant type search code is in `TypeSearch.hs` [in `searchByType`](https://github.com/idris-lang/Idris-dev/blob/0f86748e506f5da568423f363389554016235774/src/Idris/TypeSearch.hs#L57-L60). To fix this ticket here, a similar technique should be used with `iRenderResult` to send "Nothing found" if the list `docs` is empty.

**Comment by mattias-lundell** [comment]
Looks like a good easter project, I can take a stab at it.

**Comment by david-christiansen** [comment]
An alternative approach with both of these is to use `iRenderError` to flag the output as an error message, which might lead to better interactions with IDE clients. Another improvement that could be made above the baseline is to say what type was searched for in the error for `searchByType`: something like `iRenderError $ text "No results found for" <+> pprintTerm i ty` after setting `Delab.hs` to export `pprintTerm` and importing it to `TypeSearch.hs`.

**Comment by david-christiansen** [comment]
More that might be interesting: `Doc a` is the type of pretty-printer documents annotated with semantic information `a`, `IState` is the global Idris state that's used in the user-facing parts, `Delaborate.hs` has code to convert core language terms to high-level Idris language terms.

**Comment by david-christiansen** [comment]
Finally, remember to add yourself to the `CONTRIBUTORS` file when you're done so that you're remembered as a co-author of the compiler :-)

**Comment by david-christiansen** [comment]
Please let me know if more questions come up - my IRC presence might be somewhat limited over the weekend, but I'll check back here from time to time.

**Comment by david-christiansen** [comment]
@mattias-lundell: There is someone else working on this right now, just to warn you: [@japesinator](https://twitter.com/japesinator/status/583595376885669888). We do have some [other good starting projects](https://github.com/idris-lang/Idris-dev/issues?q=is%3Aopen+is%3Aissue+label%3A%22Low+hanging+fruit%22) though.
