### ISSUE TITLE
Totality check gets confused by type synonym

### ISSUE THREAD

**Issue by treeowl** [idris-lang/Idris-dev#2129]
This works:

```idris
%default total
succNotLTE' : (LTE (S x) x) -> Void
succNotLTE' {x = Z} prf = succNotLTEzero prf
succNotLTE' {x = (S k)} (LTESucc prf) = succNotLTE' prf

succNotLTE : Not (LTE (S x) x)
succNotLTE = succNotLTE'
```

This does not:

```idris
%default total
succNotLTE : Not (LTE (S x) x)
succNotLTE {x = Z} prf = succNotLTEzero prf
succNotLTE {x = (S k)} (LTESucc prf) = succNotLTE prf
```

**Comment by edwinb** [comment]
I think the coverage checker is assuming types have been normalised, 
which they haven't been here - should be a quick fix, and an opportunity 
for an interested person to see at a high level how the coverage checker 
works. Anyone interested in taking a look?

I thought I had fixed this a while ago, but it's possible I only got as 
far as deciding what the problem was...

This is likely to be the same problem as #2119

**Comment by edwinb** [comment]
This looks like it works fine now.
