### ISSUE TITLE
Internal "Non-exhaustive patterns in case" error, problem with records ?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2130]
The following program
````
> import Data.Vect
> import Data.Fin

> %default total 

> idSuccPreservesLTE : (m : Nat) -> (n : Nat) -> m `LTE` n -> m `LTE` (S n)
> idSuccPreservesLTE  Z     n    prf = LTEZero
> idSuccPreservesLTE (S m)  Z    prf = absurd prf
> idSuccPreservesLTE (S m) (S n) prf = LTESucc (idSuccPreservesLTE m n (fromLteSucc prf))

> ltZS : (m : Nat) -> LT Z (S m)
> ltZS  Z    = LTESucc LTEZero 
> ltZS (S m) = idSuccPreservesLTE (S Z) (S m) (ltZS m)

> record Preorder : {T : Type} -> (T -> T -> Type) -> Type where
>   MkPreorder : {T : Type} -> 
>                (R : T -> T -> Type) ->
>                (reflexive : (x : T) -> R x x) ->
>                (transitive : (x : T) -> (y : T) -> (z : T) -> R x y -> R y z -> R x z) ->
>                Preorder R

> record TotalPreorder : {T : Type} -> (T -> T -> Type) -> Type where
>   MkTotalPreorder : {T : Type} -> 
>                     (R : T -> T -> Type) ->
>                     (reflexive : (x : T) -> R x x) ->
>                     (transitive : (x : T) -> (y : T) -> (z : T) -> R x y -> R y z -> R x z) ->
>                     (either : (x : T) -> (y : T) -> Either (R x y) (R y x)) ->
>                     TotalPreorder R

> argmaxMax : {A : Type} -> {R : A -> A -> Type} -> TotalPreorder {T = A} R -> 
>             Vect n A -> LT Z n -> (Fin n, A)
> argmaxMax         {n = Z}       tp  Nil                p = absurd p
> argmaxMax         {n = S Z}     tp (a :: Nil)          _ = (FZ, a)
> argmaxMax {A} {R} {n = S (S m)} (MkTotalPreorder R r t e) (a' :: (a'' :: as)) _ 
>   with (argmaxMax (MkTotalPreorder {T = A} R r t e) (a'' :: as) (ltZS m))
>     | (k, max) with (e a' max)
>       | (Left  _) = (FS k, max)
>       | (Right _) = (FZ, a')
```
does not type check:
````
idris: src/Idris/Elab/Utils.hs:(196,30)-(198,42): Non-exhaustive patterns in case
```
but commenting out the `Preorder` declaration
````
> import Data.Vect
> import Data.Fin

> %default total 

> idSuccPreservesLTE : (m : Nat) -> (n : Nat) -> m `LTE` n -> m `LTE` (S n)
> idSuccPreservesLTE  Z     n    prf = LTEZero
> idSuccPreservesLTE (S m)  Z    prf = absurd prf
> idSuccPreservesLTE (S m) (S n) prf = LTESucc (idSuccPreservesLTE m n (fromLteSucc prf))

> ltZS : (m : Nat) -> LT Z (S m)
> ltZS  Z    = LTESucc LTEZero 
> ltZS (S m) = idSuccPreservesLTE (S Z) (S m) (ltZS m)

> {-
> record Preorder : {T : Type} -> (T -> T -> Type) -> Type where
>   MkPreorder : {T : Type} -> 
>                (R : T -> T -> Type) ->
>                (reflexive : (x : T) -> R x x) ->
>                (transitive : (x : T) -> (y : T) -> (z : T) -> R x y -> R y z -> R x z) ->
>                Preorder R
> -}

> record TotalPreorder : {T : Type} -> (T -> T -> Type) -> Type where
>   MkTotalPreorder : {T : Type} -> 
>                     (R : T -> T -> Type) ->
>                     (reflexive : (x : T) -> R x x) ->
>                     (transitive : (x : T) -> (y : T) -> (z : T) -> R x y -> R y z -> R x z) ->
>                     (either : (x : T) -> (y : T) -> Either (R x y) (R y x)) ->
>                     TotalPreorder R

> argmaxMax : {A : Type} -> {R : A -> A -> Type} -> TotalPreorder {T = A} R -> 
>             Vect n A -> LT Z n -> (Fin n, A)
> argmaxMax         {n = Z}       tp  Nil                p = absurd p
> argmaxMax         {n = S Z}     tp (a :: Nil)          _ = (FZ, a)
> argmaxMax {A} {R} {n = S (S m)} (MkTotalPreorder R r t e) (a' :: (a'' :: as)) _ 
>   with (argmaxMax (MkTotalPreorder {T = A} R r t e) (a'' :: as) (ltZS m))
>     | (k, max) with (e a' max)
>       | (Left  _) = (FS k, max)
>       | (Right _) = (FZ, a')
```
type checks fine. If the two `record` declarations are replaced by plain `data` declarations, both the uncommented and the commented versions type check fine. Perhaps a problem with records ?

**Comment by david-christiansen** [comment]
This is clearly a compiler bug in any case - the compiler should not crash!. I'll try to find some time to look into it soon.

**Comment by david-christiansen** [comment]
Though @sualitu's new record implementation might render it a moot point - how's that coming @sualitu?

**Comment by treeowl** [comment]
I ran into this exact error just now with a much smaller example and no records in sight:

```idris
module MinCrash

revInduction : (P : List a -> Type) -> P [] -> ((xs : List a) -> (x : a) -> P xs -> P (xs ++ [x]))
               -> (ys : List a) -> P ys
revInduction pred base ind ys with (reverse ys)
  revInduction pred base ind _ | revys =
    ?revInduction_rhs
```

**Comment by david-christiansen** [comment]
This seems to be happening when local names shadow overloaded global names (in this case `pred`). Will report back when I've figured out a bit more.

**Comment by david-christiansen** [comment]
OK, figured it out. At one point, the system was looking up global names using a disambiguating match, which failed if multiple definitions were found. Normally, this wouldn't be a problem, because it's got fully-qualified names at that stage of the elaborator, but it was looking up bound variable names. If a bound variable had the same name as two or more global names, this would then crash.

**Comment by david-christiansen** [comment]
Fix incoming.

**Comment by david-christiansen** [comment]
@nicolabotta It seems that your issue with the records came up because the projections caused the ambiguity that I mentioned above. Yours and @treeowl's code is now in there as regression tests.

Thanks for good examples to work with!

**Comment by treeowl** [comment]
I'm just wondering if there's a way to get rid of that incomplete pattern in the Haskell code altogether.

**Comment by david-christiansen** [comment]
@treeowl I don't think there's a good way to get rid of it without major changes (which may well be warranted, but I can't do it right now for reasons of time, energy, and focus).

In some parts of the compiler, we can use `lookupCtxtExact :: Name -> Ctxt a -> Maybe a` that returns the unique thing that a name maps to, if there's precisely one, or `Nothing` in case of ambiguity.  At this point, however, if a name is not fully resolved, then it means something has gone horribly wrong earlier in the compiler. Returning `Nothing` would cause it to silently compute the wrong answer in case of ambiguity, which in my opinion is worse than crashing and letting us know that things were wrong.

But contributions towards making these assumptions more evident in the code (and where possible guaranteeing them) are highly welcome, so long as they don't make the code into an unmaintainable soup of crazy new extensions. We're fairly conservative about the fancier Haskell features, in order to keep the implementation understandable, but if you can get rid of lots of horrible partial matches with a nice data structure change or a different lookup, then that would be great!
