### ISSUE TITLE
Building Against LTS Haskell.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2135]
[LTS Haskell](https://github.com/fpco/lts-haskell) is an [FP Complete](https://www.fpcomplete.com) project to provide: *a curated set of packages which includes non-breaking point releases*. FP Complete provides a cabal configuration file that can be used by package developers to pin their library dependencies against. Using LTS Haskell:

1. We can develop Idris against a set of packages that are known to work together.
2. Reduces the chances of users encountering cabal hell.
3. Update package constraints in a timely manner.

However, the LTS Haskell Project is still young and developing its goals and procedures. The question is:

> Should we look to specify our dependencies for Idris against LTS Haskell?

Personally, I believe it is worth it, but I am not familiar enough with Haskell packaging and the effects of using a custom cabal config will have on the project and its dissemination. Thus, I am going to leave the following set of [numpty](http://bit.ly/JEZLF3) questions here:

+ [X] Can Idris actually build against LTS Haskell?
  + As of `2015-08-15` Idris can be built with LTS Haskell 3.0
+ [X] How does switching to LTS Haskell affect the build process for those building against HEAD and in sandboxes?
  + Add the LTS Haskell config to the local repo as `cabal.config`.
+ [X] How does this affect developing against different versions of GHC? 
  + LTS Haskell is defined against `GHC 7.8.X`, when reconfiguring Idris's dependencies for hackage and testing on travis the bounds might need to be widened to support `GHC 7.10.X`. 
+ [ ] How will this affect our CI testing with Travis?
  + LTS Hackage uses GHC 7.8.4. To build better bounds for multiple GHC versions, the [hvr/multi-ghc-travis](https://github.com/hvr/multi-ghc-travis) can be used to test Idris against these versions.
  + There is a [stackage mailing list thread](https://groups.google.com/forum/#!topic/stackage/bB0-kW4ETSo) that highlights the possiblity of a Stackage PPA in the future to make building against LTS Haskell quicker and easier on travis.
  + [ ] Question is still how do we resolve the use of stackage that pins ghc and cabal, and use multi ghc version support in travis? Given multi ghc, do we actually need to 'use' stackage on travis?
+ [X] How does this affect releasing Idris on Hackage?
  + The affect will only be a release with a better configuration over dependencies. Again bounds may need to be widened to support non-stackage users.
+ [X] How do we react to new releases of LTS Haskell?
  + Swap out the old `cabal.config` for the new one, and fix bounds as necessary.
  + [Stackage-CLI](https://www.fpcomplete.com/blog/2015/04/announcing-stackage-cli) might address these issues.
+ [X] Are there any reasons to not use LTS Haskell?
  + `GHC 7.10.X` is not supported, and given conservative policies on version bounds, Idris might be struggle to be built against LTS Haskell.
+ [X] LTS Haskell has major and minor releases, which one should we follow?
  + Major
+ [ ] How does migration affect the location of the lib directory.

If you can think of any more questions add them below and I will add them here. If you can answer the questions, answer them below and I will link to the answers in this issue.

**Edit** Added in responses from @acfoltzer and @david-christiansen 
**Edit** Update to reflect Stackage-CLI
**Edit** Add results of dependancy analysis, and missing interpretation of stickage contents.
**Edit** Updated section about effect on using LTS Haskell with Travis.
**Edit** Updated section about using LTS Haskell with Travis, and building against LTS Haskell.
**Edit** Updated to reflect release of LTS Haskell 3.0 and that idris can build with it.

**Comment by acfoltzer** [comment]
We recently started using LTS Stackage for a group of related packages here at Galois, and have been enjoying the resulting stability quite a bit. The key benefit was just getting *some* consistent set of dependencies frozen across all the packages. It's something we could have done manually or with `cabal freeze`, but using Stackage means that we'll continue to get newer versions without having to manually hunt for solutions. By adding our own packages to Stackage, we also get an early warning system when downstream users might wind up wedged.

As for the specific questions that I can speak to:

> How does switching to LTS Haskell affect the build process for those building against HEAD and in sandboxes?

With our setup it's pretty lightweight; we just add the `cabal.config` to the repository and the rest of the build proceeds as usual. This only becomes a problem if individual developers want to have their own local (not user-wide) `cabal.config` settings for a particular project. In those cases folks modify the Stackage one locally, but this is very awkward with git.

> How does this affect developing against different versions of GHC?

This is trickier, as Stackage currently targets a single GHC. We can test with other versions by moving the `cabal.config` out of the way and running the build, but of course that means that the non-Stackage builds have to find their own dependency solution, and we're back to the headaches we wanted to avoid in the first place.

> How does this affect releasing Idris on Hackage?

It shouldn't. See [cryptol](http://hackage.haskell.org/package/cryptol): there's no indication other than the link to the Stackage distribution that Cryptol is built with a Stackage config in place. There are still looser bounds on the dependencies, so that folks who don't use Stackage should still be able to find a solution, but it's totally opt-in.

> How do we react to new releases of LTS Haskell?

In our experience, it's a matter of swapping out the `cabal.config`, and fixing any errors that crop up as a result. The pain is similar to whenever one adopts a newer version of a package, except that it happens in one big burst with multiple packages (which I actually prefer).

> Are there any reasons to not use LTS Haskell?

The main reasons are the ability to pick your own GHC version. 

1. Right now, LTS is tied to 7.8.4, which might not work if folks consider that too ancient to use at this point :wink:
2. LTS tends to be conservative about adopting new versions of packages vs. removing downstream dependencies from LTS. [lens](https://github.com/fpco/stackage/issues/467) is a good example: it has quite a few downstream dependencies, and because they weren't updated in time, the LTS version is a couple point releases behind the latest and greatest.

> LTS Haskell has major and minor releases, which one should we follow?

The major releases are the ones to really pay attention to. LTS versions follow the [PVP](https://wiki.haskell.org//Package_versioning_policy) w.r.t. the packages they include, so as long as maintainers are good PVP citizens, minor LTS releases are bugfixes only.

**Comment by jfdm** [comment]
@acfoltzer Cheers for your comments. It appears as if switching to LTS Haskell appears to be pretty straight forward with few minor adjustments to the 'release' processes. GHC version pinning aside, it appears to be good.

**Comment by david-christiansen** [comment]
We can also continue to run tests on other versions of GHC, so we don't leave those users out in the cold by accident and so we know that our wider bounds make some sense.

**Comment by david-christiansen** [comment]
As far as Travis goes (item 4 on your list), I think that it makes sense to use more that just LTS Haskell there. This makes sure that we don stomp on other versions. It probably doesn't have to change much.

**Comment by jfdm** [comment]
So I had a quick look at the dependancies for both Idris the library and and what is on Stackage for the latest LTS Haskell.

There are three packages missing from Stackage and will need to be included.
+ `annotated-wl-print`
+ `cheapskate`
+ `Win32`

There are two packages that are too modern with version numbers outside our bounds:
+ `blaze-markup` we ask for `>= 0.5.2.1 && < 0.6.3.0` they have `0.7.0.2`
+ `utf8-string` we ask for `< 0.5` they have `1.0`

The remaining packages on stackage satisfy the bounds we place on dependancies.

Actionable steps are:

1. Get `annotated-wl-pprint`, `cheapskate`, and `win32` onto stackage. We need to love bomb the authors. [Package Author information is available](http://www.stackage.org/authors)
2. Determine what to do about `blaze-markup` and `utf8-string`, that is can we adjust our bounds to use the versions on stackage.

The table is:

 Package                 | Idris Bounds            | Stackage Version 
 -------------------------|----------------------------|-------------
 base                    | >=4 && <5               |          4.7.0.2 
 annotated-wl-pprint     | >= 0.5.3 && < 0.6       |              --- 
 ansi-terminal           | < 0.7                   |          0.6.2.1 
 ansi-wl-pprint          | < 0.7                   |          0.6.7.2 
 base64-bytestring       | < 1.1                   |          1.0.0.1 
 binary                  | >= 0.7 && < 0.8         |          0.7.1.0 
 blaze-html              | >= 0.6.1.3 && < 0.8     |          0.8.0.2 
 blaze-markup            | >= 0.5.2.1 && < 0.6.3.0 |          0.7.0.2 
 bytestring              | < 0.11                  |         0.10.4.0 
 cheapskate              | < 0.2                   |              --- 
 containers              | >= 0.5 && < 0.6         |          0.5.5.1 
 deepseq                 | < 1.5                   |            3.0.2 
 directory               | >= 1.2 && < 1.3         |          1.2.1.0 
 filepath                | < 1.5                   |          1.3.0.2 
 fingertree              | >= 0.1 && < 0.2         |          0.1.0.2 
 haskeline               | >= 0.7 && < 0.8         |          0.7.1.2 
 lens                    | >= 4.1.1 && < 4.9       |          4.7.0.1 
 mtl                     | >= 2.1 && < 2.3         |          2.1.3.1 
 network                 | < 2.7                   |          2.6.0.2 
 optparse-applicative    | >= 0.11 && < 0.12       |         0.11.0.2 
 parsers                 | >= 0.9 && < 0.13        |         0.12.1.1 
 pretty                  | < 1.2                   |          1.1.1.1 
 process                 | < 1.3                   |          1.2.0.0 
 split                   | < 0.3                   |            0.2.2 
 text                    | < 1.3                   |          1.2.0.4 
 time                    | >= 1.4 && < 1.6         |            1.4.2 
 transformers            | < 0.5                   |          0.3.0.0 
 transformers-compat     | >= 0.3                  |          0.4.0.3 
 trifecta                | >= 1.1 && < 1.6         |          1.5.1.3 
 uniplate                | >=1.6 && < 1.7          |           1.6.12 
 unordered-containers    | < 0.3                   |          0.2.5.1 
 utf8-string             | < 0.4                   |                1 
 vector                  | < 0.11                  |        0.10.12.3 
 vector-binary-instances | < 0.3                   |          0.2.1.0 
 xml                     | < 1.4                   |           1.3.14 
 zlib                    | < 0.6                   |          0.5.4.2 
 safe                    |                         |            0.3.8 
 unix                   | < 2.8 | 2.7.0.1
Win32                 | < 2.4 | ---

**Comment by acfoltzer** [comment]
The dependencies don't need to all be on Stackage in order to build against Stackage; you still have all of Hackage available but the versions of certain packages are constrained.

**Comment by jfdm** [comment]
Cheers for that. Somehow I missed that crucial part out, and thought that stockage *only* contained package sets that build together nicely.

**Comment by jfdm** [comment]
@david-christiansen I see on the IRC channel you enquired about people with experience in using travis to test against multiple GHC (i.e. hvr/multi-ghc-travis ) If I am right in your thinking, we can use this to reliably test idris against mutli GHCs and help adjust package bounds.

Secondly, I have looked into compiling Idris against LTS Haskell this morning, the major blocker I have encountered is `cheapskate`. The version on hackage requires a slightly older version of `blaze-html`. Fortunately the upstream version of `cheapskate` has better bounds. This problem shoudl disappear on the next `cheapskate` release. I also imagine that the `Win32` package will not be a problem, ditto for `annotated-wl-pprint`.

Thus, I think we are actually close to being able to build against LTS Haskell.

**Comment by Heather** [comment]
@jfdm seems like table is outdated, at least few weeks ago I discussed with @david-christiansen and @edwinb about `directory` downgrade from this push `directory >= 1.2.2.0 && < 1.3` https://github.com/idris-lang/Idris-dev/commit/2de8a47afa223ac831cce71f49917449270d8b33 because `directory` is part of `GHC` and it breaks compatibility with other packages when they are built with different version of `directory`. My issue was understood but in result my ask was rejected in flavor of writing "distropatch" because this package is the only thing that lives in sandbox and don't consider any interactions from outside... As far as I understand Idris philosophy and slack philosophies are very different in this point, maybe I understood something in wrong way.

**Comment by LeifW** [comment]
Idris now installs on GHC 7.10 w/ stackage nightly. Would someone want to test on LTS Haskell 2.17 - GHC 7.8? What else needs to be done to address this? Do we want to get all of Idris' deps, and Idris itself, into stackage?

**Comment by jfdm** [comment]
As a result of #2469 Idris has a stackage file that builds against stackage nightly. This is good. I think best might be to wait until this stackage set gets made into a LTS Haskell release, and at the same time look at how we can update the rest of the infrastructure.

**Comment by jfdm** [comment]
Just an update to this. I updated my stack configuration to use LTS-3.0. My system setup is:

+ Ubuntu LTS 14.04.3 
+ GHC 7.10.2
+ Cabal-Install 1.22.6.0
+ Cabal Library 1.22.4.0
+ Stack Version 0.1.2.0
+ Resolver lts-3.0

Using this setup Idris HEAD can be built using:

```sh
stack install --flag idris:FFI --flag idris:GMP
```

Provided that libFFI is added as a dependency to `stack.yaml` and the bound for lens is increased.

My only concern is building Idris using Stack and the other flags i.e. curses and CI and release, on other platforms i.e. Mac OS X, and Windows.

**Comment by jfdm** [comment]
Right, currently we can build idris using stack and against LTS haskell. I am happy that this satisfy the issue. If no one objects, I am going to close this issue after the weekend, and then open a new issue to suggest replacing our use of cabal with stack.
