### ISSUE TITLE
Data type constructors not total

### ISSUE THREAD

**Issue by fiendfan1** [idris-lang/Idris-dev#2144]
```Idris
module Main

%default total

data Expr : Type -> Type where
  LitFn : (Expr a -> Expr b) -> Expr (a -> b)

toInt : Expr a -> Int
toInt (LitFn _) = 1

idExpr : Expr (a -> a)
idExpr = LitFn id
```
gives the error
```
Main.toInt is possibly not total due to: Main.LitFn

Main.idExpr is possibly not total due to: Main.LitFn
```

**Comment by david-christiansen** [comment]
The problem here is that your type `Expr` is not strictly positive - that is, it has itself to the left of a arrow in a constructor argument. Allowing this would be a hole in the totality checker - see [this Stack Overflow](http://stackoverflow.com/questions/2583337/strictly-positive-in-agda) answer about Agda for a good explanation.

In the meantime, you can achieve something similar, and still get nice Idris syntax for embedded language functions - take a look at the [well-typed interpreter section of the tutorial](http://docs.idris-lang.org/en/latest/tutorial/interp.html) for the encoding of lambda calculus, and [DSL notation](http://docs.idris-lang.org/en/latest/tutorial/syntax.html#dsl-notation) for how to re-use Idris's binders in it.
