### ISSUE TITLE
Pattern matching on Fin fails

### ISSUE THREAD

**Issue by harelfishbein** [idris-lang/Idris-dev#2172]
Can't unify
                Integer (Type of 4)
        with
                Fin 4 (Expected type)

**Comment by david-christiansen** [comment]
This issue is quite difficult to understand - there seems to be some missing context. Would you please provide the actual code that is generating this error message as well as the entire error message (eg, which line it points at in the code)?

**Comment by DanielOberg** [comment]
But this shouldn't be a bug as I understand it. Fin 4 means that the maximum value is _up to_ 4 but not including.

Had the same error before reading the code for Fin... :)

**Comment by jfdm** [comment]
@DanielOberg The question is that we don't actually know what the bug is here. All that has been reported is an error message outside of context. Once we know the context that this message was produce then we can declare if it is an actual error or not.

**Comment by harelfishbein** [comment]
`someFun : Integer -> ...`
`someFun 4 ... =` matches

`someFun : Nat -> ...`
`someFun 4 ... =` matches

`someFun : Float -> ...`
`someFun 4 ... =` matches

`someFun : Fin 5 -> ...`
`someFun 4 ... =` fails

**Comment by david-christiansen** [comment]
Ah, I see what the issue is. Thanks.

I'm a bit surprised that it works for `Nat`, actually - integer literals are transformed to a function call, and function calls aren't allowed in patterns unless justified by some equality constraint imposed by another pattern. There may be some special-casing of `Nat` here.

It might be nice to have some way to mark functions that should be evaluated to yield patterns, however.

**Comment by luke-clifton** [comment]
This seems to affect `Nat`s as well in 0.9.20.

In the mean time, what is the standard way of doing this?

I have a `readVect : String -> IO (Maybe (n ** Vect n Int))` and I wish to call a function `printIfV2 : Vect 2 Int -> IO ()`

~~~ idris
readAndPrint : String -> IO ()
readAndPrint fn =
  case !(readVect fn) of
      Nothing => putStrLn "File reading error"
      Just (S (S Z) ** v) => printIfV2 v
      _ => putStrLn "Incorrect vector length"
~~~
which works fine for 2, but gets pretty tedious pretty fast, so instead I have

~~~ idris
readAndPrint : String -> IO ()
readAndPrint fn =
  case !(readVect fn) of
      Nothing => print "File error"
      Just (n ** v) =>
        case decEq n 2 of
          Yes prf =>
            -- Is there a better way? `rewrite prf in v` didn't work.
            let k = replace {P = \n => Vect n Int} prf v
            in printIfV2 k
          No _ => putStrLn "Wrong vector length"
~~~
which seems more verbose than it needs to be, and doesn't really scale if there are multiple special cases for different `n`s.

(I only ask here because this issue crops up on google when searching, so it might be useful for other people)
