### ISSUE TITLE
Typing list literals in REPL yields error

### ISSUE THREAD

**Issue by morganthomas** [idris-lang/Idris-dev#2178]
Example:

    Idris> [1,2,3]
    Can't disambiguate name: ForeignEnv.::, Prelude.List.::, Prelude.Stream.::

On the other hand:

    Idris> with List [1,2,3]
    [1, 2, 3] : List Integer

But it seems like the former example ought to "just work." One thought would be to define list literals so that [a,b,c] expands to Prelude.List.(::) a (Prelude.List.(::) b (Prelude.List.(::) c Prelude.List.Nil))). I could take a stab at implementing this behavior, if people agree this is a good idea.

**Comment by jfdm** [comment]
@morganthomas The error you are seeing is expected behaviour. The list-like construct `[1,2,3]` is essentially syntactic sugar for a cons style list i.e. `1 :: 2 :: 3 :: Nil`. In Idris if you provide constructors for a cons style list (i.e. `Nil` and `(::)`) Idris will allow you to use the `[]` notation as short hand. We already expand `[1,2,3]` to `1::2::3::Nil` This is good for code readability, but bad when you have multiple data structures that implement Cons: Which data structure do we de-sugar to? This is the essence of the error message you are getting. Idris cannot work out what kind of list to de-sugar `[1,2,3]` to in the REPL. Fortunately, the elaborator can use context to work this out most of the time, thus you don't notice it. The `with` construct allows you to inform the elaborator more about the context you are working in.

**Comment by morganthomas** [comment]
All right, fair enough. So now I understand that this is done on purpose, because we want to be able to use list literals for things other than lists. Largely I was objecting to this behavior on the grounds that it just seems fair that when I type a list literal into the REPL, it should give me a list.

On the other hand, I realize there's a tradeoff being made here; and the behavior is adequately described [in the documentation](http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#useful-data-types). I am also guessing based on comments on [a similar issue](https://github.com/idris-lang/Idris-dev/issues/1359) that this bad behavior is mainly an issue on the REPL, and it won't really show up in real code.

**Comment by LeifW** [comment]
That can be a bit annoying. One thing that could be done is leaving out `ForeignEnv` and `Stream` from the Prelude, so only `List.::` would be in scope be default. Then everyone using `ForeignEnv` and `Stream` must explicitly import them. Suppose it's a trade-off of which is more annoying to make people do?
