### ISSUE TITLE
backend executables are confusing

### ISSUE THREAD

**Issue by osa1** [idris-lang/Idris-dev#2194]
So apparently users should not run `idris-c`, `idris-javascript` etc. manually, and I think this is weird, because Idris is installing all those executables to users' systems but expecting them to not run those..

As a new user, here's how it caused problems to me:

* `idris` executable always runs the REPL, even if I point it a file. So I thought it's just for repl.
* Seeing all those `idris-c`, `idris-javascript` etc. executables, I thought those should be for compiling Idris programs.
* I wasted some time trying to figure out why `idris-c` is doing linking wrong, and not generating some symbols that are used in generated C files.
* Note that `idris-c`, `idris-javascript` etc. don't have `--help`.
* People on IRC channel pointed out that I'm doing it wrong, instead I should be using `idris` executable at all times.

It seems to me like `idris-c` etc. executables should be removed and backends should be used as libraries/plugins.

**Comment by david-christiansen** [comment]
Thanks for a valuable report! It's always good to see how real users encounter the system.

The reason to have them as separate executables is to make it easier to maintain them outside of the main compiler tree.

Also, it should be possible to call `idris-c` directly, if you provide it with the correct options.

It seems to me that, rather than going for some complicated plugin system, we could either make the backend executables dump helpful messages unless called with a particular flag, or we could install them in Idris's libraries directory instead of where Cabal is putting executables. I prefer the former.

**Comment by david-christiansen** [comment]
I suppose another way to fix this is to have all the backends accept a flag `--yep-this-is-the-main-idris-executable`. If it's not provided, then they ask the user to call the main `idris`.

**Comment by suhr** [comment]
Consider renaming `idris-*` to `idris-codegen-*` to avoid “oh this should compile my code to ‹langname›!” confusion.
