### ISSUE TITLE
Idris js : foreign FFI_JS ".id" generates i$ret = .id; and it causes errors...

### ISSUE THREAD

**Issue by Heather** [idris-lang/Idris-dev#2206]
I used to follow this tutorial: http://raichoo.blogspot.dk/2013/01/idris-to-javascript-playing-with-ffi.html

afaiu for new FFI it will be

``` idris
module Main

--%include javascript "helper.js"

data HTMLElement : Type where
  Elem : Ptr -> HTMLElement

data NodeList : Type where
  Nodes : Ptr -> NodeList

query : String -> JS_IO NodeList
query q = do
  e <- foreign FFI_JS "document.querySelectorAll" (String -> JS_IO Ptr) q
  return (Nodes e)

item : NodeList -> Int -> JS_IO HTMLElement
item (Nodes p) i = do
  i <- foreign FFI_JS ".item" (Ptr -> Int -> JS_IO Ptr) p i
  return (Elem i)

getId : HTMLElement -> JS_IO String
getId (Elem p) = foreign FFI_JS ".id" (Ptr -> JS_IO String) p

setText : HTMLElement -> String -> JS_IO ()
setText (Elem p) s = foreign FFI_JS ".textContent=" (Ptr -> String -> JS_IO ()) p s

main : JS_IO ()
main = do
  e <- query "#test"
  i <- item e 0
  s <- getId i
  setText i (s ++ ": SUPERFOO!!!")
```

but I'm getting error `SyntaxError: Unexpected token .`

on:

``` js
var _idris_Main_46_getId = function(oldbase){
  var myoldbase = new i$POINTER();
  i$valstack_top += 1;
  i$ret = .id;
  i$valstack_top = i$valstack_base;
  i$valstack_base = oldbase.addr;
}
```

**Comment by david-christiansen** [comment]
I haven't used the JS backend before, so please take this with a gigantic grain of salt! But my understanding was that the names of FFI references were JavaScript expression with placeholders for the arguments, rather than e.g. function names as the C backend uses. So instead of ` foreign FFI_JS ".id" (Ptr -> JS_IO String) p`, I'd expect something like `foreign FFI_JS "%0.id" (Ptr -> JS_IO String) p`.

**Comment by raichoo** [comment]
@david-christiansen Yep, you are correct. This is all documented in the tutorial.
