### ISSUE TITLE
FFI types allow exporting functions with unsupported types and throws error during codegen

### ISSUE THREAD

**Issue by prark** [idris-lang/Idris-dev#2229]
exports : FFI_Export FFI_C "test.h" []
    exports = Fun not "not"
                   End

The code above when exported using

    idris test.idr --interface --codegen C -S -o test.c

throws below error.
```
:When elaborating right hand side of exports:
When elaborating argument prf to constructor FFI_Export.Fun:
        Can't solve goal 
                FFI_Exportable (MkFFI C_Types String String) [] (Bool -> Bool)
idris: src/IRTS/Exports.hs:(30,23)-(33,68): Non-exhaustive patterns in case
```

**Comment by lightningy** [comment]
As discussed over #idris, bools are not supported as mentioned in the docs, so the only issue here is for the compiler to report the error better.

**Comment by edwinb** [comment]
That's exactly the error I'd expect. There's nothing special going on
with the way FFI calls are built and so it uses the same error mechanism
as everything else.

If someone wants to add an %error_handler to make it prettier, it would
be useful, but I see this as a feature request rather than a problem.
