### ISSUE TITLE
Type checking eats all memory and hangs 

### ISSUE THREAD

**Issue by harelfishbein** [idris-lang/Idris-dev#2237]
`test : {[ 'V1 ::: STATE  (Vect 3 Float) , 'V2 ::: STATE  (Vect 3 Float) ,`
`                  'V3 ::: STATE  (Vect 3 Float) , 'V4 ::: STATE  (Vect 3 Float) ,`
`                  'V5 ::: STATE  (Vect 3 Float) , 'V6 ::: STATE  (Vect 3 Float) ,`
`                  'V7 ::: STATE  (Vect 3 Float) , 'V8 ::: STATE  (Vect 3 Float) ,`
`                  'V9 ::: STATE  (Vect 3 Float) , 'V10 ::: STATE (Vect 3 Float) ]}` 
`                  Eff (List Float)`
`test = do 'V1 :- put [1,2,3] `
`           pure [1.5]`

`> :l test.idr `
`Type checking ./test.idr` Hangs here
Perhaps Proof search is causing issue?

**Comment by edwinb** [comment]
It's the syntax rule and backtracking in the parser. Instead, better to
use the new (not yet documented) form which doesn't require the syntax rule.

  test : Nat -> Eff (List Float) [stuff]

Syntax rules will always have the potential to cause this, which is why
I think using syntax rule for effects was a mistake.

**Comment by edwinb** [comment]
I'm closing this because it's a problem with syntax rules that I don't intend to fix - syntax rules aren't intended to be used in the heavyweight way I've been trying for Eff. Rather, the new API solves this.
