### ISSUE TITLE
compute tactic fails on Vect.zipWith

### ISSUE THREAD

**Issue by ulidtko** [idris-lang/Idris-dev#2243]
This looks really silly:

```
----------              Assumptions:              ----------
 a : Type
 b : Type
 c : Type
 f : a -> b -> c
 y : Vect (fromInteger 0) b
----------                 Goal:                  ----------
{hole5} : zipWith f [] y = []

-Verified.Applicative.Vect.proveme> compute

----------              Other goals:              ----------
{hole4},{hole3},{hole2},{hole1},{hole0}
----------              Assumptions:              ----------
 a : Type
 b : Type
 c : Type
 f : a -> b -> c
 y : Vect (fromInteger 0) b
----------                 Goal:                  ----------
{hole5} : zipWith f [] y = []


-Verified.Applicative.Vect.proveme> let p1 = (y = [])

----------              Other goals:              ----------
{hole5},{hole4},{hole3},{hole2},{hole1},{hole0}
----------              Assumptions:              ----------
 a : Type
 b : Type
 c : Type
 f : a -> b -> c
 y : Vect (fromInteger 0) b
 p1 = y = [] : Type
----------                 Goal:                  ----------
{hole6} : zipWith f [] y = []


-Verified.Applicative.Vect.proveme> rewrite p1
rewrite_rule does not have an equality type (Type)

-Verified.Applicative.Vect.proveme> 
Abandoned


*Verified/Applicative/Vect> :t \f, y => Vect.zipWith f [] y
(input):0:0:No such variable a

*Verified/Applicative/Vect>
```

`zipWith _ [] _` doesn't compute to nil, despite the direct definition of `zipWith` in the library as:

    zipWith : (a -> b -> c) -> Vect n a -> Vect n b -> Vect n c
    zipWith f []      []      = []
    zipWith f (x::xs) (y::ys) = f x y :: zipWith f xs ys

Also, the prover message about rewrite_rule equality type is clearly incorrect, the right type is visible in the assumption list.

Finally, the repl gives a bad error message for what should've cleanly typecheck.

Something is clearly broken here, but I'm clueless what could it be.

----
Version 0.9.17.1 from Hackage

**Comment by ulidtko** [comment]
@david-christiansen can you please elaborate?

By fundamental equational reasoning, I'd expect that definition `zipWith f [] [] = []` directly leads to a proof that for any `y : Vect 0 b` and any `f : a -> b` it's true that `zipWith f [] y = []`. The (implicit) types are inferred just as I expect; the property `p1 = (y = [])` gets unified as I expect — but `rewrite p1` fails giving contradictory reason. How to expect that?

If not all, how do you prove this simple property?

    zipWithNil : Vect.zipWith f [] y = []
    zipWithNil = ?proveme

**Comment by edwinb** [comment]
There's nothing wrong here. If you look at the definition of zipWith you'll see that the second argument needs to be an empty list to reduce:

    > :printdef Vect.zipWith
    zipWith : (a -> b -> c) -> Vect n a -> Vect n b -> Vect n c
    zipWith f [] [] = []
    zipWith f (x :: xs) (y :: ys) = ((f x y) :: (zipWith f xs ys))

The machine won't do the equational reasoning for you - you need to tell it what to reduce.

Also the thing you've let bound is a type, not an equality proof. It has type 'Type' (the thing you see in the assumptions list is p1 = [value] : [type]. So the error message is completely correct.

You'd probably be better off doing this proof by pattern matching. There's a tutorial at http://docs.idris-lang.org/en/latest/proofs/index.html#proofs-index

**Comment by ulidtko** [comment]
Thank you Edwin.

**Comment by david-christiansen** [comment]
This is actually behaving as it should. Let me walk you through why that is.

The key thing to realize is that there's a pretty big difference between a function clause that has just a variable or universal pattern and a function clause that has a concrete constructor pattern. The former will reduce (that is, be replaced by the right-hand side of the clause) no matter what the argument is, so long as the patterns above them have been ruled out, while the latter will wait until they see the actual requested constructor prior to reducing. This is true *even if there's only one thing that the pattern could be*. In other words, `f : () -> () ; f () = ()` will reduce when invoked as `f ()` and not when invoked as `f x` where `x : ()`, while `g : () -> () ; g _ = ()` will reduce on either input.

The first pattern of `zipWith` is `zipWith f []      []      = []`. Because of this rule, it requires that both vectors be the `Nil` constructor. However, in your proof state, the second argument that you're passing is a variable rather than a constructor, which blocks reduction. To fix this, I'd pattern-match that argument in the context surrounding your metavariable to reduce it to a constructor.

The second issue in your code is that you're let-binding the equality type, rather than an inhabitant of it. You'd have to let-bind a `Refl` to use it.

**Comment by david-christiansen** [comment]
Aaaaand I see that my reply has been beaten to the punch while I had spaced out from the Firefox tab. Sorry I did something rude! It wasn't the intention!

**Comment by ulidtko** [comment]
Oh... That's the culprit. I gained understanding, your explanations weren't useless David! <sub>especially the examples...</sub>
