### ISSUE TITLE
When defining type classes, some types don't get inferred properly

### ISSUE THREAD

**Issue by turion** [idris-lang/Idris-dev#2249]
I asked this on StackOverflow, where I was encouraged to file it as an issue. I tried to define a verified category type class like this:

    class Cat ob (mor : ob -> ob -> Type) where
      comp  : {a : ob} -> {b : ob} -> {c : ob} -> mor a b -> mor b c -> mor a c
      unit   : (a : ob) -> mor a a
      l     : {a,b : ob} -> {f : mor a b} -> (comp (unit a) f) = f

`ob` is the object type, `mor a b` the type of morphisms from `a` to `b`, `comp` the composition, `unit` the identity morphism and `l` the left unit constraint. I meant to write right unit and associativity constraints as well, but it stopped typechecking already here. It says:

     When elaborating type of constructor of Main.Cat:
     When elaborating an application of comp:
             Can't unify
                     mor a13 b14 (Type of f)
             with
                     mor b14 c (Expected type)

Which doesn't mean anything to me. The type of `f` is clearly `mor a b` and the type of `unit a` is `mor a a`, so I don't see why it's expecting anything else. Strangely enough, it works after I give the implicit arguments explicitly:

    class Cat ob (mor : ob -> ob -> Type) where
      comp  : {a : ob} -> {b : ob} -> {c : ob} -> mor a b -> mor b c -> mor a c
      unit  : (a : ob) -> mor a a
      l     : {a,b : ob} -> {f : mor a b} -> (comp {a=a} {b=a} {c=b} (unit a) f) = f

This typechecks, but I don't see why I'm required to give the extra arguments. I have similar problems in other places with error messages I don't understand at all.

**Comment by edwinb** [comment]
'mor' could be anything, including a function. Idris isn't Haskell,
which means that a thing that gives you a type could just as easily be a
function as a data constructor, and it might not be injective. It would
probably be possible to construct an instance of 'mor' for which the
unification you expect isn't true in Idris' type system.

I will admit to not having looked at this closely yet, but for the
moment I don't think this is incorrect behaviour.

Most likely you'd be better off doing this sort of thing as a record
than as a class (I am careful to say 'class' rather than 'type class'
because classes can be parameterised on things which are not types!)

**Comment by turion** [comment]
Sorry, I don't understand. I'm restricting `mor` on the top of the class to have the type `ob -> ob -> Type`. How can it be anything else then?
I don't understand how to do that as a record either. I mean I want to be able to define my own categories and overload morphism composition and prove Yoneda's lemma for any category and so on, how can I do that with a record?
(Sorry for the stupid questions, but I'm still a beginner in dependently typed programming)

**Comment by edwinb** [comment]
Given that `mor a b = mor c d`, you can't necessarily conclude that `a = c` and `b = d` unless you know `mor` is injective. When you have first class types, this isn't necessarily true, because `mor` could be anything. In Haskell, it can only be a type constructor, but in Idris, it could be any function. Here's an example which might break:

    foo : Nat -> Nat -> Type
    foo x y = Int

Now, `foo 4 5 = foo 1 2` but does that mean `4 = 1` and `5 = 2`? 

Having said all that - I've taken a closer look at this now and recent changes mean that it should be treating `mor` as injective since it's a type class parameter and they now have to be injective. So I think the class definition as you have it probably ought to work. 

I think it would be better to discuss the class/record thing on the mailing list rather than the issue tracker so that more people will be able to see it and contribute (particularly people who might know more about the problem you're actually trying to solve.)

**Comment by turion** [comment]
Oh, I see! If `f` has type `mor a b`, that doesn't actually constrain `a` and `b` sufficiently. Ok, I'll continue on the mailing list, thanks!
