### ISSUE TITLE
Segmentation fault when executing a program but not in REPL

### ISSUE THREAD

**Issue by blemoine** [idris-lang/Idris-dev#2290]
In idris 0.9.17.1,

The following code for generating prime numbers

```
module Main

concat: List a -> Stream a -> Stream a
concat [] ys = ys
concat (x :: xs) ys = x :: (concat xs ys)

generate: (Num a, Ord a) => (start:a) -> (step:a) -> (max:a) -> List a
generate start step max = if (start < max) then start :: generate (start + step) step max else []

mutual
  sieve: Nat -> Stream Int -> Int -> Stream Int
  sieve k (p::ps) x = concat (start) (sieve (k + 1) ps (p * p)) where
    fs: List Int
    fs = take k (tail primes)
    start: List Int
    start = [n | n <- (generate (x + 2) 2 (p * p - 2)), (all (\i => (n `mod` i) /= 0) fs)]

 primes: Stream Int
 primes = 2 :: 3 :: sieve 0 (tail primes) 3

main:IO()
main = do     
  printLn $ take 10 primes
```

In the REPL, if I write ```take 10 primes```, the REPL correctly shows 
```[2, 3, 5, 11, 13, 17, 19, 29, 31, 37] : List Int```

If I try :exec, nothing happens and if I try to compile and execute the program I get Segmentation fault: 11

**Comment by edwinb** [comment]
It's a stack overflow in the C back end, which means that the REPL
version is taking advantage of the underlying Haskell implementation to
make things lazy, but at runtime there's an infinite loop which is
causing problems. It's 'sieve' that is infinite.

This is expected behaviour - obviously segfaulting is not the right way
to report this error, but you can only expect Stream based programs to
terminate if they are total, which 'sieve' isn't.

For more on the difference between compile time and run time evaluation,
see
http://docs.idris-lang.org/en/latest/faq/faq.html#evaluation-at-the-repl-doesn-t-behave-as-i-expect-what-s-going-on

**Comment by ben-schulz** [comment]
Could this be the same sort of behavior referenced in Issue #1515?
