### ISSUE TITLE
Problem with "index" function in the tutorial

### ISSUE THREAD

**Issue by thurn** [idris-lang/Idris-dev#2392]
Hey, I've just started going through the tutorial, and I've run into a possible bug. We define this function:

```
index : Fin n -> Vect n a -> a
index FZ     (x :: xs) = x
index (FS k) (x :: xs) = index k xs
```

Unless I misunderstand something, can't this function *only* be used to look up the last element in a vector? If I change the type signature to `index : Fin m -> Vect n a -> a` it works more like how I'd expect.

In general, it would be great to include an example of how to invoke the `index` function at this point in the tutorial. It took me a long time to figure out how to call it, since you can't just do `Prims.index FZ ("Foo" :: ("Bar" :: Nil))` or something in the REPL but need to always provide a type signature for FZ.

**Comment by david-christiansen** [comment]
Thanks for the feedback! It's really valuable for us to get insight into how new users experience Idris.

This function can be used to look up any element of the vector. For some natural number `n`, the type `Fin n` contains precisely `n` elements - or in other words, one for each position in a `Vect n a`. If the `Fin n` happened to be a particular one of those elements called `FZ`, then we take the first element of the vector, and if not , we call the function recursively. This works because `FS` has the type `Fin k -> Fin (S k)`, so its argument is a `Fin` that matches the length of the tail of the vector.

If it used `Fin m`, then the bound on the index would have no relationship to the length of the vector, so we'd need a type like `index : Fin m -> Vect n a -> Maybe a`, at which point we might as well just use `Nat` and `List`.

With regards to the REPL, it should work to use `index` directly with the constructors of `Fin` and `Vect`. Here's what I just typed in:
```
λΠ> Vect.index FZ ["rats", "are", "wonderful", "animals"]
"rats" : String
λΠ> Vect.index (FS FZ) ["rats", "are", "wonderful", "animals"]
"are" : String
λΠ> Vect.index (FS (FS FZ)) ["rats", "are", "wonderful", "animals"]
"wonderful" : String
```

What sorts of error messages were you getting? How did you end up calling it? That will help me diagnose what needs to be in the tutorial.

**Comment by thurn** [comment]
Ahh... I was thinking that each "Fin" type contained exactly 1 value. Didn't really wrap my head around the fact that a value like "FZ" has an infinite number of different types.

The second problem was caused by the first one, actually, changing the type signature to have `Fin m` makes it not work in the REPL.

That said, I do think it would be good to encourage folks to run the function themselves and see it in action with examples like the ones you provided, I think it makes what's going on a lot clearer.
