### ISSUE TITLE
Idris analog of coq_makefile?

### ISSUE THREAD

**Issue by kevinsullivan** [idris-lang/Idris-dev#2393]
Hi, I'd like to generate a makefile from the .idr files in a directory, or directory hierarchy, where the makefile will then build HTML or Latex for me. I see how to generate latex/html from a function using the REPL, but not how to do what I want to do. Any pointers? Thanks!

**Comment by david-christiansen** [comment]
Hello Kevin,

Hi, I'd like to generate a makefile from the .idr files in a directory, or
> directory hierarchy, where the makefile will then build HTML or Latex for
> me. I see how to generate latex/html from a function using the REPL, but
> not how to do what I want to do. Any pointers? Thanks!
>
We don't presently have a means of generating HTML or LaTeX from Idris
source files. I think that it would not be too difficult to implement using
the same mechanism that highlights source code in Emacs (and soon Atom),
but it would require a bit of programming time that I don't have at the
moment.

I could, however, get it to dump the highlighted regions fairly quickly -
something like "from line 38 col 8 to line 38 col 11 is the name
Prelude.Nat.Nat which is a Type with this docstring". Then you could write
the code to map these regions to the HTML or LaTeX as a separate utility.

/David

**Comment by jfdm** [comment]
I might be mistaken here, but is what was described the an analogue for `coqdoc`, rather than `coq_make`. 

One thing that might be helpful is that of the [Idris packaging system.](http://idris.readthedocs.org/en/latest/tutorial/packages.html) This will allow you to not only manage the build of a Idris package/executable but allow for API documentation to be generated for your package. Examples of generated docs are available on our [documentation summary page.](http://www.idris-lang.org/documentation/) A specific example being the API docs for the [preldue](http://www.idris-lang.org/docs/current/prelude_doc/) and [base](http://www.idris-lang.org/docs/current/base_doc/).

At this moment in time the API documentation does not spit out LaTeX.

**Comment by david-christiansen** [comment]
With the change in #2395, you can set the idris options in the .ipkg file so that it will dump highlighting information. It's then up to you to write some code to use it to decorate your source files afterwards.
