### ISSUE TITLE
Should :apropos look in types?

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris-dev#2400]
It seems to me that this might give too many results a lot of the time. For example, if you try `:apropos length` not only do you find `length`, you also find all of the functions which use it for properties of other functions, which I don't think is what was originally intended.

On the other hand, sometimes you do want this behaviour, for example if you know the name of a function and want to find what properties are proved about it.

I think the most likely use, and the one which would make most sense to beginners in particular, would be to not look in types, and to have an alternative version (say `:properties`) for searching for properties of things.

Any thoughts? Anyone using this in practice? Unless there's a strong argument against, I will change the default behaviour to ignore types and add an alternative which does.

**Comment by david-christiansen** [comment]
I did originally intend `:apropos` to look in types as well as definition names and documentation. The idea was that it's the one-stop shop to find everything related to a seach term, and that it should cast a wide net for people who are exploring the system and the libraries. `:apropos length` isn't really for searching for the function `length`, it's more for finding things that are length-related in general to get an overview of how it works. That's  why it accepts an arbitrary number of search terms: so that it can later be narrowed down if it returns too many things.

Note that there are better UIs than the "type command, press up, add stuff, press up, add stuff", like `helm-idris` in Emacs, that update the result set dynamically as the query is typed. This could perhaps also be implemented at the command line, though that might require making a bigger deal out of the curses bindings.

**Comment by edwinb** [comment]
In practice, I'm not sure a search which returns lots of results is always the right thing, though. And if it does, we should probably try harder to return the most relevant results first. For example, at the minute, `:apropos length` returns `Sigma` first, which is a valid thing to do when it's looking in the documentation, but probably not what the user is most likely to be looking for.

Anyway, if `:apropos` is meant to cast a wide net then it's clearly not what I'm looking for here, so I'll close this. Instead, maybe a tweak to `:search` is what I want, where `:search [name]` would find definitions which include the name as a substring, possibly case insensitively. Currently it's not especially helpful if you give it just a name because it treats it as a type variable and returns a lot of irrelevant things...

Essentially what I'm looking for here is ways to help new users find their way around the prelude by exploration.

**Comment by david-christiansen** [comment]
I agree that this would be a useful searching feature, and that `:apropos` should order results so that name matches come first.

Having `:search` work the way you describe would match the way Hoogle works, so that's a point in its favor.
