### ISSUE TITLE
Idris not installable with stack

### ISSUE THREAD

**Issue by pharpend** [idris-lang/Idris-dev#2416]
Running `stack install idris` gives me this:

```
[~] % stack install idris                                                                           pete@locust
Using resolver: nightly-2015-07-01 from global config file: /home/pete/.stack/global/stack.yaml
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      blaze-html: needed (>=0.6.1.3 && <0.8), but 0.8.0.2 found
      blaze-markup: needed (>=0.5.2.1 && <0.6.3.0), but 0.7.0.2 found
      utf8-string: needed (<0.4), but 1 found
    needed for package: idris-0.9.18.1
stack install idris  1.60s user 1.66s system 226% cpu 1.436 total
[~] %                                                                                               pete@locust
```

Stack is quickly gaining popularity, and will very likely eclipse cabal-install in the near future. Thus, I think it's quite important that Idris is installable with Stack.

Stack also has the advantage of using Stackage by default, so this would likely solve the dependency hell problems.

**Comment by jfdm** [comment]
This is a duplicate of #2135

**Comment by pharpend** [comment]
@jfdm Stack didn't exist back then. Also, that issue is specifically about LTS Haskell. I'm advocating for *any* of the Stackage package selections.

**Comment by jfdm** [comment]
Although you are correct in that issue #2135 was created pre-stack and pre-stackage-cli days, your issue is still a duplicate of #2135 just with a different package selection as its target and means of obtaining said selection.  Of note #2135 did mention how best to get to LTS Haskell through use of stackage-cli, and with stack now available it appears that stack is the preferred means of accessing LTS Haskell and its variations.

Regardless of which package set is chosen, the knock-on effects of moving over to a new package set and other infrastructure tooling must also be considered.

**Comment by david-christiansen** [comment]
@pharpend I'm currently not in a position to mess with my Idris install, as I'm at a conference and will be doing a demo, or I could try this myself. Have you tried bumping the upper bounds and building Idris? If the new versions of these libraries are sufficiently compatible, then it should work just fine. We have aggressively upper-bounded to avoid being broken by upstream changes, but bumping them in the .cabal file is fairly easy.

**Comment by pharpend** [comment]
@david-christiansen I haven't tried that. I'll try it today, let y'all know how it goes.

**Comment by pharpend** [comment]
Since this is apparently a duplicate, I'm closing it.

**Comment by pharpend** [comment]
So, for what it's worth, I got master to build on my machine with Stackage nightly.

**Comment by david-christiansen** [comment]
Thanks @pharpend!
