### ISSUE TITLE
Can't resolve type class Lala t

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2505]
The program
```
> class Lala t where
>   A : Type  
>   plus : A -> A -> A 
>   plusAssociative : {a, b, c : A} -> a `plus` (b `plus` c) = (a `plus` b) `plus` c
```
does not type check:
```
- + Errors (1)
 `-- typeClasses9.lidr line 1 col 6:
     When checking type of plusAssociative:
     Can't resolve type class Lala t
```
Is this the expected behavior? What am I doing wrong here?

**Comment by portnov** [comment]
Hello.
Any updates on this?

**Comment by Newlifer** [comment]
I second this

**Comment by nicolabotta** [comment]
I have no idea what is going on here but, generally speaking, there still appear to be massive problem with Idris type classes. Even Prelude.Classes.Num does not work, see #2830. 

I have been trying to use Idris type classes many times and every time I had to give up in the end, see, for instance, #2053. This can be very frustrating, expecially when problems show up at only at the end and in applications as in #2830. And without type classes one can easily end up with something like lines 58-68 of 

https://github.com/nicolabotta/SeqDecProbs/blob/master/frameworks/14-/SeqDecProbMonadicTheoryRVExample2.lidr

which is probably not how one would expect to express the idea that, if M = Identity, then M is a monad. 

On the other hand, it is perhaps not a bad idea to think about how notions like monoids, semigroups, lalas, etc. could be expressed in Idris without using type classes: attempts at using type classes for expressing these notions seem to have failed or to have ended up with a lot of comments and very little code, see contrib/Control/Algebra.idr. 

Perhaps this is an indication that Idris type classes, at least with their current limitations, are not a suitable approach for representing hierarchies of notions or abstract data types.

**Comment by nicolabotta** [comment]
With 0.11-git:4a4548e, the program
```
> %auto_implicits off
 
> interface Lala t where
>   A : Type  
>   plus : A -> A -> A 
>   plusAssociative : {a, b, c : A} -> a `plus` (b `plus` c) = (a `plus` b) `plus` c
```
still fails to type check but the error message is now
```- + Errors (1)
 `-- 2505_type_classes.lidr line 3 col 10:
     When checking type of plusAssociative:
     Can't find implementation for Lala t
     
     Possible cause:
             2505_type_classes.lidr:6:60-61:When checking argument y to type constructor =:
                     Type mismatch between
                             A t1 (__class2) (Type of c)
                     and
                             A t _ (Expected type)

```

**Comment by edwinb** [comment]
The combination of associated types and dependency in interfaces turns out to be pretty tricky to get right. I'll take a look.

(The "massive problems" you talk about arise when pushing interfaces way beyond what e.g. Haskell like type classes can do, which is what they were originally designed for. Sorry we didn't get it right earlier but we'll get there in the end. "Even Num doesn't work" turns out not to be correct - it's doing the right thing, given the possibility of named implementations.)

**Comment by edwinb** [comment]
Hang on... `t` appears in the class declaration but not anywhere in the body. Is this really what you intended?

I've been meaning to implement that check (i.e. that each method needs either a parameter or to appear in the type of another method) for a while, because otherwise all kinds of things can go wrong with unhelpful error messages. I'd better get around to implementing it.

**Comment by nicolabotta** [comment]
Thanks Edwin! The original code works perfectly now.
> Hang on... t appears in the class declaration but not anywhere in the body. Is this really what you intended?

Yes! I agree that the example is not very canonical. I came to it while trying to do things like
```
> interface Mono (n : Nat) where
>   t : Type  
>   op : t -> t -> t 

> namespace NatPlusMono
>   implementation Mono Z where
>     t = Nat
>     op = plus

> namespace NatMultMono
>   implementation Mono (S Z) where
>     t = Nat
>     op = mult
```
which perhaps was a bad idea in itself!
