### ISSUE TITLE
Transparent FFI from Haskell to Idris

### ISSUE THREAD

**Issue by suhr** [idris-lang/Idris-dev#2509]
They're close languages, so a lot of glue code can be avoided.

**Comment by david-christiansen** [comment]
This would be nice to have, but I disagree that they are close languages. Please consider:

 1. Haskell code typically assumes laziness, while Idris code assumes strictness. It's possible to express the other in each, but it's far from convenient and requires glue code. OCaml is much closer in this respect. In particular, idiomatic Haskell relies on combinator libraries and higher-order functions, and dumping strict Idris functions in there will likely not be as easy as expected.
 2. The type class system is quite different, even if similar on the surface. In particular, Idris makes no attempt at uniqueness of instances, which a great deal of Haskell code relies on for correctness.
 3. The type systems aren't really compatible. Haskell has things like impredicative polymorphism, while Idris has things like Vect. Should the singleton trick be used at the border?
 4. In order to work right, Idris needs pervasive erasure. How do we track usage of fields across the language boundary?

I'm not saying this can't be done - it probably can. But in my estimation it's a whole-PhD research project, not something we can hack together as the result of a feature request. So I'm going to go ahead and close this.
