### ISSUE TITLE
Regression when cleaning a package on windows

### ISSUE THREAD

**Issue by archaeron** [idris-lang/Idris-dev#2568]
The newest version (0.9.19) fails when cleaning a package on windows.

With a line like this in the `ipkg` file:
```
executable = executable
```
it tries to delete the file `executable` without attaching the `.exe` to the file path.

This worked in the last version.

**Comment by melted** [comment]
Ah, that was removed because  it attached a spurious .exe when building the JavaScript version. 

Guess we'll have to add some logic to the cleaning.  i wonder if it ever worked for JavaScript.

----- Ursprungligt meddelande -----
Från: "archaeron" <notifications@github.com>
Skickat: ‎2015-‎09-‎01 10:34
Till: "idris-lang/Idris-dev" <Idris-dev@noreply.github.com>
Ämne: [Idris-dev] Regression when cleaning a package on windows (#2568)

The newest version (0.9.19) fails when cleaning a package on windows.
With a line like this in the ipkg file:
executable = executable
it tries to delete the file executable without attaching the .exe to the file path.
This worked in the last version.

**Comment by archaeron** [comment]
Couldn't it try to remove the `.exe` and if it doesn't find one go on?
I think it stops cleaning up at the moment if it can't find a file.
