### ISSUE TITLE
Compiler is (probably) stuck

### ISSUE THREAD

**Issue by mukeshtiwari** [idris-lang/Idris-dev#2580]
I am declaring a datatype which takes stream but creating the instance of datatype using list. I tried to compile this code but it's taking too long time and I think it's not terminating.

```idris
module Main

data Tape : Type where
  RTape : (xs : Stream Int) -> (r : Int) -> (ys : Stream Int) -> Tape

emptyTape : Tape
emptyTape = RTape ([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]) 0
  ([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])


main : IO ()
main = do
  str <- fread stdin
  fwrite stdout str

hello:Idris mukeshtiwari$ idris
     ____    __     _                                          
    /  _/___/ /____(_)____                                     
    / // __  / ___/ / ___/     Version 0.9.19
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/      
 /___/\__,_/_/  /_/____/       Type :? for help               

Idris is free software with ABSOLUTELY NO WARRANTY.            
For details type :warranty.

Bye bye
hello:Idris mukeshtiwari$ time idris -o Bug Bug.idr 
^C

real	2m26.060s
user	2m24.003s
sys	0m1.523s
```

**Comment by edwinb** [comment]
It'll terminate if you wait long enough and have enough memory... not
that that's very useful in practice.

This turns out to be to do with ambiguous constructor names and type
based disambiguation, and its interaction with coinductive things. It's
a bit of a rabbit hole so I don't know how long it'll take to fix, but
once I've got to the bottom of it things will be much quicker.

In the meantime, the problem here is that the Stream you've given is
finite, and only infinite Streams are allowed.

**Comment by edwinb** [comment]
This now fails quickly, as it should.

**Comment by mukeshtiwari** [comment]
Thank you.
