### ISSUE TITLE
Broken build on Hackage -- INTERNAL ERROR??

### ISSUE THREAD

**Issue by kevinsullivan** [idris-lang/Idris-dev#2653]
Hi All,
A student and I just did a clean install of Idris from Hackage. When we try to compile a very simple bool module we get: INTERNAL ERROR: Can't find namebool. This is probably a bug ... consider reporting. The idris --version command returns 0.9.19.1. It's conceivable that it's something on the student's PC, but it's not clear what it could be. I know that it's hard to imagine that 0.9.19.1 would make it to Hackage with such an error. Any ideas?

The file looks like this:
=====

module bool

data bool = true | false

not: bool -> bool
not true = false
not false = true

========

**Comment by david-christiansen** [comment]
The quantification rules were tweaked, making it be the case that any name that _could_ be an implicit parameter _will_ be an implicit parameter.

In the past, if I wrote:

```
a : Type
a = Nat

id : a -> a
id x = x
```
then the `a` would refer to the global definition and `id` would work only at `Nat`, but if I had
```
a : Type
a = Nat

id : b -> b
id x = x
```
then I would get a polymorphic definition and `id` would work at any type. To avoid the confusion around this, lowercase names in types are now *always* implicit arguments, just like in Haskell. This is not a problem for Idris code that follows ordinary Idris conventions, where type constructor and constructor names are capitalized.

Try this instead, if you want to avoid capturing the names:
```
module MyBool

data Bool' = True' | False'

not : Bool' -> Bool'
not True' = False'
not False' = True'
```

Alternatively, if you really must keep everything lowercase, you can qualify your names:
```
module bool

data bool = true | false

not : bool.bool -> bool.bool
not true = false
not false = true
```
I agree that the error message here is decidedly non-helpful.

You can diagnose this problem by watching the colors in Emacs: the lowercase `bool` references are purple instead of blue until they get qualified, and then they become blue.

(cc @edwinb)

**Comment by kevinsullivan** [comment]
Thanks for this explanation, David. I understand what happened. I validated 0.9.19 as an update for my students (so they could use Atom). A few waited too long and got 0.9.19.1. That version interacted with our flouting of Idris capitalization conventions so that our pedagogical implementations of bool, nat, etc would not conflict with Prelude. A classic TOCTOU failure. At the same time, the less than helpful error message made it look like we were seeing a compiler bug. In the future, we'll try to find a way to defeat implicit import of Prelude, and just have the students write convention-compliant code for the "built-in" types that they're learning how to program. I'll leave this issue open as a reminder to fix the error msg. Thanks, again. --KS

**Comment by david-christiansen** [comment]
There is a command-line option to skip the Prelude - that might be easier than trying to invent all kinds of new names!

**Comment by kevinsullivan** [comment]
Agreed, for sure. Is there a way to cause Idris mode in emacs to accept that option? I read another issue / thread on this question, but it didn't seem to come to a conclusion.

**Comment by david-christiansen** [comment]
You can use standard Emacs features to control `idris-mode`, including file variables. Emacs lets you set Elisp variables for a particular file by sticking a special comment at the bottom, then re-opening the file (with `M-x revert-buffer` or by just closing and opening again). Because all `idris-mode` settings are elisp variables, you can set them up for just one file.

Now that my Emacs lecture is done, here's the incantation:
```
-- Local Variables:
-- idris-interpreter-flags: ("--noprelude")
-- End:
```

Stick it at the end of your file, and from then on it won't load the prelude.  You can also put that option in a .ipkg file to have it apply to a whole directory full of Idris files.

**Comment by kevinsullivan** [comment]
That's great. Thank you. The issue is resolved for me.

**Comment by david-christiansen** [comment]
Great! It still shouldn't say "Internal error" here, so please don't close it.

**Comment by david-christiansen** [comment]
Also, if you want a list of all the customizable settings for `idris-mode`, you can do `M-x customize-mode` to get a list of the variables intended for user settings. Browsing that might be useful.

**Comment by kevinsullivan** [comment]
Thanks. Leaving open.

**Comment by edwinb** [comment]
I'll take a look at making this message better. Actually I wonder if we should require that data type names can't begin with a lower case letter...

**Comment by david-christiansen** [comment]
I think it at least should have a warning by default.

**Comment by edwinb** [comment]
I have added this warning, though it does mean I'm finding all the bits in the library where we don't follow the convention! Next up, elaborator reflection, changing the prim__ prefix to Prim__ ...

**Comment by david-christiansen** [comment]
Thanks @edwinb :-)
