### ISSUE TITLE
HVect - INTERNAL ERROR: cantSolveGoal

### ISSUE THREAD

**Issue by gonzaw** [idris-lang/Idris-dev#2656]
Hi, I have the following code:

    import Data.HVect
    import Data.Vect
    import Data.Fin

    %default total

    hVectEx1 : HVect [String, List Nat, Nat, (Nat, Nat)]
    hVectEx1 = ["Hello",[1,2,3],42,(0,10)]

When loading it in the REPL, and doing `put 3 hVectEx1` I get the following message:

    INTERNAL ERROR: cantSolveGoal
    This is probably a bug, or a missing error message.

Not only that, but when I try `put (the Nat 3) hVectEx1` I get this message:

    (input):1:10:When checking argument a to function Prelude.Basics.the:
            Type mismatch between
                    Type (Type of Nat)
            and
                    Elem a ts (Expected type)

I thought the automatic tactic would be able to find a proof that `Nat` belongs to this `HVect` instance.

Doing `put {t=Nat} 3 hVectEx1` works correctly, but I found the above errors weird, considering I thought the type-checker could infer the implicit types (and proofs) correctly.

**Idris Version: 0.9.19**

**Comment by edwinb** [comment]
This is to do with the way the 'auto' tactic works and when it decides to try solving a goal. Things have changed since 'put' was written, so I'll add a test to catch this.

In short: 'auto' should be considered a way of adding side conditions as properties of previous arguments, since elaboration works left to right. Here, proof search is searching too early, thinking it has enough information.

The difficulty with 'auto' is that if proof search fires too early, it risks solving metavariables by accident (here, it's decided it's looking for a String because 'Here' worked when it started the search too early). But if it fires too late, and the proof itself is required for the rest of elaboration, you'll get some surprising errors.

For now, I've changed the type of 'put' so that the auto implicit is after the argument it is referring to. One day I may come up with a better/more precise rule for when proof search should start searching. While I don't mind a certain amount of magic with 'auto', in that it just means "find anything that works" there is still a bit too much voodoo involved.
