### ISSUE TITLE
Type checking consumes too much memory or doesn't terminate

### ISSUE THREAD

**Issue by NightRa** [idris-lang/Idris-dev#2657]
Reproduction: 

``` idris
module Main

import Data.Vect

ix : (Vect 9 Bool) -> Bool
ix [True , _ , _    , _, True , _ , _    , _, True ] = True
ix [_    , _ , True , _, True , _ , True , _, _    ] = True
ix [False, _ , _    , _, False, _ , _    , _, False] = True
ix [_    , _ , False, _, False, _ , False, _, _    ] = True
ix _ = False
```

Type checking _seems_ not to terminate here, it consumes 12 GB of memory and then I kill it.
Maybe it just consumes too much memory but would terminate at some point.
It does terminate with `List Bool -> Bool` and without any of the 4 pattern matches.
This does typecheck however (reordered lines):

``` idris
ix : (Vect 9 Bool) -> Bool
ix [True , _ , _    , _, True , _ , _    , _, True ] = True
ix [False, _ , _    , _, False, _ , _    , _, False] = True
ix [_    , _ , True , _, True , _ , True , _, _    ] = True
ix [_    , _ , False, _, False, _ , False, _, _    ] = True
ix _ = False
```

**Comment by edwinb** [comment]
My first guess was coverage checking (sometimes it's worth trying with --nocoverage to see if the same thing happens), but that appears not to be the case... I'm sure it'll terminate eventually, given enough memory, but clearly that's not what we want...

**Comment by edwinb** [comment]
There turns out to be two problems here. One I can do something about fairly easily, so I will, the other is more tricky. The first is that there's a lot of ambiguity to resolve - resolving it is easy enough (it's obviously a Vect after all) but there are some bits of code that weren't very clever about ignoring the ambiguity when they didn't need to care about it.

The second, which is more tricky, is that the case tree generated for the first version of your function is big and complex, whereas the second with the reordered cases is more reasonable. There's quite a lot of hidden stuff going on with Vects (you need case analysis on the length at compile time, for example, when then needs erasure analysis for the runtime version) so big case trees can hurt. We'll have to try to do better for functions such as this, but it's always going to be a bit tricky with larger values of dependent types, especially when coverage checking gets involved.

The same function is okay with Lists (after I've done the first fix) because the case tree building and erasure doesn't have to worry about what to do with the lengths of the lists.

**Comment by NightRa** [comment]
I'm saying this without knowing much about the used typechecking algorithm, but can't it infer the sizes of each subexpression of the vect directly? 9,8,7,...,1,0? Is some sort of a deep search algorithm applied in this case?

a : b : [] => infer [] of size 0, b : [] of size 1, a : b : [] of size 2

**Comment by edwinb** [comment]
They *are* inferred, that's not the problem. It's the huge case tree that gets generated that really hurts in the end.

**Comment by ahmadsalim** [comment]
Still an issue in `0.11`

**Comment by alercah** [comment]
Encountered this example with a pair of Fins that, even with `--nocoverage`, causes the compiler to run out of memory and crash (on a machine with about 30GB of free RAM):

```
import Data.Fin

data Square : Type where
  MkSquare : Fin 8 -> Fin 8 -> Square

syntax "f0" = FZ
syntax "f1" = FS FZ
syntax "f2" = FS $ FS FZ
syntax "f3" = FS $ FS $ FS FZ
syntax "f4" = FS $ FS $ FS $ FS FZ
syntax "f5" = FS $ FS $ FS $ FS $ FS FZ
syntax "f6" = FS $ FS $ FS $ FS $ FS $ FS FZ
syntax "f7" = FS $ FS $ FS $ FS $ FS $ FS $ FS FZ
syntax "x8" {p} = FS $ FS $ FS $ FS $ FS $ FS $ FS $ FS p

pieceAt : (square : Square) -> ()
pieceAt (MkSquare (x8 p) _) = absurd p
pieceAt (MkSquare _ (x8 p)) = absurd p
pieceAt (MkSquare f0 f0) = ()
pieceAt (MkSquare f1 f0) = ()
pieceAt (MkSquare f2 f0) = ()
pieceAt (MkSquare f3 f0) = ()
pieceAt (MkSquare f4 f0) = ()
pieceAt (MkSquare f5 f0) = ()
pieceAt (MkSquare f6 f0) = ()
pieceAt (MkSquare f7 f0) = ()
pieceAt (MkSquare f0 f7) = ()
pieceAt (MkSquare f1 f7) = ()
pieceAt (MkSquare f2 f7) = ()
pieceAt (MkSquare f3 f7) = ()
pieceAt (MkSquare f4 f7) = ()
pieceAt (MkSquare f5 f7) = ()
pieceAt (MkSquare f6 f7) = ()
pieceAt (MkSquare f7 f7) = ()
pieceAt (MkSquare _ f1) = ()
pieceAt (MkSquare _ f2) = ()
pieceAt (MkSquare _ f3) = ()
pieceAt (MkSquare _ f4) = ()
pieceAt (MkSquare _ f5) = ()
pieceAt (MkSquare _ f6) = ()
```
