### ISSUE TITLE
Proposal for conditional imports

### ISSUE THREAD

**Issue by melted** [idris-lang/Idris-dev#2662]
Say I want to make an Idris library that needs to interface with the outside world, let's say for drawing. But I want it to work with several different backends using whatever is suitable, like SDL for C or Canvas for javascript. How to do this? Without this functionality it is hard to build backend-portable libraries that abstracts out system interfaces.

Elaboration reflection is no help here, even if we added a primitive for manipulating the imports, as it is run before the backend is selected and the same ibc file can be used to produce code for different backends.

I propose that we add an optional parameter for backend selection to the import so that the following code becomes possible:
```idris
module Drawing

import Drawing.SDL for c
import Drawing.Canvas for javascript
```

The syntax could be:
```
import <module> [as <alias>] [for <backend>]
```
An alternative could be to make it a directive preceding the import.

An extension could be to use it for conditional import of platform-dependent libs, but that would be possible with elaborator reflection if that could manipulate imports, so maybe it isn't desirable.

Any thoughts? @edwinb? @david-christiansen?

I'm willing to implement it, just thought I would ask for feedback before starting.

**Comment by david-christiansen** [comment]
This seems like one reasonable way to do backend-conditional things, but what about the cases where the different backends need to parametrize more than just module imports? Also, it seems to me that each of those modules should somehow have the same signatures, but differing implementations.

The IO type currently accepts an FFI as an argument. Is there a reason not to use type classes over the FFI to solve this parametrization instead? It seems to provide a bit less of a cpp-like experience, in any case.

**Comment by jfdm** [comment]
I agree with @david-christiansen on this. The `IO` monad as constructed in Idris provides a nice example of achieving the *Factory Design Pattern* within Idris. Facilitating the construction of generic code that works agnostic to a chosen representation, but also provide concrete instantiations for its use.

**Comment by edwinb** [comment]
I think it ought to be possible to do this in the language itself, rather than adding an extra feature for import. It will need some thought too though. For example, you could write an effect with handlers for each FFI it needs to deal with, or you could have a type class for the interface with instances for each FFI. Then, at the top level (so probably in your Main module) you'd pick the right interface, or run the effect in the right context.

The problem with backend specific imports is that it's not the backends that are behaving differently here, but the FFIs. It's entirely reasonable for a backend to implement multiple FFIs, or none at all. e.g. you can call Haskell from C, so a C backend could be made to know how to call that.

**Comment by melted** [comment]
Ok, I close this as parameterization over FFI seems to be preferred.

Ideally, of course, what I would want is first class modules. But that is a rather larger thing to pull off.
