### ISSUE TITLE
Invalid syntax accepted

### ISSUE THREAD

**Issue by mrmonday** [idris-lang/Idris-dev#2666]
As far as I can tell, the following code uses invalid syntax:

```idris
foo : Int -> Bool
foo 1 | 2 | 3 = True
foo _ = False
```

But compiles successfully.

**Comment by edwinb** [comment]
The syntax is valid (it's the syntax for a with block clause, and clauses are parsed independently) but the elaborator should reject it because there's no expected patterns from a with block. As it is, it's just silently rejecting the additional arguments.

This might be a good one for someone to look at who is interested in learning a bit about how the elaborator works. We should probably take a closer look reasonably soon, though, since a similar syntax is the kind of thing people coming from Haskell expect to work (as guards).

**Comment by ahmadsalim** [comment]
I know get:

```idris
Type checking ./test.idr
test.idr:2:5:When checking left hand side of foo:
unexpected patterns outside of "with" block
```
which is a suitable error.
