### ISSUE TITLE
The name of new package `Pruviloj` may be confusing.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2667]
Recently, the package `pruviloj` has been added to `libs/` directory. This package presents a library of tactics that work with Idris's elaborator reflections. Kudos to @david-christiansen for the creation of such a library, however, I think the name may not be suitable for distribution in `libs/`. While we are free to name our projects as we see fit, I think for distribution with Idris `libs/` extra care should be taken to present more descriptive and accessible names rather than unique names. This is to avoid confusion surrounding what the package provides and its use by developers. 

The Esperanto word `pruviloj` while distinctive is also too distinctive w.r.t to spelling, and also offers little connotation over the intended use of the package.  I am open to being persuaded otherwise on this issue but am nonetheless compelled to voice my concerns prior to the next Hackage release of Idris. 

**Note** earlier comments made by myself were made in PR #2649.

**Comment by david-christiansen** [comment]
Here's some reasons for using a unique name:
 1. It's really not intended to be the "default" or "official" way to use elaborator reflection. That said, it's collected from things that I really have found useful and that make sense to have available both as examples and for use. A unique name helps communicate this, while also being Googleable.
 2. The README states exactly what it's for (thanks for prompting me to write that). 
 3. Plenty of libraries have had unique names in the past without it being a big deal. The most-downloaded libraries from Hackage right now are `text` (generic), `Cabal` (unique), `aeson` (unique), `warp` (unique), `vector` (generic), `lens` (debatable), `attoparsec` (unique), `yaml` (generic), `pandoc` (unique), and `conduit` (unique). So it doesn't seem to prevent people from figuring out what it's for.

Here's some mitigating factors for the downsides:
 1. It's not something that a new user has any business working with. By its very nature, it's for advanced users, and hopefully most users will never even need it, because resorting to metaprogramming means the language has been missing something important.
 2. There's tons of docstrings
 3. If someone does stumble over it, they can look at the README and they'll know what it is immediately.

It should be in `libs` because it is being used to implement features of general interest to Idris users, such as type class deriving.

**Comment by jfdm** [comment]
I am not doubting the need for a exemplar library within `libs/` that illustrates how elaborator reflection can be used, and also provides something useful. I never doubted that, and I do not see why that should be made an issue in this discussion. Raising it paints my points in a more negative light than they actually are. 

I still think the choice of name is important, especially if it is to be an exemplar and something that will be used. Why not use a name such as: `tactics` or `prooftools` or `proofbox`? 

> make sense to have available both as examples and for use. A unique name helps communicate this, 

I think the README communicates this rather well.

> while also being Googleable.

I actually do not know what you mean by 'googleable' in this context. Do you mean that if you search 'pruvolij' you get taken to the package immediately, or if you search for `tactics + idris` (or some other term) the name `pruvolij` stands out in the results. 

> Plenty of libraries have had unique names in the past without it being a big deal. 

Thinking about it, the main gripe i have is the esoteric nature of the name and its affect of usability. The unique names you have given as examples are simple, and indicative of application area, and to not sound contrived don't really need IPA information for pronunciation.

> Here's some mitigating factors for the downsides:

Sorry, I do not understand what 'downsides' you are referring to.

I've said my piece now, and actually I do not want this conversation to drag on unnecessarily.
