### ISSUE TITLE
Can't disambiguate name: expected behavior or bug?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2701]
The program
```
> namespace N2
 
>   Nat2 : Type
>   Nat2 = (Nat,Nat)

>   toNat : Nat2 -> Nat
>   toNat (i,j) = i

> namespace N3
 
>   Nat3 : Type
>   Nat3 = (Nat,Nat,Nat)

>   toNat : Nat3 -> Nat
>   toNat (i,j,k) = i

> lala : Nat2 -> Nat3 -> Nat
> lala x y = toNat x + toNat y
```
fails to type check with
```
- + Errors (1)
 `-- name_disambiguation.lidr line 18 col 5:
     When checking right hand side of lala:
     Can't disambiguate name: Main.N2.toNat, Main.N3.toNat, Prelude.toNat
```
Is this the expected behavior? Is it a bug? I would actually expect the program to type check: it seems to me that, both in the case of `toNat x` and in the case of `toNat y`, the function to be applied can be fully determined. Thanks, Nicola

**Comment by jfdm** [comment]
I am going to argue for expected behaviour, as a result of `Prelude.toNat`. Although, I might be wrong. 

The function `Prelude.toNat` has the type signature `toNat : Enum a => a -> Nat`. This might cause confusion when working with the type synonyms for the tuples when it tries to work out what `a` should be. If you `%hide Prelude.toNat` the file will type check as expected.

Whether this is a bug I do not know.

**Comment by nicolabotta** [comment]
The problem is that, even if one comments out the definitions of `Nat2`, `Nat3` and `toNat` that is
```
> namespace N2
 
>   Nat2 : Type
>   -- Nat2 = (Nat,Nat)

>   toNat : Nat2 -> Nat
>   -- toNat (i,j) = i

> namespace N3
 
>   Nat3 : Type
>   -- Nat3 = (Nat,Nat,Nat)

>   toNat : Nat3 -> Nat
>   -- toNat (i,j,k) = i

> lala : Nat2 -> Nat3 -> Nat
> lala x y = toNat x + toNat y
```
the error is still there. This suggests that it is an Idris bug. At the very least I do not see why the type checker should get confused with `toNat : Enum a => a -> Nat`: there is no obvious reason why `Nat2` and `Nat3` should be instances of `Enum`!

**Comment by Melvar** [comment]
I’m pretty sure searching for an appropriate instance would only start happening after one was picked, i.e. class constraints don’t affect disambiguation at all.

**Comment by Melvar** [comment]
(Specifically, I believe @edwinb said so in IRC, but I can’t find it in my logs anymore.)

**Comment by edwinb** [comment]
As @jfdm says, the disambiguation is unwilling to rule out Prelude.toNat (commenting out definitions has nothing to do with it, the types are still there). If class resolution fails, the elaborator hangs onto it in case some more information turns up later which will help. On the other hand, in this case, it's clear that the failure is never going to be resolved, so it should really fail instantly.

This is sort of expected behaviour, in that I knew disambiguation behaved like this, but I also think we can do better so I do consider this a bug...
