### ISSUE TITLE
Proof search fails on simple example

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#2703]
In current master, with the following program, interactive proof search fails to solve `?DecEq_rhs_1`. It seems to me that it should be able to. Am I missing something?  Wrapping a `Yes` constructor around the hole makes proof search succeed.

```
data Tree a = Leaf | Branch (Tree a) a (Tree a)

injBranch : Branch l x r = Branch l' x' r' -> (l = l', x = x', r = r')
injBranch Refl = (Refl, Refl, Refl)

instance DecEq a => DecEq (Tree a) where
  decEq Leaf Leaf = ?DecEq_rhs_1
  decEq Leaf (Branch l x r) = ?DecEq_rhs_4
  decEq (Branch l x r) Leaf = ?DecEq_rhs_2
  decEq (Branch l x r) (Branch l' x' r') = ?DecEq_rhs_5

```

**Comment by david-christiansen** [comment]
@edwinb I believe you made some changes to make proof search more predictable lately - can this be a consequence of those?

**Comment by edwinb** [comment]
It won't find that, because it doesn't consider the type of each constructor of `Dec` informative enough to proceed. In the interactive mode, it won't search if it can't distinguish the constructors in the target type. This is to prevent it filling it holes with any old rubbish, e.g. `Nothing` whenever there's a `Maybe`, or `Z` if there happens to be a `Nat`.

I think this is the wrong behaviour, because it should probably be happy to search for `Dec` in particular. I don't know what the right behaviour is though.

Essentially, in interactive mode, I'd like to avoid filling in holes with any old value if the type isn't informative enough (so not just any old List or any old Nat). If only I knew exactly what I meant by this, I might be able to implement it...

It might be better to return to the old behaviour until I work out exactly what it is I mean, and just be clear that you will get the first well-typed value it finds.

**Comment by edwinb** [comment]
Oh, just to add - this wasn't really anything to do with being more predictable, so much as giving less surprising behaviour in interactive mode for simpler types. The changes I have been making have involved removing excessive magic and guesswork - in general, Idris should only accept a program if there's only one valid interpretation of anything ambiguous, and there were quite a few cases where this wasn't true.

The one exception to the 'no magic' rule is 'auto' which really is intended to mean 'find me anything that type checks, I don't care what it is'.

**Comment by david-christiansen** [comment]
In the absence of a definition of "informative enough", what about a pragma stating "search this one deeper"?

Also, the old interactive behavior wasn't ever an issue when I was using it or explaining it. I could tell people "See? The type wasn't informative enough, so the thing it picked wasn't what we wanted. Let's go refine that type and use `Dec` instead of `Maybe`...".  Or the "refine" command could be used if I didn't like what proof search was finding.

About the only thing that was unfortunate for me with the old proof search behavior was when it would be a little bit too depth-first and spit out 100-deep nestings of `::` with a hole at the bottom, instead of a `Nil`. Perhaps some kind of breadth-first approach would be nice for interactive mode.

**Comment by ahmadsalim** [comment]
This seems to work fine now, I will close the issue.
