### ISSUE TITLE
Interactive elaborator should make context in term more obvious

### ISSUE THREAD

**Issue by jonschoning** [idris-lang/Idris-dev#2726]
I'm not sure if I've misunderstood `rewriteWith` syntax/semantics, or if there is a bug here

code:
https://gist.github.com/jonschoning/0fcd3ec9413dc8bd266a

error during :elab bsorAssociative_rhs_4
![idris](https://cloud.githubusercontent.com/assets/137183/10431602/97bf8d8e-70cb-11e5-9a4d-dfa5ce70ce64.png)

**Comment by david-christiansen** [comment]
This is because the internal implementation of `rewriteWith` produces a hidden let binding with the rule used to rewrite. To introduce bindings, the hole must be of the right form (the reference to the hole binding must be immediately below the binding itself, like `?h : t . h` rather than `?h : t . f h`).

You can use the `attack` tactic to generate a hole in that form that can be used for whatever your current goal is, enabling binding tactics.

Of course, this user interface gives you no way of knowing that and should be improved!

Here's a version of your script that works for me:
```
intro'
intro'
intro'
intro'
intro'
intro'
rewriteWith `(orAssociative ~(Var `{{x}}) ~(Var `{{y}}) ~(Var `{{z}}))
attack
rewriteWith `(bsorAssociative ~(Var `{{xs}}) ~(Var `{{ys}}) ~(Var `{{zs}}))
search
solve
```

However, I don't think this is the best use of elaborator reflection, because the direct proof is much shorter and more readable:
```
bsorAssociative : (a : BitString) ->
                  (b : BitString) ->
                  (c : BitString) ->
                  (a `bsor` b) `bsor` c = a `bsor` (b `bsor` c)
bsorAssociative [] b c = Refl
bsorAssociative (x :: xs) [] c = Refl
bsorAssociative (x :: xs) (y :: ys) [] = Refl
bsorAssociative (x :: xs) (y :: ys) (z :: zs) =
  rewrite orAssociative x y z in
  rewrite bsorAssociative xs ys zs in
  Refl
```

Writing this made me also realize that `intro'` really needs to return the name that it introduced.

Thanks for reporting your experience, and I'll strive to make this easier!

**Comment by david-christiansen** [comment]
I think that the bad UI constitutes a legitimate issue, so I'd like to keep this open if you don't mind.

**Comment by david-christiansen** [comment]
The interactive elaborator should really show the current proof term the way that the debug tactic does - that would make it much more clear when `attack` is necessary.

**Comment by jonschoning** [comment]
oh, ok!  Thank you for your investigation!!

**Comment by david-christiansen** [comment]
Thanks for showing me where things need to be better!

**Comment by david-christiansen** [comment]
It seems that making `intro'` return the introduced name would require some major updates to Idris guts that aren't worth it at this time. But the UI improvement should be a "mere matter of hacking" - it needs to be disentagled from the old prover's state display, and it should probably also show TT rather than Idris terms.
