### ISSUE TITLE
Installing and referencing packages in non-standard prefixes doesn't seem to work

### ISSUE THREAD

**Issue by shlevy** [idris-lang/Idris-dev#2751]
With shayan-najd/wl-pprint@120f654  running `TARGET=~/.idris-libs idris --install wl-pprint.ipkg` works fine, but if I then run `idris --idrispath ~/.idris-libs -p wlpprint` I get:

> Idris> :module Text.PrettyPrint.Leijen
> Can't find import Text/PrettyPrint/Leijen

**Comment by jfdm** [comment]
When doing package related commands, all options specified at the command line are ignored. There is an upstream patch to address this, but it is not finished yet. 

To fix this, you will need to specify the installation dir when building and installing the wl-pprint package.

**Comment by shlevy** [comment]
I thought that's what the `TARGET` env var did, and indeed I have `~/.idris-libs/wlpprint` populated. How am I meant to specify the installation dir otherwise?

**Comment by shlevy** [comment]
It turns out `--idrispath ~/.idris-libs/wlpprint` did it. Shouldn't `--idrispath` recurse (once at least) into all directories there?

**Comment by jfdm** [comment]
Errm looking at `--idrispath` the docs mention its purpose to be: **Add directory to the list of import paths**. I do think this is expected behaviour, with the 'idris path' being thought of as a list of all the locations that point to the ibc files for an idris package.

If we want to have the option to add an existing 'library' directory to 'idris path' then I think that should warrant a new command line arg. For instance: `idris --addlibdir ~/.local/lib/idris/ --idrispath ../sideproject/ foobar.ipkg`. Where `--addlibdir` points idris to an additional library dir.

As with the `TARGET` env variable, i wasn't aware of that trick. I tend to configure my projects using 'pure' idris tooling.

**Comment by LeifW** [comment]
The "idris --install checking for $TARGET" was my first Idris commit - https://github.com/idris-lang/Idris-dev/commit/81d917f6944bcb6eaa6fbe33805dc67b772a5515

I thought @puffnfresh had done some work to allow multiple libdirs, or at least proposed that?
