### ISSUE TITLE
mutual data declarations without using "mutual" - expected behaviour?

### ISSUE THREAD

**Issue by TimRichter** [idris-lang/Idris-dev#2752]
Hi,

in the example code of #2731, shlevy does mutual data declarations without using 
the "mutual" keyword. Instead of

    module Test
    
    mutual
      data Test : Type where
        Y : Test1 -> Test
      data Test1 : Type where
        O : Test1
        X : Test -> Test1

one obviously can do just

    module Test
    
    data Test1 : Type
    --mutual
    data Test : Type where
      Y : Test1 -> Test
    data Test1 : Type where
      O : Test1
      X : Test -> Test1

to the same effect.

Interestingly, if I leave "mutual" there, I get "Test.Test1 already defined".

Is this expected behaviour?

Best,
Tim

**Comment by shlevy** [comment]
Forward declarations are allowed https://github.com/idris-lang/Idris-dev/commit/895b323bc1f5bf94e0c80a2637e437466bc4eae0 They are more general than mutual blocks I think but are less convenient to use

**Comment by TimRichter** [comment]
Ah, ok. Closing then.
Best,
Tim

**Comment by edwinb** [comment]
Just for information, since this is indeed expected behaviour: mutual blocks are implemented, more or less, by translating to forward declarations. So in this case, the forward declaration appears twice.

I suppose we could allow this, as long as the declaration is identical, but my instinct is that it's probably better for it to be an error since that's unlikely to be something a programmer intended.
