### ISSUE TITLE
Surprising non-reduction on type level in 0.9.20

### ISSUE THREAD

**Issue by pbl64k** [idris-lang/Idris-dev#2804]
After upgrading to 0.9.20 I decided to check whether my tiny pet project still compiled, and to my surprise it failed to do so. There's quite a lot of errors reported by Idris, but as I started digging into it I managed to isolate the behavior that seems to be quite weird to me while still looking at the very first type error:

    %default total
    
    val : {index : Type} -> (index -> Type) -> Type
    val {index = index} ixT = (ix : index) -> ixT ix
    
    ixType : () -> Type
    ixType () = ()
    
    ixVal : (ix : ()) -> ixType ix
    ixVal () = ()
    
    ixVal' : val {index = ()} ixType
    ixVal' () = ()

Unless I'm very much mistaken, `ixVal` and `ixVal'` should be equivalent, but while `ixVal` type checks, `ixVal'` fails with:

    When checking right hand side of ixVal' with expected type
            ixType ()
    
    Type mismatch between
            () (Type of ())
    and
            ixType () (Expected type)

I can't think of a single good reason for `ixType ()` to fail to reduce to `()` here, so I thought I'd report this.

**Comment by david-christiansen** [comment]
The reason is that the rules for automatic universal quantification have been simplified. The new rule is "anything starting with a lowercase letter that's not being applied to something else is an implicit argument", whereas before it searched for any imported name, which let people wreak havoc by exporting "x" from their library. These are now the same rules as in patterns.

The `ixType` there is not referring to the definition above; it's instead referring to a new implicit parameter. You can either explicitly qualify this (something like `val {index = ()} Main.ixType`) or you can rename `ixType` to `IxType`.

**Comment by pbl64k** [comment]
Thank you, that explains it. Argh, I knew what I was signing up for when I started tinkering with a 0.9 language! :-)
