### ISSUE TITLE
Strange Int (show?) behaviour

### ISSUE THREAD

**Issue by norm2782** [idris-lang/Idris-dev#2839]
Consider the following program:

```
a : Int
a = 272773 * 6250

b : Int
b = 1704831250

main : IO ()
main = do
  putStrLn (show a)
  putStrLn (show b)
```

Expected output:
1704831250
1704831250

Actual output:
-442652398
-442652398

System: 64 bit OSX 10.11.1

Interestingly, entering `a` and `b` in the REPL gives the expected result.

**Comment by markuspf** [comment]
I think this is expected behaviour: `Int` only has 31 bits (in code compiled through the C backend), and hence you run into an overflow.

If you want to be on the safe side, use `Integer`.

The reason why the repl gives you a different result is because there Int is interpreted through GHC's runtime.

**Comment by norm2782** [comment]
That would indeed explain the current behaviour. But why have 31-bit Ints and not 32? (or 64 on 64-bit platforms)
Is there any (significant) overhead to using Integers?

**Comment by markuspf** [comment]
The use of 31 bits is because of tagging as `Int`s are unboxed in the C backend. The fact that they are 31 and not 63 bits has something to do with your C compiler (I am not kidding) using 32bit as the size of an int. Of course that could be extended to use longer integers, but there is probably not much of an advantage at this point.

There is some overhead involved in using Integer, since Integers are boxed GMP objects. I cannot quantify this overhead, but if you do benchmarks, do share, please.

**Comment by norm2782** [comment]
OK, too bad, but at least the behaviour can be explained :)
Closing this issue, as it seems to be expected behaviour in the current implementation.

**Comment by Pzixel** [comment]
@markuspf could you please elaborate which exact guarantees `Int` provides? Is it always 32 bits integer or it's a native `int` (32 or 64 bits on modern platforms)? It's essential because of linked issue
