### ISSUE TITLE
Make operator aliases mandatory

### ISSUE THREAD

**Issue by sgraf812** [idris-lang/Idris-dev#2876]
Hi,

as noted in the [breaking changes section of the PureScript 0.8 RC](https://github.com/purescript/purescript/releases/tag/v0.8.0-RC1), they will deprecate operators as regular functions in favor of aliases of a named function. The motivation is more readable generated JS, but I found it interesting for another reason: IDE support. 

Many people find code using custom (e.g. unfamiliar) infix operators hard to understand, yet easier on the eye if understood (think `+`). That's mostly because it's relatively hard to look up the meaning of an operator. Having the tooltip show the name of the aliased function (or have shortcut to convert between infix operator version and regular function application syntax) would make it far easier to understand code making use of operators.

On the other hand, this fosters writing operator heavy code, to which many have a rather partial stance. 

Note that I don't have a really strong opinion on that (especially as I haven't really played with Idris yet), but just wanted to leave a note here and open an discussion.

**Comment by enolan** [comment]
By "it's relatively hard to look up the meaning of an operator" do you mean [because Google won't search for them](https://www.google.com/search?q=%28%3E%3E%3D%29&ie=utf-8&oe=utf-8#q=%3C*%3E)? One of my pet peeves about math is the use of symbols I can't look up or pronounce, and I suppose the same argument applies to programming. It's somewhat mitigated by Idris' in-built documentation - Google might fail, but `:doc` will always work.

I support the idea of making operators easier to talk about and look up, but I'm not convinced making everyone give them a second name will help. We can't force people to write their blog posts about `mappend` instead of `<>` and we can't force them to pronounce them that way in conversation, so we just end up with two names for the same thing.

\*shrug\*

**Comment by sgraf812** [comment]
> Google

That's one thing, although I most of the time know/guess the package containing the operator. 

> `:doc`

Comes close to what I want, but I find the alias a bit more to the point. Also, documentation: If you provide an alias anyway, you either have to duplicate the whole description or have an unsatisfying 'Alias for `view`', which forces you to open the documentation in a browser.

I just see it as a convenient shortcut which often would suffice for understanding the code. If that wasn't the case, browsing the documentation still works out.

> We can't force people to write blog bosts about `mappend` instead of `<>`

Yeah, I found that worrysome, too. But on the other hand, it won't be worse than the current situation.

Coming to think of it, operator aliasing could be optional, in that regular operators as functions still work, but there is additional syntax for defining an operator alias that has this special support by the language tools.

**Comment by LeifW** [comment]
A meta-comment: We tend to reserve this issue tracker for bugs or things that can be definitely implemented in a specific amount of time to close the ticket. For more open-ended things that require discussion, the mailing list (https://groups.google.com/forum/#!forum/idris-lang) or even the feature proposal section on the wiki might be more appropriate: https://github.com/idris-lang/Idris-dev/wiki/Feature-proposals
