### ISSUE TITLE
Watch command doesn't work

### ISSUE THREAD

**Issue by etorreborre** [idris-lang/Idris-dev#2909]
I am not sure what to include in this report to reproduce the issue. Basically I upgraded Idris from `0.9.2` to `0.10` using `brew upgrade`. When I open a file `:l tdd.idr` then `:watch` it nothing happens if I type new contents into the file, even when I had expressions which don't compile:
```idris
*tdd> :watch
tdd.idr
Watching for .idr changes in ["tdd.idr"], press enter to cancel.
```

**Comment by melted** [comment]
I see something similar on Windows. I have tracked down one bug, that it's case-sensitive. Easy enough to fix. I will continue later.

**Comment by LeifW** [comment]
I can reproduce this on Mac OSX.

The relevant code is here: https://github.com/idris-lang/Idris-dev/blob/master/src/Idris/REPL.hs#L691

I added some debug prints (via Debug.Trace), and see what's going on now. I set dir(s) to watch by calling `takeDirectory` (to get the base dir path) on the set of file inputs as reported by Idris.
If the file's in the current dir, the watch dir is just ".",  otherwise, it's something like "/tmp", if I'm editing "/tmp/tdd.idr"

The edit events come back as happening to "/private/tmp/tdd.idr". Which I don't respond to, as that doesn't look like one of the files I was initially watching ("/tmp/tdd.idr"). Sounds like a bug with the Mac bindings for this fsnotify lib, if you ask me; I said I was watching "/tmp", so why are change events in there coming back as "/private/tmp"? I'll look into that, but we could probably hack up a workaround for now.

**Comment by LeifW** [comment]
One workaround that seems to work for now: If I say `:l /private/tmp/tdd.idr` (instead of `:l /tmp/tdd.idr`), then I'm watching `/private/tmp/tdd.idr`, and the change events still come back as `/private/tmp/tdd.idr`, so everything works.

**Comment by LeifW** [comment]
Sounds like "/tmp" is a symlink into "/private/tmp" on OSX. Some things I'm thinking: we can canonicalize all paths (maybe things are already coming back canonicalized in the events, as above?) - use absolute paths (rather than ".", as above), and resolve symlinks. On case-insensitive file systems we could normalize everything to one casing or use a case-insensitive comparison...

**Comment by LeifW** [comment]
So if you access your source at a non-symlinked path, which is not relative to the $PWD of the Idris process, it'll work on OSX currently. (as the events come back as absolute paths w/ symlinks resolved). Could also just ignore the paths and filenames, and just watch for all changes to *.idr files in the dirs you've loaded source from. (Currently it checks to see if the edit event in the dir happened to one of the files in your initially loaded set).

**Comment by melted** [comment]
It would be so nice to have a function that return True if two filepaths represents the same file.

**Comment by LeifW** [comment]
On linux, the events come back w/ symlinks resolved (so if I'm editing foo in my editor, where foo is a symlink to bar, edit events come back on bar). Can just apply `System.Directory.canonicalizePath` to the input set we're checking edits against - says it resolves ".", "..", and symlinks. Except they say it doesn't resolve symlinks on windows. Maybe we should just call `takeFIleName` on everything, and ignore the directories. Also: do we want watch to just watch the immediate dir, or also recurse into subdirs (might be handy when jumping around a large project to just watch the top dir)?

**Comment by LeifW** [comment]
@melted Did you have some more ideas about what to do for case-insensitive filesystems? One of the things I mentioned above might help: Watch for changes to '*.idr' files rather than specifically the ones you have loaded (in specific subdirs), so we wouldn't care about filenames / paths. Also, I fixed the PR that canonicalizes paths.

**Comment by LeifW** [comment]
@etorreborre Can you see if the just-merged PR fixes your use case? Or describe the paths / files involved on your system a bit more, and I can try?

**Comment by etorreborre** [comment]
@LeifW I am sorry but I have just moved from one continent to another and don't have much time to spend on my laptop at the moment. I'll give it a go as soon as I can.

**Comment by LeifW** [comment]
I'm assuming the issue he had has been fixed by that PR. If no one else can reproduce, maybe this issue can be closed for now, and re-opened if it's still a problem?

**Comment by etorreborre** [comment]
Sure I hope I can resume my study of Idris soon enough to confirm that :-) but let's close it for now.

**Comment by justjoheinz** [comment]
@LeifW : I have not read the whole issue (symlinks etc.), but the use case described originally in the issue by @etorreborre works now on Mac OS X/idris 0.11

**Comment by ahmadsalim** [comment]
Yeah, it seems that reported things works as @justjoheinz confirms.
