### ISSUE TITLE
Make list syntax be given by implementing a List interface

### ISSUE THREAD

**Issue by ObscureScience** [idris-lang/Idris-dev#2931]
What would be your thoughts of making the automatic list syntax for data types by defining Nil and (::) constructors be derived from a List interface instead? Do-notation comes from implementing the Monad interface, right?

Such as: 
```
data Vect : a -> Nat -> Type where
    EmptyVect : Vect a 0
    VectCons   : a -> Vect a n -> Vect a (n + 1)
 
List (Vect a n) where
    Nil = EmptyVect
    (::) = VectCons
```

**Comment by reuben364** [comment]
n doesn't appear in EmptyVect, so there is no way to elaborate for which n Nil would be an instance of.

**Comment by david-christiansen** [comment]
I don't think this is really appropriate as an issue report - we have a mailing list for more open-ended questions of design.

In any case, requiring users who want square bracket syntax for lists to implement a particular interface would make it far less useful, because it would restrict the types of available operations significantly. 

Also, `do`- notation in Idris is usable if there's a type-correct `>>=` operator in scope - it need not be the one from `Monad`. Again, this is to allow a greater flexibility in clients.
