### ISSUE TITLE
Custom install and search paths for `idris --build` and `idris --install`

### ISSUE THREAD

**Issue by suhr** [idris-lang/Idris-dev#2932]
So you could install a package into a custom dir, and then use that dir to build an another package.

**Comment by LeifW** [comment]
The `--install` command respects the `TARGET` environment variable, so you could run `TARGET=/tmp/foo idris --install blah.ipkg`.  There's also an argument you can pass to Idris to add another dir to the lib path, but I'm not sure what it is at the moment. I think @puffnfresh did some work there?

**Comment by LeifW** [comment]
Oh, right below in that file, it looks like you can replace the location of libdir by setting the `IDRIS_LIBRARY_PATH` environment variable: https://github.com/idris-lang/Idris-dev/blob/master/src/IRTS/System.hs#L59

**Comment by suhr** [comment]
I see. Well, Idris needs some documentation on environment variables.
(though, some cli flags might be useful too)

**Comment by jfdm** [comment]
Sorry for not getting back to you sooner on this. There is documentation on env variables coming later today.

Actually, Idris does support multiple include paths. The CLI option `-i <dir>` allows you to add a directory to the search path; this option can be used multiple times. This is a cleaner option than using `IDRIS_LIBRARY_PATH`. Further rather than using `TARGET` the CLI option `--ibcsubdir` can be used to direct where built IBC files are placed.

I'll close this issues once the docs on environment variables are merged.

**Comment by suhr** [comment]
Sorry, but it doesn't work.

```
% TARGET=../../target idris --install lightyear.ipkg
Type checking ./Lightyear/Core.idr
Type checking ./Lightyear/Combinators.idr
Type checking ./Lightyear/Errmsg.idr
Type checking ./Lightyear.idr
Type checking ./Lightyear/Char.idr
Type checking ./Lightyear/Strings.idr
Type checking ./Lightyear/StringFile.idr
Installing Lightyear.ibc to ../../target/lightyear
Installing Lightyear/Core.ibc to ../../target/lightyear/Lightyear
Installing Lightyear/Combinators.ibc to ../../target/lightyear/Lightyear
Installing Lightyear/Errmsg.ibc to ../../target/lightyear/Lightyear
Installing Lightyear/StringFile.ibc to ../../target/lightyear/Lightyear
Installing Lightyear/Strings.ibc to ../../target/lightyear/Lightyear
Installing Lightyear/Char.ibc to ../../target/lightyear/Lightyear
Installing 00lightyear-idx.ibc to ../../target/lightyear
% cd ../testing
% TARGET=../../target idris -i ../../target --install  test.ipkg 
Can't find import Lightyear
% TARGET=../../target idris -i ../../target/lightyear --install  test.ipkg 
Can't find import Lightyear
```

(I'm trying to build https://github.com/jfdm/idris-argparse)

**Comment by jfdm** [comment]
The reason it is not working is that when installing packages, all other command line options are ignored, I believe only the env vars can override. I did have a fix for allowing a subset of the options through, but it needs revisiting due to implementation issues.

**Comment by suhr** [comment]
> I believe only the env vars can override.

They can, but you can't have multiple paths in `IDRIS_LIBRARY_PATH`, that's the problem.

> I did have a fix for allowing a subset of the options through, but it needs revisiting due to implementation issues.

I believe this issue should be open until it is fixed.

**Comment by jfdm** [comment]
I do not think this issue needs to be open as the functionality you require can be accessed and is available, through the IPKG format when dealing with packages, and from the command line otherwise. See the [effects ipkg file for an example](https://github.com/idris-lang/Idris-dev/blob/master/libs/effects/effects.ipkg#L3).

However, the issue you later described is from the 'restriction' that ipkg files block all options specified on the command line, and only derive their options from the ipkg file itself. There is a PR #3071 that I revised today that will address this restriction when it is merged.

**Comment by jfdm** [comment]
Further, i was reminded today that the option `ibcsubdir` is ignored completely by the idris package build tooling. This is noted in #499.
