### ISSUE TITLE
New visibility rules and %hide directives

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2945]
The program
```
> module NatDivisorProperties

> %default total
> %hide (-)

> (-) : Nat -> Nat -> Nat
> (-) = minus

> Divisor : (m : Nat) -> (n : Nat) -> Type
> Divisor m n = Subset Nat (\ q => m * q = n)

> oneDivisorAny : (m : Nat) -> (S Z) `Divisor` m
> oneDivisorAny m = Element m (multOneLeftNeutral m)

> divisorMinusLemma : (m : Nat) -> (n : Nat) -> (d : Nat) ->
>                     d `Divisor` m -> d `Divisor` n -> d `Divisor` (n - m)
```
type checks fine with Idris 0.9.20.2-git:f6f97eb. But with 0.10-git:0cbea4a, one gets
```
- + Errors (1)
 `-- new_type_mismatch.lidr line 13 col 26:
     When checking right hand side of oneDivisorAny with expected type
             Divisor 1 m
     
     When checking argument pf to constructor Prelude.Pairs.Element:
             Type mismatch between
                     1 * m = m (Type of multOneLeftNeutral m)
             and
                     (\q => plus q 0 = m) m (Expected type)
             
             Specifically:
                     Type mismatch between
                             plus m (mult (fromIntegerNat (1 - 1)) m)
                     and
                             plus m 0
```
Is this the expected behavior? Is it an error? How is %hide meant to be used under the new visibility rules? Thanks, Nicola

**Comment by edwinb** [comment]
I think this is because `%hide` has the wrong behaviour, and the new export rules have managed to highlight this. All `%hide` should really do is make the name inaccessible to programs. What it actually does is change the name's visibility from public to private. In the old rules, private things would happily reduce, but in the new rules, they don't. 

So the %hide has, in addition to hiding (-), stopped it from reducing in any definitions which use it.

I'll fix this once I've worked out what the right way to fix it is...

**Comment by nicolabotta** [comment]
Thanks Edwin!
