### ISSUE TITLE
Coverage of interface implementation is not checked for totality

### ISSUE THREAD

**Issue by colin-adams** [idris-lang/Idris-dev#2962]
E.g.:

module Test_show

%default total

data Te = C1 | C2 | C3

Show Te where
  show C1 = "C1"
  

This checks (Idris 0.10) without complaining, both in Emacs and with:

idris --check test_show.idr

**Comment by colin-adams** [comment]
It's also interesting to add a partial Eq implementation:

  (==) C1 C3 = False

Now the command line correctly flags the problem:

Prelude.Classes.Test_show.Te implementation of Prelude.Classes.Eq, method == is not total as there are missing cases
./Prelude/Classes.idr:28:5:
Prelude.Classes.Test_show.Te implementation of Prelude.Classes.Eq, method /= is possibly not total due to: Prelude.Classes.Test_show.Te implementation of Prelude.Classes.Eq, method ==

In emacs, the line of code is underlined in red, but the only message given is "No holes found!".

**Comment by edwinb** [comment]
It turns out this is getting checked but not reported - everything gets checked for totality whether you have the 'total' default or not, but this isn't being reported because 'show' in the prelude is explicitly marked as okay to be 'partial'. This explains why you don't see a similar problem for Eq.

Your '%default total' should override this for your instance, but doesn't. 

I have a fix for this, but I want to make it a slightly better fix before I push it...
