### ISSUE TITLE
Can't write VerifiedFunctor as a single class

### ISSUE THREAD

**Issue by enolan** [idris-lang/Idris-dev#2989]
This definition won't typecheck on 65125ae:
```idris
interface MyFunctor (f : Type -> Type) where
    fmap  : {a, b : Type} -> (a -> b) -> f a -> f b
    identityProperty : {a : Type} -> (x : f a) -> fmap Prelude.Basics.id x = x
```
The error message is:
```
Type checking ./interfacebug-broken.idr
interfacebug-broken.idr:3:56:When checking type of constructor of Main.MyFunctor:
When checking an application of fmap:
        Type mismatch between
                a9 -> a9 (Type of id)
        and
                a9 -> b (Expected type)
        
        Specifically:
                Type mismatch between
                        b
                and
                        a9
```
This is a stone's throw from the definition in [Classes.Verified](https://github.com/idris-lang/Idris-dev/blob/master/libs/contrib/Classes/Verified.idr#L16-L20).

It won't let you use fmap without returning a `b`. Something is wrong with the scope of the `a` and `b` parameters maybe?

It works if you use a regular `data` declaration, and you can instantiate it like you'd expect:
```idris
data MyFunctor : (Type -> Type) -> Type where
    MkMyFunctor : (fmap : ({a, b : Type} -> (a -> b) -> f a -> f b)) ->
                  ({a : Type} -> {x : f a} -> fmap Prelude.Basics.id x = x) -> MyFunctor f

listIdPrf : {x : List a} -> map Prelude.Basics.id x = x
listIdPrf {x = []       } = Refl
listIdPrf {x = (x :: xs)} = rewrite listIdPrf {x = xs} in Refl

listFunct : MyFunctor List
listFunct = MkMyFunctor map listIdPrf
```

**Comment by edwinb** [comment]
This appears to be an effect of the way dependent interfaces work, which were implemented before we had scoped implicits. Interfaces probably need to be implemented again (or at least modified) because they'd be much cleaner if they used scoped implicits rather than the series of hacks they currently use.

Anyway, I can see where the problem is here, in where it inserts implicits, but since there's no comment on the code in question I'll have to work out what I was thinking and find out what breaks if I undo it...
