### ISSUE TITLE
More concise declarations

### ISSUE THREAD

**Issue by jeffersoncarpenter** [idris-lang/Idris-dev#2994]
Writing variables twice can be verbose:
```
someConstantUsedInProgram : Nat
someConstantUsedInProgram = 5
```
I'd rather write this:
```
someConstantUsedInProgram : Nat
                          = 5
```
Using `=` that way might cause some parsing problems; something like this would suffice:
```
someConstantUsedInProgram : Nat
                          := 5
```

**Comment by edwinb** [comment]
I see your point, but I don't think this would be consistent with the rest of the syntax. Perhaps a top level let binding might be nicer. Or even allowing type inference in limited, well defined, situations.

I'm flagging this "Feature request" so that people can find it if someone wants to try to make it work in a nice, consistent, parser friendly way. But I will probably close this in a few days unless there turns out to be enthusiasm for it and a concrete proposal. There may be other better ways to achieve more concise definitions after all.

**Comment by jeffersoncarpenter** [comment]
Top level let bindings would work.

```
let someConstantUsedInProgram
  : Nat
  = 5
```

looks beautiful.

**Comment by david-christiansen** [comment]
Given that Idris already will generate the extra copy of the name, I don't see the big win in complicating the syntax here. Having more syntax to explain is a real cost, and I'm not sure that the modest benefit outweighs it here.

**Comment by david-christiansen** [comment]
Having type inference for top-level bindings whose type is sufficiently unambiguous may be better, but even there, it makes the language more complicated. Consider:

* Right now, documentation is attached to type declarations, not definitions. If we introduce definitions without declarations, then we need to support documenting them, and suddenly a program might become invalid by adding a type declaration but not moving the documentation to the declaration. Also, we'd need to keep proper track of all this to provide good errors.

* Other modifiers, such as `export`, would also need to be tracked like documentation.

* Defaulting should probably be turned off here. Which would mean that defining a numeric constant should fail, because they are so overloaded. I think that numeric constants would be a big use case for this kind of thing.

WRT `let` as a declaration, please consider:

* Code like the following might be confusing:
```
addFive : Nat -> Nat
addFive n = plus five n
  where let five : Nat = 5
```
Right now, `where` blocks can contain basically any top-level declaration, but now that we have `let` serving both as a declaration form and an expression, it may not be immediately obvious which role it's playing.

* In which contexts should we allow the `let`? E.g. interface default definitions? For example,
```
interface (Applicative m) => Monad m where
  let (>>=) : m a -> (a -> m b) -> m b = \x f => join (map f x)
  let join : m (m a) -> m a = flip (>>=) pure
```
Idris is already a fairly big language. I think we should only add features that make a big difference in readability or writability, and I think that having to ask the text editor to make an initial definition from a type declaration is a small price to pay in this case.

**Comment by xekoukou** [comment]
Let me make a far reaching comment here. There are 2 properties that are
affected by this change. The same properties take place in any type of code
generation or language specification.

A)The first property tries to reduce the duplication of code. We want to
write less and the code we write to be used in many places.
B) The second property is about the mental capacity that is required to
understand and use something. There are 2 cases here:
  1) The complexity of the code and the mental processing required to
understand it.
  2) The mental memory required to remember it.

In my opinion, B) should always be more important than A).

Here, if this is accepted, then we have two definitions instead of one, the
memory required is doubled. One also needs to remember that even though the
syntaxes are different, they are the same thing.

**Comment by jeffersoncarpenter** [comment]
Idris can generate the second copy of the name, but that only helps the programmer if they have editor support.  Teaching people language syntax is costly, but getting people informed about the refactoring tools is also costly.

I agree about complicating the syntax, @david-christiansen and @xekoukou .  I would only want to implement this if it fit well with the rest of the language.  I think the first syntax I gave is the best one.  Overloading the `let` keyword would not work well.  As to what contexts to allow in, I'd say any context that currently allows both declarations and definitions.  But I am still reading Idris source code at this point - I'm not sure on the details yet.

**Comment by jeffersoncarpenter** [comment]
Top-level let binding is precisely the feature being requested.  The syntax would not include the `let` keyword - it would use `:` and `=` to be consistent with declarations and definitions.

If the programmer defines a variable immediately after they declare it, they may omit the variable name from the definition.

```
addFive : Nat -> Nat
addFive n = plus five n
  where five : Nat
             = 5

interface (Applicative m) => Monad m where
  (>>=) : m a -> (a -> m b) -> m b
        = \x f => join (map f x)
  join : m (m a) -> m a
       = flip (>>=) pure
```

**Comment by david-christiansen** [comment]
I totally get where you're coming from, but I still don't think that this latest proposal works, because it would overlap with the equality type. In particular, your example:
```
addFive : Nat -> Nat
addFive n = plus five n
  where five : Nat
             = 5
```
could just as well be parsed as the moderately absurd definition:
```
addFive : Nat -> Nat
addFive n = plus five n
  where five : Nat = 5
```
where `five` is an unimplemented declaration that the type `Nat` is equal to `5`.

**Comment by david-christiansen** [comment]
Also, Idris is designed to be easy to integrate with many editors, and if your editor of choice isn't powerful enough to run a command in the background, the REPL can be used. The interactive aspect of Idris is pretty important, and it shouldn't be taken to be an optional extra. Every Idris user should really learn the basics of the interactive editing.

**Comment by jeffersoncarpenter** [comment]
Ah yes, that syntax for a let binding would overlap with the equality type.

Interactive editing, I agree is critical.  There is a lot of work Idris will just do for you.  Also, I don't think it's ever necessary to write down a variable that you are defining more than twice.  That's really not so bad.

Closing this issue is fine with me.
