### ISSUE TITLE
Elaborator shell: Using :term after intro' causes error, aborts shell

### ISSUE THREAD

**Issue by jchoules** [idris-lang/Idris-dev#3000]
When I start the elaboration shell to prove a metavariable, the `:term` command initially works fine:

```
Idris> :l min_test_case.idr
Type checking .\min_test_case.idr
Holes: Main.whats_f
*min_test_case> :elab whats_f


----------                 Goal:                  ----------
{hole0} : Nat -> Nat
-Main.whats_f> :term
TT: ? {hole0} . {hole0}
```

(The contents of `min_test_case.idr` are simply:

```
f : Nat -> Nat
f n = ?whats_f
```

by the way.)

However, if I use the `intro'` tactic and then use `:term` again, I get kicked out of the elaborator shell and back into the main Idris shell:

```
-Main.whats_f> intro'

----------              Assumptions:              ----------
 n : Nat
----------                 Goal:                  ----------
{hole0} : Nat
-Main.whats_f> :term
TT: <stdout>: commitBuffer: invalid argument (invalid character)
Holes: Main.whats_f
*min_test_case>
```

I'll be honest: I've yet to get to grips with the elaborator shell properly, so I don't really know what the expected behaviour of `:term` would be in this case, but it seems to me that it shouldn't crash the shell.

(I'm using Idris 0.10 (precompiled binary) on Windows 10, if that helps.)

**Comment by david-christiansen** [comment]
Interesting. This is probably because the TT pretty-printer uses various Unicode characters that are not being properly accepted by the IO routines on Windows. In this case, `intro'` is wrapping the hole in a lambda.

Thank you very much for an excellent issue report that makes it very easy to see what's happening.

The expected output after `intro'` is this:
```
-Main.whats_f> :term
TT: λ n . ? {hole0} . {hole0}
```

It might be Idris wanting to output UTF-8 to a UCS-16 API, but I'm not sure.

@melted, do you happen know what I need to do here to fix this? Is it a matter of setting a locale, or using the right Haskell API?

**Comment by david-christiansen** [comment]
If I can't figure out how to display the special characters reliably on Windows, then I can always do a platform test and then show ASCII equivalents, I suppose, but I'd really like to maintain the visual distinction between TT and Idris as well as have a first-class experience for Windows users.

**Comment by melted** [comment]
I see, or rather I don't because I stick a chcp 65001 in my initscripts (no matter if it's msys, poweshell and good old fashioned cmd) so I get an UTF-8 terminal. I tried to set that in Idris, but that broke down for people who had localized messages in other codepages. I suppose it's possible to detect the locale and not print fancy chars for those who aren't in a unicode locale.

**Comment by melted** [comment]
It's not particular to windows, it's just that an unicode locale is the default on most unixes now (though I had to jump through several hoops to get utf-8 by default on FreeBSD not long ago). One compromise could be to tell the IO lib to be nicer when unicode chars appear when latin1 is set. Haskell's base has a draconian default in that case.

**Comment by david-christiansen** [comment]
All right, I suppose this should be workable.

**Comment by melted** [comment]
@david-christiansen can you query an useUnicode flag when printing, and make it a command line option so it can be shut off for now. I can try to find out a way to detect it and set it automatically.

**Comment by david-christiansen** [comment]
Yes, that should be doable. Annoyingly, the relevant pretty printer is pure, but it can just take a Bool flag.

**Comment by ahmadsalim** [comment]
@jchoules @melted Is this still an active issue?

**Comment by jchoules** [comment]
@ahmadsalim I've just tested this on the 0.12 precompiled Windows binary and it exhibits exactly the same behaviour as initially reported.

**Comment by david-christiansen** [comment]
That would make sense, because I haven't done anything about it yet.

A useUnicode flag would be the way to go, as Niklas says.

2016-07-08 15:03 GMT-04:00 Jake Choules <notifications@github.com>:

**Comment by RyanGlScott** [comment]
As someone who's had to work around these sorts of hairy `commitBuffer: invalid argument (invalid character)` issues on Windows many times, I think the solution could be pretty simple.

The issue is that GHC's default encoding for `stdout` is determined by the code page of your console, and much of the time, it's something like CP437, which has abysmal UTF-8 support (and in fact, GHC will just opt to crash with the error above if you try to print UTF-8 characters it doesn't support!). So to get around this, you need to:

1. Change the codepage to something that's UTF-8 aware (i.e., CP65001)
2. Change the encoding that GHC uses internally using `hSetEncoding`

If you do both of these things, you can support Unicode just fine on Windows. In fact, I do this so often that I created the [`code-page`](http://hackage.haskell.org/package/code-page) library, which exports a [`withCP65001`](http://hackage.haskell.org/package/code-page-0.1.1/docs/System-IO-CodePage.html#v:withCP65001) function for performing an IO action within a temporarily altered codepage/encoding. For reference, `code-page` is how [`criterion`](https://github.com/bos/criterion/pull/125) and [`doctest`](https://github.com/sol/doctest/pull/149) currently handle Unicode on Windows.

I wouldn't object to a `useUnicode` flag either, but I think defaulting to CP65001 makes a lot more sense for a Unicode-aware project like Idris than a Unicode-deficient codepage.
