### ISSUE TITLE
UniqueTypes in IO Monad

### ISSUE THREAD

**Issue by xekoukou** [idris-lang/Idris-dev#3005]
Right now, the io monad does not accept UniqueTypes.

**Comment by edwinb** [comment]
This isn't going to happen, sorry. UniqueTypes are experimental, and not really intended for this, and having IO support both would require some deep thought about how to change the type system to support uniqueness polymorphism.

We will, at some stage, come up with some better support for linear types so that we can reason better about memory allocation. It probably won't involve UniqueType.

At some point I'll make UniqueType accessible only with a %language pragma.

**Comment by xekoukou** [comment]
I am not so much interested in better memory allocation. I liked the
example you made in your talk with the "door" state machine in which you
used a unique type.

Apart from that, I think that the IRS should be general enough so as not to
impose a certain type of implementation. Thus, I would suggest that the
type system provided information in the IR that one could use or simply
ignore.

For example, instead of asking to INLINE, one could give the number of
possible applications of a function.
