### ISSUE TITLE
Reverse Ranges no longer work.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#3065]
Issue #2801 reported erroneous behaviour with ranges in the REPL. This was due to a change in how `Nat`  and `minus` and `(-)` worked.

Although the issue was addressed for positively increasing ranges, negatively decreasing ranges are still not working. For example:

```Idris
Idris> [1,3..9]
[1, 3, 5, 7, 9] : List Nat
Idris> [5,4..1]
(input):1:1-9:When checking argument smaller to function Prelude.Nat.-:
        Can't find a value of type
                LTE 5 4
```

**Comment by ericqweinstein** [comment]
Not sure if this should be a separate ticket, but should we expect negative ranges to work as well?

```idris
Idris> [-9, -7..-1]
(input):1:11: error: unexpected
    Operator without known fixity:
    ..-, expected: space
[-9, -7..-1]<EOF>
          ^
Idris> [(-9), (-7)..(-1)]
Can't disambiguate since no name has a suitable type:
        Prelude.Interfaces.-, Prelude.Nat.-
```

**Comment by jfdm** [comment]
yes.

**Comment by ahmadsalim** [comment]
I don't think it needs to be a separate ticket, it is better to have very related issues collected.

I think that @jfdm was answering your last part, negative ranges should work.

**Comment by jfdm** [comment]
Sorry, yes negative ranges should work, and the symptoms exhibited by both are more than likely caused by the same underlying problem. No need to create a separate issue.

**Comment by zjhmale** [comment]
any plans to fix this? at this moment maybe should take a trade off like

```idris
reverse [1,2..5]
```

**Comment by dc-mak** [comment]
Reverse ranges still seem to work with `the (List Int) [5,4..1]` (and `Integer`), so, from looking at the code (src/Prelude/prelude.idr) the main issue comes up with using the increment as a flag (which works for `Integer`s and `Int`s because they can be negative) but not, as shown by the type error (because of `(-)`, which requires a proof `smaller` of m < n) for `Nat`s. Replacing `(-)` with minus won't work either (because then it would just result in a `Z` increment).

I think it might make more sense/be more general if, instead of passing `from, inc, to` we passed `from, next, to` to the range functions. That way it can do a comparison before deciding the direction of the range (and if done right/with a bit of care, will also allow [5..1] as a range, if enough people think this is a good idea). However that would break any code using the `Enum` classes range methods directly (instead of through the syntactic sugar).

Alternatively, we could use the Int/Integer implementations as the basis for the defaults and then `map toNat`, but I can see why it would be nice conceptually to have Nats as the defaults for Enum methods.
