### ISSUE TITLE
parse error in simple let binding 

### ISSUE THREAD

**Issue by libeako** [idris-lang/Idris-dev#3073]
The following simple code does not compile.

```
x : Nat
x =
	let 
		f : Nat -> Nat
		f n = 3
	in 1
```
Error message is
```
error: expected: dependent type signature
        let  
        ^    
```
I am novice in idris, so may be wrong, perhaps this should not compile.
The whitespace used for indentation is tabulators.
I am using Idris 0.11 insalled by cabal.
My command line was `idris --check file.idr`.
May be related to #1402.

**Comment by edwinb** [comment]
Hi,
Let is only for binding individual names, it doesn't do functions in the same way as Haskell. You can use a 'where' clause for this instead.

I think in theory we could make this work, but it's unlikely that we'll do so any time soon (unless someone has enough enthusiasm to have a go, I suppose...). I'll close this, but also flag it as a feature request so that it's at least searchable.
