### ISSUE TITLE
idris: Can't happen: Not an exportable arithmetic type

### ISSUE THREAD

**Issue by colin-adams** [idris-lang/Idris-dev#3082]
I received this message when trying to compile a program (that type-checks cleanly).

To reproduce:

1) Checkout https://github.com/colin-adams/idris-libmicrohttpd, commit 539e685fc49ed26ee8738b812094134d9222c41b
2) idris --install MHD.ipkg
3) cd example
4) idris --build Simple_post.ipkg

**Comment by edwinb** [comment]
From glancing at the FFI code - are you trying to export one of the Bits types? It looks like that hasn't been implemented yet (which makes the error message wrong, because it clearly can happen...)

I haven't yet been able to reproduce this since apparently my libmicrohttpd install is broken (I just did a brew install and hoped it would work...).

If this is the problem, it should be easy to fix it. I'm just not sure why Bitsn were put in the FFI structure at all when the marshaling to C isn't implemented.

**Comment by colin-adams** [comment]
What do you mean by exporting one of the Bits types? I certainly make
extensive use of them. But I can't find a type that is exported where the
return type is Bitsn.

**Comment by edwinb** [comment]
Sorry, I mean calling a C function passing in a Bitsn type.

**Comment by colin-adams** [comment]
actually, I DO export one:


||| Run using an internal thread (or thread pool) doing select().
export MHD_USE_SELECT_INTERNALLY : Bits32
MHD_USE_SELECT_INTERNALLY = 8

And yes, I have lots of routines that pass a Bits32 to C. But I don't THINK
that's new for my code (I might be wrong).

**Comment by colin-adams** [comment]
Confirmed - I was already passing a Bits32 to a C routine (unsigned int)
and that was working.

**Comment by edwinb** [comment]
Okay, I don't have an easy way to test this, but I'm about to push a patch which may fix this. I think all it needs to do is to build the right C type since the marshaling code is indeed there.

**Comment by colin-adams** [comment]
Fixed.
