### ISSUE TITLE
Clarification or Documentation of the types of Literals

### ISSUE THREAD

**Issue by HalosGhost** [idris-lang/Idris-dev#3089]
```hs
Idris> :t 7
7 : Integer
Idris> :t exp
exp : Double -> Double
Idris> exp 7
1096.6331584284585 : Double
```

So, apparently, the type of ``7`` is ``Integer``, but passing ``7`` to ``exp`` which expects a ``Double`` works instead of throwing a type error.

Is this just that the type of ``7`` is actually ``Num a => a`` (like it is in Haskell), and something is odd about ``:t``'s resolution of ``7``'s type?

**Comment by jfdm** [comment]
@HalosGhost  This is expected behaviour.

The `7` in `exp 7` will not have type `Integer`, and will be of  type `Double`

Off the top of my head, I am not sure if Idris does treat `7` *exactly* as Haskell treats `7`, but I do know Idris is 'smart' with literals as Haskell is `smart`; probably a different means of smart. The Idris elaborator will ensure that the `7` literal will be of the right type.

To show this we can make use of the `the` function to specify the type of something; handy if the type elaborator is unsure. For example take the following Idris REPL session:

```idris
Idris> :t the Double 7
the Double 7 : Double
Idris> :t the Integer 7
the Integer 7 : Integer
Idris> exp (the Integer 7)
(input):1:10:When checking argument a to function Prelude.Basics.the:
        Type mismatch between
                Double (Inferred value)
        and
                Integer (Given value)
```

Hope this helps.

**Comment by Melvar** [comment]
To expand on the explanation, an integer literal is treated as an application of `fromInteger` to the literal as an `Integer`. `fromInteger` is subject to the usual type-directed disambiguation in addition to `Prelude.Interfaces.fromInteger : Num ty => Integer -> ty` utilizing an interface.

The result seen above is because the REPL has a defaulting rule in favor of `Integer`; otherwise things like `:t 7` would yield an error because the desired type could not be inferred.
