### ISSUE TITLE
repl function call shows generated code

### ISSUE THREAD

**Issue by Fathardie** [idris-lang/Idris-dev#3152]
Hi all!

I have just started using Idris. Currently I am using Idris v0.11.1 on Arch linux. I installed using cabal install idris with Cabal 1.22.5.0 and GHC 7.10.3. When I try to use repl, I get a never-ending generated code string instead of the read-eval-put-loop I expected. I tried using the following snippet directly in REPL:

`repl "hello" (\str => str)`

I also tried using repl in a document loaded into Idris with the same result. The generated code starts with:

    io_bind (io_bind (prim_write "hello") (\__bindx => io_return ()))
        (\__bindx =>
           io_bind (io_bind prim_read
                            (\x =>
                               io_return (prim__strRev (with block in Prelude.Interactive.getLine', trimNL (MkFFI C_Types String String)
                                                                                                           (prim__strRev x)
                     
Seeing as this is very unexpected, I think it is a bug but I am not sure of course (very new to Idris :P). Hopefully you guys and girls can help me! Thanks in advance!

**Comment by gpyh** [comment]
This is not a bug, although I guess the pretty printer for this function could be overloaded.

`repl` returns an IO action. When used in the main body of a compiled module, the IO action is executed. This execution doesn't occur in the same sense as a pure function. It is executed in the sense that the IO action is hooked into the terminal, then executed *outside* of Idris if that makes sense.

In the Idris REPL, you are not in a terminal. You are in a pure context. The functions are therefore executed and the result is returned to you. Because `repl "hello" id`  is of the `IO ()` type, it is not really a function, it is simply an IO action, which in turns in simply a value in the IO monad. The REPL executes your expression until is has an IO action and shows it to you. As `repl` is intended to never terminate, the REPL never stops displaying the IO action.

To illustrate my point, do `3 + 3` in the REPL. It returns `6 : Integer`. The pure function `(+)` is executed and an `Integer` is returned, then pretty printed. Doing `repl "hello" id` is really the same. Do `putStrLn "yo"` do see what a non-recursive IO action would print.

**Comment by Fathardie** [comment]
Ahh got it! Big difference from Haskell but Idris' way is more logical if follow your explanation. I tried to find any documentation on how to run it in REPL anyways but I couldn't. Anyone in a similar situation, :exec is your friend.

Thanks @gpyh!

**Comment by gpyh** [comment]
I just found out about `:x`. According to the REPL help:

```
:x      <expr>    Execute IO actions resulting from an expression using the interpreter
```

**Comment by jfdm** [comment]
Good to see people figuring it out for themselves. 

The REPL and compiler work [slightly differently](http://idris.readthedocs.io/en/latest/faq/faq.html#evaluation-at-the-repl-doesn-t-behave-as-i-expect-what-s-going-on). When in the REPL `:x` can be used to execute IO actions, and `:main` to run the main method of the module you are currently in, IIRC.

In case you guys were not aware, Idris has some nice documentation features. When in the REPL `:?` gives a list of commands. `:browse`, `:apropos`, `:search`, `:doc` can be used to show namespaces, generic searches, type based search of APIs, and show documentation. These can be accessed in most supported editors. There is also http://idris.readthedocs.io and http://www.idris-lang.org/documentation/
