### ISSUE TITLE
Allow mutual dependence between default interface methods and interface-dependent functions

### ISSUE THREAD

**Issue by gpyh** [idris-lang/Idris-dev#3168]
Consider this: 

``` idris
interface MyInterface a where
  bar : a -> b
  bar = ?bar_rhs
  foo : a -> b
  foo = bar
```

`foo` depends on `bar`. They both provide a default implementation and depend on the type of the implementation.

An implementation can override `foo`, which is fine, but I don't want `bar` to be overridden. I need it outside of the interface.

In Haskell, I would do something akin to this:

``` idris
bar : MyInterface a => a -> b
bar = ?bar_rhs

interface MyInterface a where
  foo : a -> b
  foo = bar
```

Problem is, the order is messed up because bar depends on `MyInterface`.

Symmetrically:

``` idris
interface MyInterface a where
  foo : a -> b
  foo = bar

bar : MyInterface a => a -> b
bar = ?bar_rhs
```

`foo` is trying to use the `bar` function that is not already defined. 

How such a problem would be solve?

**Comment by ahmadsalim** [comment]
Have you tried putting things in a mutual block?

**Comment by ahmadsalim** [comment]
OK, this doesn't work with `mutual` around everything either.

**Comment by edwinb** [comment]
It turns out mutual blocks don't properly respect interface definitions... probably because I didn't work out what the rules should be. I'll take another look.

**Comment by edwinb** [comment]
Oops, closed the wrong issue via a commit...

**Comment by edwinb** [comment]
I'm changing this so that in a mutual block, the interface header gets elaborated on the first pass, and method types get elaborated on the second pass. Given that the first pass does function types, and the type of `bar` references `MyInterface`, you'll need to define this as follows:

    interface MyInterface a where
      foo : a -> b
      foo = bar

    bar : MyInterface a => a -> b
    bar = ?bar_rhs

Rather than the other way around.

I think I see why I didn't include interfaces in mutual blocks - it's a bit tricky to decide what to do on each pass without possibly introducing a third pass. There's the interface type, then the method types, and potential dependencies between method types. Given the potential dependencies between method types, I've chosen to do them on the second pass only.

Assuming my patch doesn't break anything, I'll push it shortly.
