### ISSUE TITLE
Type Checking Not Terminating

### ISSUE THREAD

**Issue by kaminsod** [idris-lang/Idris-dev#3191]
Type checking for the following code does not seem to terminate. Memory and CPU usage goes up to 100% after a short while. The same behavior is in the 0.11.2 release as well as 0.11.2-git:bf108b6. Seems to be related to #3077. 

```idris
module Main

data B t = B1 t
data A t = A1 t | A2 (A (B t))

implementation Show t => Show (B t) where
    show (B1 t) = "B1(" ++ show t ++ ")"

implementation Show t => Show (A t) where
    show (A1 t) = "A1(" ++ show t ++ ")"
    show (A2 t) = "A2(" ++ show t ++ ")"

main : IO ()
main = putStrLn (show (A1 1))
```

**Comment by ahmadsalim** [comment]
Yeah, from the log it seems it is going into an infinite loop.

**Comment by edwinb** [comment]
This turns out to be because the elaborator is trying too hard to come up with optimised implementations of 'show', specialised for A and B. Since they're nested, it's making quite a lot of these, and isn't going to stop unless it notices...

I'll tweak the partial evaluator so that it doesn't go so deep in such cases.

It's not the same thing as #3077 - this was to do with things reducing too much.
