### ISSUE TITLE
Temporary Heaps

### ISSUE THREAD

**Issue by foliot** [idris-lang/Idris-dev#3195]
From time to time, developers must engage in messy activities that lead to excessive garbage collection and potentially latency spikes in their applications. Thread-local heaps and garbage collection are awesome and should help the situation a lot, but it would also be nice to empower the developer further. Temporary heaps might be an effecive way to do this. Forgive my poor Idris/Haskell in the description below. 

A developer would use a temporary heap to perform an operation using:
```
copy : Lazy a -> a
```
The argument would be evaluated synchronously, but use a temporary heap that is destroyed after the evaluation is complete. The result is copied into the original heap before the temporary heap is destroyed, hence the function is named "copy". If a developer knows an operation will produce a lot of garbage, it can be isolated and possibly garbage collected by simply freeing a pointer. 

Similar to this idea is the "discard" function, which is more about asynchronous tasks than temporary heaps. 
```
discard : Lazy a -> ()
```
The argument could be evaluated in a background thread, since the original thread doesn't care about the result.

**Comment by david-christiansen** [comment]
Thanks for the suggestion! It does sound like it would be a useful feature.

I don't think that these kind of open-ended feature requests are a good use of the issue tracker, because many more of them arrive than we can reasonably implement, and the actual bugs we need to track become harder to find when there's a lot of other things.

If you'd like to implement something like this, then a note to the mailing list would be a good first step.
