### ISSUE TITLE
foldr1 and foldl1 in Foldable

### ISSUE THREAD

**Issue by zmactep** [idris-lang/Idris-dev#3220]
It seems be useful if any `Foldable t` would have `fodlr1` and `foldl1` functions like in Haskell. Also I miss scans for `List` type. I am ready to implement this.

**Comment by gpyh** [comment]
For this to make sense, `Foldable` should expose a datatype holding a proof that the foldable is not empty. IMHO this is undesirable because:

1. It makes the interface more complicated than strictly needed. Most of the times you have a neutral element for your fold ; just use this as the initial value of the accumulator to reach the same effect.
2. Say you want to implement `Foldable` on a custom data structure? What if the emptiness of said data structure is undecidable? I don't know if it could happen but that's something that should be answered before committing to this.
3. In order to actually use the datatype (as a proposition of non-emptiness) you may need to leak the implementation, which would defeat the purpose of the interface. Code that would happily typecheck with an instance (because non-emptiness can be easily proven) could fail for another.

If you really need to be polymorphic on `Foldable` and if you don't have a neutral element for your fold operation, I invite you to create a new interface constrained by `Foldable`, expose it, and provide implementations for common folds. Nobody knows yet what is or is not a good idea when writing software in dependently typed languages, so I'd be happy to be proven wrong.

**Comment by ahmadsalim** [comment]
@zmactep I would think that functions would be accepted in `contrib`. Perhaps the `fold*1` can be implemented in a superclass of `Foldable` (named `Foldable1` or similar) there.

**Comment by ahmadsalim** [comment]
I will close this since no PR came.
