### ISSUE TITLE
What am I doing wrong? Are interfaces broken? Is this a regression?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3234]
The program

```
> import Syntax.PreorderReasoning

> %default total
> %access public export
> %auto_implicits on

> interface (Num t) => NumMultZeroOne t where
>   multZeroRightZero   : (x : t) -> x * 0 = 0
>   multZeroLeftZero    : (x : t) -> 0 * x = 0
>   multOneRightNeutral : (x : t) -> x * 1 = x
>   multOneLeftNeutral  : (x : t) -> 1 * x = x

> cross : (a -> c) -> (b -> d) -> (a, b) -> (c, d)
> cross f g (x, y) = (f x, g y)

> sumMapSnd : {A, B : Type} -> (Num B) => List (A, B) -> B
> sumMapSnd abs = sum (map snd abs) 

> mapIdRightMult : {A, B : Type} -> (Num B) => (List (A, B), B) -> List (A, B)
> mapIdRightMult (abs, b) = map (cross id (* b)) abs

> mapIdRightMultLemma : {A, B : Type} -> (NumMultZeroOne B) => 
>                       (absb : (List (A, B), B)) -> 
>                       sumMapSnd (mapIdRightMult absb)
>                       =
>                       (sumMapSnd (fst absb)) * (snd absb)
> mapIdRightMultLemma (Nil, b) = 
>     ( sumMapSnd (mapIdRightMult (Nil, b)) )
>   ={ Refl }=
>     ( sumMapSnd (map (cross id (* b)) Nil) )
>   ={ Refl }=
>     ( sumMapSnd Nil )
>   ={ Refl }=
>     ( 0 )
>   ={ ?kuku }= 
>   -- ={ sym (multZeroLeftZero b) }=
>     ( 0 * b )
>   ={ Refl }=     
>     ( (sumMapSnd Nil) * b )
>   ={ Refl }=     
>     ( (sumMapSnd (fst (Nil, b))) * (snd (Nil, b)) )   
>   QED
> mapIdRightMultLemma ((ab :: abs), b) = ?lala
```

type checks fine. But replacing lines 35-36

```
>   ={ ?kuku }= 
>   -- ={ sym (multZeroLeftZero b) }=
```

with

```
>   -- ={ ?kuku }= 
>   ={ sym (multZeroLeftZero b) }=
```

yields

```
- + Errors (1)
 `-- 3223_cant_infer.lidr line 27 col 20:
     Can't infer argument A to sumMapSnd, 
     Can't infer argument A to mapIdRightMult, 
     Can't infer argument A to Pair, 
     Can't infer argument A to sumMapSnd, 
     Can't infer argument A to Pair, 
     Can't infer argument A to cross, 
     Can't infer argument A to id, 
     Can't infer argument A to sumMapSnd, 
     Can't infer argument A to Pair, 
     Can't infer argument A to sumMapSnd, 
     Can't infer argument A to Pair, 
     Can't infer argument A to sumMapSnd, 
     Can't infer argument A to Pair, 
     Can't infer argument elem to List, 
     Can't infer argument elem to []
```

What is going on here? Is there something broken with interfaces? Is this a regression? Am I doing something wrong?

**Comment by TimRichter** [comment]
Hi Nicola,
after filling in implicits like so

    > mapIdRightMultLemma {A} {B} (Nil, b) = 
    >     ( sumMapSnd {A} (mapIdRightMult (Nil, b)) )
    >   ={ Refl }=
    >     ( sumMapSnd {A} (map (cross id (* b)) Nil) )
    >   ={ Refl }=
    >     ( sumMapSnd {A} Nil )
    >   ={ Refl }=
    >     ( 0 )
    >   -- ={ ?kuku }= 
    >   ={ sym (multZeroLeftZero b) }=
    >     ( 0 * b )
    >   ={ Refl }=     
    >     ( (sumMapSnd {A} Nil) * b )
    >   ={ Refl }=     
    >     ( (sumMapSnd {A} (fst (Nil, b))) * (snd {a=List(A,B)} (Nil, b)) )   
    >   QED

it typechecks, but you probably knew this... 
Did you check with older Idris versions?

Best,
Tim

**Comment by nicolabotta** [comment]
> but you probably knew this... 

No, I have not tried filling in implict arguments explicitly. The point here is that the original program (with ` ={ sym (multZeroLeftZero b) }=` commented out) type checks fine!

I would expect that attempts at implementing `kuku` can result in errors. But I certainly do not expect a raw of  `Can't infer argument` as the one reported above. Notice also that
```
> import Syntax.PreorderReasoning

> %default total
> %access public export
> %auto_implicits on

> interface (Num t) => NumMultZeroOne t where
>   multZeroRightZero   : (x : t) -> x * 0 = 0
>   multZeroLeftZero    : (x : t) -> 0 * x = 0
>   multOneRightNeutral : (x : t) -> x * 1 = x
>   multOneLeftNeutral  : (x : t) -> 1 * x = x

> interface (NumMultZeroOne t) => NumMultDistributesOverPlus t where
>   multDistributesOverPlusRight : (x, y, z : t) -> x * (y + z) = (x * y) + (x * z)
>   multDistributesOverPlusLeft  : (x, y, z : t) -> (x + y) * z = (x * z) + (y * z)

> cross : (a -> c) -> (b -> d) -> (a, b) -> (c, d)
> cross f g (x, y) = (f x, g y)

> sumMapSnd : {A, B : Type} -> (Num B) => List (A, B) -> B
> sumMapSnd abs = sum (map snd abs) 

> mapIdRightMult : {A, B : Type} -> (Num B) => (List (A, B), B) -> List (A, B)
> mapIdRightMult (abs, b) = map (cross id (* b)) abs

> sumMapSndMapIdRightMultLemma : {A, B : Type} -> (Num B) => 
>                                (b : B) -> (ab : (A, B)) -> (abs : List (A, B)) -> 
>                                (snd ab) * b + sumMapSnd (mapIdRightMult (abs, b)) 
>                                = 
>                                sumMapSnd (mapIdRightMult ((ab :: abs), b))

> mapIdRightMultLemma : {A, B : Type} -> (NumMultDistributesOverPlus B) => 
>                       (absb : (List (A, B), B)) -> 
>                       sumMapSnd (mapIdRightMult absb)
>                       =
>                       (sumMapSnd (fst absb)) * (snd absb)
> mapIdRightMultLemma {A} {B} (Nil, b) = 
>     ( sumMapSnd (mapIdRightMult (Nil, b)) )
>   ={ Refl }=
>     ( sumMapSnd (map (cross id (* b)) Nil) )
>   ={ Refl }=
>     ( sumMapSnd Nil )
>   ={ Refl }=
>     ( 0 )
>   ={ ?kuku }= 
>   -- ={ sym (multZeroLeftZero b) }=
>     ( 0 * b )
>   ={ Refl }=     
>     ( (sumMapSnd Nil) * b )
>   ={ Refl }=     
>     ( (sumMapSnd (fst (Nil, b))) * (snd (Nil, b)) )   
>   QED
> mapIdRightMultLemma ((ab :: abs), b) = 
>     ( sumMapSnd (mapIdRightMult ((ab :: abs), b)) )
>   ={ sym (sumMapSndMapIdRightMultLemma b ab abs) }=
>     ( (snd ab) * b + sumMapSnd (mapIdRightMult (abs, b)) )
>   ={ cong (mapIdRightMultLemma (abs, b)) }=
>     ( (snd ab) * b + (sumMapSnd (fst (abs, b))) * (snd (abs, b)) )
>   ={ Refl }=
>     ( (snd ab) * b + (sumMapSnd abs) * b )
>   ={ sym (multDistributesOverPlusLeft (snd ab) (sumMapSnd abs) b) }=  
>     ( (snd ab + sumMapSnd abs) * b )
>   ={ Refl }=
>     ( (snd ab + sum (map snd abs)) * b )
>   ={ Refl }=
>     ( (sumMapSnd (ab :: abs)) * b )
>   ={ Refl }=
>     ( (sumMapSnd (fst ((ab :: abs), b))) * (snd ((ab :: abs), b)) )
>   QED
```
type checks fine.

**Comment by nicolabotta** [comment]
> Did you check with older Idris versions?

No, I just have the impression that `Can't infer` and `Can't disambiguate` errors appear more frequently lately. I might be wrong, of course.

**Comment by TimRichter** [comment]
> No, I have not tried filling in implict arguments explicitly. The point here is that the original program 
> (with ={ sym (multZeroLeftZero b) }= commented out) type checks fine!
>
> I would expect that attempts at implementing kuku can result in errors. But I certainly do not expect a 
> raw of Can't infer argument as the one reported above. 

Sure. 
What about the type of kuku?:

    *test> :t kuku
      A : Type
      B : Type
      b : B
      constraint : NumMultZeroOne B
      A1 : Type
      A2 : Type
      A3 : Type
      y : B
    --------------------------------------
    kuku : fromInteger 0 = fromInteger 0 * b
    Holes: Main.lala, Main.kuku

How do A1, A2, A3 and y get into the context?

**Comment by nicolabotta** [comment]
> How do A1, A2, A3 and y get into the context?

I do not  know. Not because of `%auto_implicits on` anyway. One can turn auto implicits off and the premises of `kuku` are still the same. What is also strange is that the totality checker does not seem to believe that `mapIdRightMultLemma` is total.

**Comment by edwinb** [comment]
I'm quite sure interfaces are not "broken" because I use them a lot and we have some (not yet finished) work on better abstraction capabilities via interfaces on the go, of which more later. 

I did, however, change the implementation of interfaces recently and there may be some corners to tidy up. I'll take a closer look at this when I next have some proper time for Idris maintenance.

**Comment by edwinb** [comment]
Okay, I took a quick look at this, and I believe Idris is behaving correctly:

* When there are holes, Idris is more liberal about missing implicits, because in general it is possible that resolving a hole will resolve those missing implicits, and it's more useful to be able to see the type of the hole in these cases. This is the reason for the `A1`, `A2` etc here in the context of `kuku`.

* The reason for the "Can't infer" errors is that you have a lot of `Nil`s about, as arguments to functions with generic types, and there's nothing the elaborator can use to help unify the arguments to these `Nil`s. Note in particular that during reasoning, `sumMapSnd` returns a `B`, and can only get the type of its `A` argument by looking at the type of the list you give it, and all it has to go on there is `Nil`. This is why Tim's suggestion of filling in the implicits makes the program type check. I solved it similarly by being explicit with `Nil {elem = (A, B)}`.

* The checker does believe `mapIdRightMultLemma` is total. When there's another error, it reports that it isn't yet checked for totality when tested with `:total`.

None of this has anything to do with interfaces.

**Comment by nicolabotta** [comment]
@edwinb I agree that the behavior has nothing to do with interfaces, I'm sorry for the stupid title! I think that I understand remarks 1 and 3 but I am not convinced about 2. The program
```
> mapIdRightMultLemma : {A, B : Type} -> (NumMultDistributesOverPlus B) => 
>                       (absb : (List (A, B), B)) -> 
>                       sumMapSnd (mapIdRightMult absb)
>                       =
>                       (sumMapSnd (fst absb)) * (snd absb)
> mapIdRightMultLemma {A} {B} (Nil, b) = 
>     ( sumMapSnd (mapIdRightMult (Nil, b)) )
>   ={ ?kuku }= 
>     ( (sumMapSnd (fst (Nil, b))) * (snd (Nil, b)) )   
>   QED
> mapIdRightMultLemma {A} {B} ((ab :: abs), b) = 
>     ( sumMapSnd (mapIdRightMult ((ab :: abs), b)) )
>   ={ ?koko }=  
>     ( (sumMapSnd (fst ((ab :: abs), b))) * (snd ((ab :: abs), b)) )
>   QED
```
type checks fine but we still have one more implicit argument in `kuku` than in `koko`. I would expect here the type of `Nil` in the base case to be as determined as the type of `ab :: abs` in the cons case. Both can only be lists of elements of type `(A, B)`, I think.

**Comment by edwinb** [comment]
`koko` has more to go on than `kuku`, because it has a list with actual contents, `ab :: abs`. If there's a `Nil` there needs to be some context to disambiguate it, and there isn't, because the type of `sumMapSnd` doesn't give enough information.

It can only be lists of elements of type `(A, B)` I agree, but Idris doesn't have enough to work that out by unification.

**Comment by nicolabotta** [comment]
> It can only be lists of elements of type (A, B) I agree, but Idris doesn't have enough to work that out by unification.

Was it always like that? I was under the impression that the type of the arguments of a function is determined by the function's signature. And `(Nil, b)` in
```
>     ( sumMapSnd (mapIdRightMult (Nil, b)) )
```
has to be the explicit argument of `mapIdRightMultLemma`, I believe.

**Comment by edwinb** [comment]
What is the implicit argument to `Nil` here, and why?

Here's more or less the process Idris follows, at least as far as I see it in this example:

`sumMapSnd`'s (explicit) argument type is:

* `List (A, B)`

So, `mapIdRightMult (Nil, b)` must have type `List (A, B)`.

`mapIdRightMult`'s return type is `List (A, B)`. Great. Its (explicit) argument type is:

* `(List (A, B), B)`

So, the question is, does `(Nil, b)` have a type which fits `(List (A, B), B)` and if so, what do we instantiate `A` and `B` with? We have:

* `Nil` which must have type `List (A, B)`. This is fine, but tells us nothing about what to instantiate `A` and `B` with.
* `b` which must have type `B`.  We know the type of `b`, because it's a local variable, so that tells us how to instantiate `B`.

So we've got enough to establish what `B` is in this call (to `sumMapSnd`), but not enough to establish what `A` is. We'll have to hope to get it from something else.

Perhaps we could get it from the preorder reasoning itself. But the left hand side of the reasoning only has type `B`. The `A` in the call to `sumMapSnd` is independent of everything else, so there's really nothing Idris can do other than guess.

**Comment by edwinb** [comment]
P.S. As further evidence that unification should not be expected to find an answer, I actually tried instantiating `A` with any old rubbish (`Int`, `Nat`, `B`), and it type checks fine in each case, as it should. If there's more than one possibility, we really don't want Idris just putting in any old thing.

**Comment by nicolabotta** [comment]
Edwin, thanks for the detailed explanations! I am probably too dumb to get the point: my understanding is that the answer to the question

- does (Nil, b) have a type which fits (List (A, B), B) ?

is yes: the type of `Nil` is `List (A, B)` and the type of `b` is `B`. But I do not understand what you mean by

- what do we instantiate A and B with?

in this context. I would expect the problem of instantiating `A` and `B` to arise in programs that use `mapIdRightMultLemma`, not here. Here we are implementing `mapIdRightMultLemma` and there are no recursive calls. How could we instantiate `A` and `B` in any meaningful way? Anyway, I found
```
- + Errors (1)
 `-- 3223_cant_infer.lidr line 27 col 20:
     Can't infer argument A to sumMapSnd, 
     Can't infer argument A to mapIdRightMult, 
     Can't infer argument A to Pair, 
     Can't infer argument A to sumMapSnd, 
     Can't infer argument A to Pair, 
     Can't infer argument A to cross, 
     Can't infer argument A to id, 
     Can't infer argument A to sumMapSnd, 
     Can't infer argument A to Pair, 
     Can't infer argument A to sumMapSnd, 
     Can't infer argument A to Pair, 
     Can't infer argument A to sumMapSnd, 
     Can't infer argument A to Pair, 
     Can't infer argument elem to List, 
     Can't infer argument elem to []
```
upon replacing
```
>   ={ ?kuku }= 
```
with
```
>   ={ sym (multZeroLeftZero b) }=
```
in the original example very confusing. But if this is in fact the expected behavior, please close this issue.

**Comment by ahmadsalim** [comment]
I will close the issue since there has been no objection and it seems that there has been not much activity. @nicolabotta If you still think it's a major issue, please reopen it.
