### ISSUE TITLE
exit code from System.system is wrong

### ISSUE THREAD

**Issue by alrunner4** [idris-lang/Idris-dev#3251]
```
> :exec system "exit 1" >>= printLn
256
```

**Comment by Melvar** [comment]
Well, `system` returns a wait status, not an exit code. Looking at the definition on my current system a recent Linux system, the exit code happens to be the second-lowest byte of the status, so `256` is, indeed a status containing an exit code of `1` (and additionally indicating termination not by a signal). Unless your wait status macros are defined differently, this is expected behavior.

**Comment by steshaw** [comment]
@Melvar, there was no need to look into this. As I mentioned on #idris, I was taking a look at it. I've added a test case to reproduce the issue. I do agree that it's unfortunately expected behaviour. However, I've expanded the test case to show how to bind `WIFEXITED` and `WEXITSTATUS` macros with Idris FFI. @alrunner4 could copy these into their project if they wish. Perhaps better would be to incorporate access to various such macros into a prelude. However, there is a question of portability...

**Comment by alrunner4** [comment]
Ah, that explains it. Since the macros are POSIX-defined, perhaps it's best they live in idris-posix? It does seem a bit odd to have a function in the Prelude that returns an implementation-defined Int, though.

@steshaw, where is this expanded test case?

**Comment by steshaw** [comment]
@alrunner4 [take a look here](https://github.com/idris-lang/Idris-dev/pull/3281/files)

**Comment by alrunner4** [comment]
Thanks! I'll work around for now. A while back I'd considered pitching in some things to idris-posix (it's pretty slim currently) but I've yet to come into a chunk of time to get much of anything done with it.
