### ISSUE TITLE
Infinite loop on erroneous type definition

### ISSUE THREAD

**Issue by krobelus** [idris-lang/Idris-dev#3261]
While trying to learn idris I discovered that this data definition would crash the compiler
(it looks like an infinite loop as the cpu usage goes to 100% and there is no output)
I am using the dev version, commit 45bf2b648d5a082a2c4494e954af3079dcd23be0

``` idris
data Point : Num t => Nat -> t -> Type where
   Nil : Point Z t
```

Btw if someone could point out to me how to correctly  define Point here (using Nil and ::) so that it only accepts Num types that would be nice ;)

**Comment by enolan** [comment]
I can confirm the bug.

If you want a type of points indexed by their dimension, this is it:

```idris
data Point : Nat -> t -> Type where
  Nil : Point Z t
  (::) : Num t => t -> Point n t -> Point (S n) t
```
Putting the `Num` constraint on the cons constructor instead of `Point` means you can write `Point 2 String` but can't ever make a term of that type without writing an implementation for `Num String`. What you wrote prevents the construction of the *type*, my version prevents the construction of *inhabitants of the type*. I don't know why what you wrote hangs the compiler, but it isn't what you want.

If you'd like to discuss this further, let's keep it off the bug tracker and use the mailing list instead.

**Comment by ahmadsalim** [comment]
From @comco:

```idris
-- typechecks
data Mono1 : (Monoid m) => Type where
  Monono1 : (Monoid m) => Mono1 {m}

-- typechecks
data Mono2 : (m : Type) -> Monoid m => () -> Type where
  Monono2 : (Monoid m) => Mono2 m ()

-- PROBLEM: typechecking diverges -- compilation doesn't terminate
data Mono : (Monoid m) => () -> Type where
  Monono : (Monoid m) => Mono {m} ()
```
