### ISSUE TITLE
Lazy and implementation resolution

### ISSUE THREAD

**Issue by BartAdv** [idris-lang/Idris-dev#3330]
```idris
foo : Eq a => Lazy a -> a -> Bool
foo x y = x == y
```

```
      When checking right hand side of foo with expected type
             Bool
     
     Can't find implementation for Eq (Lazy a)
```

Is it by design, or should it unwrap Lazy before finding an implementation?

**Comment by edwinb** [comment]
I'd expect to need an explicit 'Force' here, just because the implicit 'Force' is inserted when there'd otherwise be a type mismatch error, and it isn't a type mismatch error here. There could, in theory, turn out to be an instance which works differently for 'Lazy' and the elaborator doesn't backtrack to reinsert any missing 'Force' if there turns out not to be an instance.

There might be some cleverness that the elaborator could do to solve this, but I'd be a bit scared of introducing too much backtracking. So this is expected behaviour, but I'll leave the issue open for the moment since there's a few things that could be worth a try.

**Comment by BartAdv** [comment]
By the way - how to use this explicit 'Force' in this case?

```idris
foo : (Force x) y = x == y
```
gives
```
     When checking left hand side of foo:
     Attempting concrete match on polymorphic argument: Force x
```

**Comment by ahmadsalim** [comment]
@BartAdv You should do the following

```idris
foo : Eq a => Lazy a -> a -> Bool
foo x y = Force x == y
```

**Comment by ahmadsalim** [comment]
@BartAdv Can we consider your issue resolved?

**Comment by BartAdv** [comment]
@ahmadsalim Yes!
