### ISSUE TITLE
Can't case over empty types

### ISSUE THREAD

**Issue by taralx** [idris-lang/Idris-dev#337]
When r is of an empty type (e.g. LTE (S n) O), you can't case over it. "case r of {}" is a parse error.

**Comment by jfdm** [comment]
I am marking this as 'Awaiting More Information' under the proviso that we are waiting for the Design Decision to be made.

**Comment by edwinb** [comment]
"Awaiting More Information" is intended to mean we need the reporter to 
provide more details. Here, we just need to get on with making a 
decision (or just do it...).

**Comment by jfdm** [comment]
Ah okay. I'll make a not of that difference for future.

**Comment by david-christiansen** [comment]
Didn't we come to a conclusion on IRC that this is fine if someone wants to do it, but that we aren't going to bother?

The elaboration story for empty case expressions over constructorless types is a bit involved, actually, because every definition is supposed to have a clause, and we have the "same family" check for impossible clauses. We would need to generate an eliminator, probably.

**Comment by edwinb** [comment]
If someone wants to do this, they're welcome to add it, but I'm not going to leave the issue open...
