### ISSUE TITLE
Remove dependency on network

### ISSUE THREAD

**Issue by polkovnikov-ph** [idris-lang/Idris-dev#3378]
Idris installation fails on Windows due to dependency on `network` package which is known to be a developers' pain for years. I don't see why it is required by a programming language at all. Could we get rid of this dependency?

UPD. Here's a [response](https://github.com/haskell/network/issues/89) from 2013.

**Comment by david-christiansen** [comment]
Idris uses sockets to communicate with development tools.

In any case, there are binary packages for Windows, and the Appveyor CI script should serve as a guide for installing dependencies and the like.

**Comment by melted** [comment]
You're gonna need network for other stuff, so that wouldn't be a solution for long. 

This is an issue with the cabal that is bundled with GHC, you can read all about it here https://github.com/haskell/cabal/issues/3689. There are five workarounds, 1) install from cabal git, 2) rename your GHC directory(!), 3) install using stack. 4) install using an earlier GHC, 5) install network not with cabal install, but with cabal unpack, configure, build, copy, register...

**Comment by polkovnikov-ph** [comment]
@melted I need an Idris REPL to try it. I'm not happy jumping through the hoops to get it. Should I rename the issue to "Provide binary releases" to get it reopened?

**Comment by david-christiansen** [comment]
There are binary releases of Idris for Windows, linked to from http://www.idris-lang.org/download/

**Comment by polkovnikov-ph** [comment]
@david-christiansen Website was down several minutes ago from Europe and Asia, I've thought it's not operating. Thanks.
