### ISSUE TITLE
+ operator used in type signature not commutative in unification

### ISSUE THREAD

**Issue by owickstrom** [idris-lang/Idris-dev#3480]
So, I've reduced a program based on `Vect` to this example where using `(l + 1)` in the type signature does not unify with the type of the body expression, where I thought it would. It seems the `+` operator on `Nat` is not commutative in unification.

**A small warning:** I started hacking with Idris just this week. I have tried to find a similar report among the other issues, with no luck, so I'll give this a shot.

The program looks like this:

```
module Main

import Data.Vect

prepend : (elem : t) -> Vect l t -> Vect (l + 1) t
prepend x xs = [x] ++ xs
```

When loading this in the REPL, I get:

```
     When checking right hand side of prepend with expected type
             Vect (l + 1) t
     
     Type mismatch between
             Vect (1 + l) t (Type of [x] ++ xs)
     and
             Vect (plus l 1) t (Expected type)
     
     Specifically:
             Type mismatch between
                     plus 1 l
             and
                     plus l 1
```

If I flip `(l + 1)` in the type signature to `(1 + l)` it type checks properly. I expect `plus 1 l` and `plus l 1` to unify as well.

**Comment by gpyh** [comment]
*Short explanation because I'm on the phone*

The unification is just a syntactic process. As the plus function is recursive on the first argument, it will never be able to match the two expressions if you don't put the arguments that get deconstructed in the same place.
You figured how to solve this ;  if you wanted to juste make a local change to the code,  you coud have used the "rewrite" keywoard which changes the type of an expressing according to some proof functon (here, the suitable function is "plusCommutative") available in Prelude. 

So, this is not a bug. Just a reminder that computers are dumb and that we need to spell it all for them. Making this process automatic is, as far as I know, not trivial at all.

**Comment by david-christiansen** [comment]
As @gpyh said, addition on Nat is only _propositionally_ commutative. This means that it has to be proved via induction and the proof object then used to rewrite in the necessary context.

**Comment by owickstrom** [comment]
I see. Thank you both for explaining it so well, and sorry for posting this as a bug. I should have probably gone through the mailing list or IRC first.

**Comment by david-christiansen** [comment]
No worries :-)
