### ISSUE TITLE
Chocolatey Idris package

### ISSUE THREAD

**Issue by userzimmermann** [idris-lang/Idris-dev#3484]
Hi :) I'm new to Idris and created a Chocolatey package for the Windows distribution:

https://github.com/userzimmermann/choco-packages/tree/master/idris

I would like to upload it to chocolatey.org. I already maintain the msys2 package there. Are there any complains?

Kind regards,
Stefan

**Comment by melted** [comment]
Sounds good to me!

**Comment by userzimmermann** [comment]
1 positive. 0 negative. So I will just upload it :) Can be reverted later ;)

**Comment by userzimmermann** [comment]
https://chocolatey.org/packages/idris got approved :)

**Comment by jfdm** [comment]
Sorry was on annual leave. The only word of caution I have with this is: are you willing to maintain the chocolatey package? To me, this package is a distribution of idris not maintained by those that develop idris. If there are problems with a deployed version of idris installed using chocolatey that is not idris' fault, user's may complain to us about it rather than yourself. As long as people are aware that they should complain to the package maintainer first about installation issues, and then to use about idris related issues.
