### ISSUE TITLE
System.usleep is a no-op if argument is >= 1000000

### ISSUE THREAD

**Issue by harveywi** [idris-lang/Idris-dev#3505]
Idris version:  0.12.2

I ran into this bug using the Windows 64-bit binary on Windows 7 Enterprise.  If you call `System.usleep` with an argument >= `1000000`, then no sleeping actually happens.  This appears to be related to the specification of the `usleep` method in unistd.h ([link to documentation](http://pubs.opengroup.org/onlinepubs/007908799/xsh/usleep.html)).  Specifically:

>  The useconds argument must be less than 1,000,000. If the value of useconds is 0, then the call has no effect. 

I have only tried this on Windows.  Behavior may be different on Linux/Mac.

Maybe the Idris `usleep` method could be tightened up a bit to avoid this unexpected behavior...but I am sure there are good arguments either way.

**Comment by harveywi** [comment]
From various online Linux man pages ([here](http://man7.org/linux/man-pages/man3/usleep.3.html)) and ([here](http://man7.org/linux/man-pages/man3/usleep.3.html)), it looks like the C `usleep` function will report an `EINVAL` error on some systems when given a value >= `1000000`, whereas other systems may do just fine and carry on without issue.

**Comment by jfdm** [comment]
@harveywi Thanks for the issue and exploration to why it occurs. I think the two ways you have hinted at to address it are both viable: tighten up the `usleep` method in the Prelude, or tighten up the call itself through a wrapper.

For the former one could argue that we should either: provide an auto implicit bound on the value to sleep such that it falls in the range `(0,1 000 000]`; or return the result of `usleep` so that an error can be passed to the user. Both ways have merit and I am not sure (at the moment) which one is preferred.

**Comment by jfdm** [comment]
I forgot to add, if you need help with doing this then please do ask! or if you are not comfortable then say. 

Whilst we welcome new contributors of all abilities, we don't expect them to paint the sistine chapel after their first viewing of 'the joy of painting'.

**Comment by harveywi** [comment]
@jfdm Thanks for the feedback, much appreciated.  One of the exercises in Edwin's book is affected by this issue (that's how I stumbled upon it), so he may provide some guidance on how, if at all, to address it, since the fix must mirror whatever goes into the book.

I'm pleasantly surprised to be nominated to fix it!  We will see how that goes - I probably will not have time to dive in for several weeks (busy with several work deadlines), so feel free to carry the torch if that is too large a timeline (especially relative to the deadline for Edwin's book).
