### ISSUE TITLE
length [] -> Can't infer argument a to []

### ISSUE THREAD

**Issue by 81120** [idris-lang/Idris-dev#3518]
## Freshman Question
when using length like that 
```
length []  
```
it will be 
```
Can't infer argument a to []
```
Why can't get a 0?

**Comment by david-christiansen** [comment]
Hi Leo,

> ## Question
> when using length like that 
> ```
> length []  
> ```
> it will be 
> ```
> Can't infer argument a to []
> ```
> Why can't get a 0?

The reason is that, behind the scenes, Idris needs to be able to fully
determine the types used for each constructor, even if there's no
arguments that actually have those types.

In other words, the definition of List looks like this:

data List : Type -> Type where
  Nil : List a
  (::) : a -> List a -> List a

but it actually has hidden arguments that pass the types around, like this:

data List : Type -> Type where
  Nil : {a : Type} -> List a
  (::) : {a : Type} -> a -> List a -> List a

Also, length needs to have these types plumbed around:

length : {a : Type} -> List a -> Nat
length {a} (Nil {a}) = Z
length {a} ((::) {a} x xs) = S (length {a} xs)

When Idris sees [], it expands it to the name Nil. Having this
information around is necessary when it comes time to combine programs
with each other, and not just consider expressions in isolation, so we
can't just erase it either, at least not until we finally compile the
program to an executable.

The "Can't infer argument a" message is saying that it can't find that
hidden argument that tells us what type of list it is.

/David

**Comment by 81120** [comment]
Hi, @david-christiansen , thanks for your working, pretty careful.  I am trying to understand, and I have two questions now :).
1.  When define a function like that:
```
myLength List a -> Int
myLength [] = 0
myLength (x :: xs) = 1 + myLength xs
```
and when using
```
myLength [1..10] 
```
I can get 10.  But when using
```
myLength []
```
I will get
```
Can't infer argument a to []
```
It is a recursive process which ends up with []. That is to say, in the recursive process, myLength [] will be computed normally. But when using myLength [] independently, there is a different result, why?
2. How to deal with the [] when using `f : List a -> b`?

**Comment by ahmadsalim** [comment]
@81120 You can use something like `myLength {a = ()} []` which explicitly fills out the implicit `a` parameter with the unit type `()` or `myLength (the (List ()) [])` which fills it out by unification.
Here `the` is a function which takes a type as a first argument and a value of that type as a second argument, and thus allows you to "annotate" the types of intermediate values which type is not fully known.

**Comment by 81120** [comment]
@ahmadsalim , Thanks, got it.

**Comment by ahmadsalim** [comment]
I will close the issue then if it's OK.
