### ISSUE TITLE
Generalize Vect functions for Foldable

### ISSUE THREAD

**Issue by jachymb** [idris-lang/Idris-dev#3520]
For example, we have

```
elemBy : (p : elem -> elem -> Bool) -> (e : elem) -> (xs : Vect len elem) -> Bool
elemBy p e []      = False
elemBy p e (x::xs) = p e x || elemBy p e xs
```

Why not generalize like this:
```
elemBy : Foldable f => (elem -> elem' -> Bool) -> (elem) -> (f elem') -> Bool
elemBy = (any .)
```

Then of course
```
elem : (Foldable f, Eq elem) => elem -> (f elem) -> Bool
elem = elemBy (==)
```

And similarly for many other functions in `Data.Vect`. But maybe there is a good reason to have it like it is that I don't know.

**Comment by ahmadsalim** [comment]
@jachymb You are more than welcome to make a PR with these generalizations if they type check. The most likely reason is just that people have not thought about it, since Idris is strict and so for most functions it usually doesn't matter whether you explicitly pattern match or not.

**Comment by jachymb** [comment]
Although I personally prefer the point-free style here, the reason for this is not really getting rid of pattern matching, but making the function more polymorphic.

**Comment by bamboo** [comment]
Please correct me if I'm wrong but those two `elemBy` definitions are not equivalent performance-wise and might exhibit very different performance characteristics in practice depending on how expensive the `Foldable` implementation is.

The first, specialised definition, will stop iterating as soon as the element matching the predicate is found.

The second, more general definition, will evaluate the whole Foldable range of the data structure. 

That's why I think the specialised versions should be preferred unless a suitable abstraction that can properly handle early termination is used.

**Comment by ahmadsalim** [comment]
@bamboo So as far as I understand we need concrete performance benchmarks to compare.
But, note that Idris does aggressive inlining, erasure and partial evaluation so the performance difference might not be that great.

**Comment by jachymb** [comment]
@bamboo 
Could that be perhaps fixed by switching to `Lazy Bool` on the right place?

**Comment by ahmadsalim** [comment]
@jachymb 
`any` is already Lazy as far as I remember.

**Comment by ahmadsalim** [comment]
In any case using `any` and `all` should not be penalty incurring w.r.t. early stopping.
If it is now, that needs to be changed.

**Comment by ahmadsalim** [comment]
PRs still welcome, but I will close the feature request since there has been no updates for some time.
