### ISSUE TITLE
Possible Coverage Checking Error

### ISSUE THREAD

**Issue by xekoukou** [idris-lang/Idris-dev#3524]
https://gist.github.com/xekoukou/e943ea185bc8007aab89cea7a8a8a188

The problem arises in function ```trLDT``` . 
If I remove the case : 
```
trLDT x (AndC y) = ?error_if_deleted
```
I get this error : 
```
../cov_error.idr:287:1:LinLogic.trLDT is not total as there are missing cases
../cov_error.idr:350:1:LinLogic.indTrLDT is possibly not total due to: LinLogic.trLDT
```

**Comment by ahmadsalim** [comment]
@xekoukou There is definitely an error. You mean that the error is spurious, and why?

**Comment by xekoukou** [comment]
@ahmadsalim 
If you check the type of ```error_if_deleted```, you get this : 

```
  rll : LinLogic
  b : LinLogic
  a : LinLogic
  x : LinDepT (And (Delay a) (Delay b))
  y : LLTr (And (Delay b) (Delay a)) rll
--------------------------------------
error_if_deleted : LinDepT rll
```

If you then look at the definition of LinDepT, the only constructor that gives that datatype is
``` TAnd ```, thus there shouldn't be an error.

I removed all the ```Inf``` in the LinDepT datatype and I get no error, so either I do not understand something, or Inf confuses the coverage checker.

**Comment by edwinb** [comment]
I don't get this error with the new coverage checker.

I do get some other coverage errors though, which is entirely possible since it's an undecidable problem so different algorithms may cause different things not to get through. Perhaps they need a closer look.

**Comment by xekoukou** [comment]
edwinb : 

Keep in mind that I have types that depend on Codata, something that is ill-advised.
If that should not affect the coverage checker, then continue the research into the issue.

**Comment by xekoukou** [comment]
I ll test  the new coverage checker when I finish reading on possible solutions on the normalization of codata.

**Comment by edwinb** [comment]
Codata shouldn't make any difference to the coverage checker.

I'm not working on this at the moment - the initial reported error is certainly no longer there, the question is now whether the reported failures are due to the undecidability of the problem (in which case you'd need an explicit proof) or because something about the new algorithm is not right.

**Comment by xekoukou** [comment]
@edwinb  : 

https://gist.github.com/xekoukou/379ebe5ed443c85e89dbe056d59f683f
(I changed the code a bit. (different version).)

If you look at the second case of trSetLL, you will see that it already exists a few cases further down.

If it is removed, the coverage checker returns a missing case error.

**Comment by xekoukou** [comment]
https://gist.github.com/xekoukou/e5e4ea8b09b723ef558c65b3e98d945e

A simplified version of the previous. Check trSetLL.

**Comment by edwinb** [comment]
In the latest version, this has improved: there are four missing cases, none of which are explicitly matched by the given cases but all of which have some justification for claiming they are covered. Adding these cases makes the checker happy.

The checker works essentially by choosing a pattern to split into cases, adding the missing ones, then seeing if the result type checks. The missing cases it generates will depend on what it chooses to split, so it tries hard to choose something which will rule out as many cases as possible. When there's overlapping patterns, it's much harder to get this right.

Here I suspect if it picked the second argument first it would be fine. But, alas, it doesn't.

I still think I can improve this, but ultimately with this being an undecidable problem in general it's coming down to heuristics now rather than some fundamental underlying problem. I'm not going to let this particular issue get in the way of a  release any more, but I am still going to try to improve it.

By the way, I think the only reason this got past the previous implementation was that the previous implementation had a problem which made it unsound.

**Comment by edwinb** [comment]
Ha. So as it turns out when I peered more closely at the case trees, I had got something wrong in generating the clauses, and this now gets past the checker. It is at the cost of efficiency in some other large cases, but it's not completely disastrous and we can work on that later.

The point about overlapping cases and undecidability still stands, but things should be a bit better now.

(Pending other tests. I may be speaking too soon - things usually go wrong when I do. Fingers crossed.)
