### ISSUE TITLE
Infinite recursion in the idris evaluator

### ISSUE THREAD

**Issue by ubsan** [idris-lang/Idris-dev#3535]
I'm learning from TDD with Idris - very fun language so far 😄! I found this, and someone told me to file a bug report.

Given the code

```
module Main

palindrome : Nat -> String -> Bool
palindrome len s =
  if (length s) <= len then False else
    let str = toLower s
        rstr = reverse str in
        palindromeInner str rstr -- could halve them
where
  palindromeInner : String -> String -> Bool
  palindromeInner s1 s2  = 
    let c1 = strHead s1
        c2 = strHead s2
        t1 = strTail s1
        t2 = strTail s2 in
        if c1 == c2 then palindromeInner t1 t2 else False


main : IO ()
main = putStrLn (show (palindrome 0 "hh"))
```

If I compile the code, or `:exec` in the evaluator, the program prints `False`. If I attempt to call `palindrome 0 "hh"` myself, the interpreter infinitely loops:

```
if intToBool (prim__eqChar (prim__strHead "") (prim__strHead ""))
  then if intToBool (prim__eqChar (prim__strHead (prim__strTail ""))
                                  (prim__strHead (prim__strTail "")))
         then if intToBool (prim__eqChar (prim__strHead (prim__strTail (prim__strTail "")))
                                         (prim__strHead (prim__strTail (prim__strTail ""))))
                then if intToBool (prim__eqChar (prim__strHead (prim__strTail (prim__strTail (prim__strTail ""))))
                                                (prim__strHead (prim__strTail (prim__strTail (prim__strTail "")))))
                       then if intToBool (prim__eqChar (prim__strHead (prim__strTail (prim__strTail (prim__strTail (prim__strTail "")))))
                                                       (prim__strHead (prim__strTail (prim__strTail (prim__strTail (prim__strTail ""))))))
                              then if intToBool (prim__eqChar (prim__strHead (prim__strTail (prim__strTail (prim__strTail (prim__strTail (prim__strTail ""))))))
                                                              (prim__strHead (prim__strTail (prim__strTail (prim__strTail (prim__strTail (prim__strTail "")))))))
                                     then if intToBool (prim__eqChar (prim__strHead (prim__strTail (prim__strTail (prim__strTail (prim__strTail (prim__strTail (prim__strTail "")))))))
                                                                     (prim__strHead (prim__strTail (prim__strTail (prim__strTail (prim__strTail (prim__strTail (prim__strTail ""))))))))

... [continued]
```

**Comment by jfdm** [comment]
Hi @ubsan thanks for the error report. I am wondering if you can tell us the version of Idris you are using. This will help us identify what, if anything, is wrong.

 [One thing to note is that Idris in the REPL behaves differently to compiled Idris](http://idris.readthedocs.io/en/latest/faq/faq.html#evaluation-at-the-repl-doesn-t-behave-as-i-expect-what-s-going-on) whether that is the cause of your trouble *I* do not know but others may.

**Comment by ubsan** [comment]
@jfdm 0.12.3, the latest installable with `brew`.

**Comment by edwinb** [comment]
As we discussed on IRC, this is behaving the way I'd expect (essentially, attempting to normalise a partial thing under an "if" which can't make progress because `strTail ""` gets stuck). However, there are two things which ought to be changed, I think:

* The run-time behaviour of strTail. This currently returns "" for an empty string, which isn't consistent with the compile time behaviour. Either it should crash, or the compile time behaviour should be to return "". There are arguments for either.

* Evaluation at the REPL is exactly the same as evaluation in the type checker, exept that we reduce partial things so that you can try them out easily. One thing that can go wrong as a result is that partial things which are reducing with some unknowns can lead to infinite recursion (`palindromeInner` here doesn't is reducing without knowing `t1` and `t2` because `strTail` couldn't reduce). It may be that it would be safer for the REPL only to reduce partial things in the empty context.

So, while this is expected behaviour, I think we should leave this open so that the expected behaviour can change to something a bit better...

**Comment by ubsan** [comment]
😄
