### ISSUE TITLE
MacOS distribution missing libraries

### ISSUE THREAD

**Issue by machunter** [idris-lang/Idris-dev#3540]
When trying to go through the book I get the following error:

```
Can't find import Data/Vect
```

`idris --listlibs` returns **prelude** only

`idris --info` returns amongst many things:
- **Library Dir:** `/usr/local/share/x86_64-osx-ghc-7.10.3/idris-0.99/libs/`

If I go to that directory I only see a Prelude folder.

**Comment by jfdm** [comment]
Hi @machunter 

Is it possible for you to tell us which version of Idris you are using, and how you obtained it?

There was an issue (#3538) with the macOS/Mac OS X installer we provide via idris-lang.org that was resolved recently. I am wondering if your problem would be resolved by that.

Otherwise, it would be helpful to try and reproduce the error. 

Thanks in advance.

Jan

**Comment by machunter** [comment]
I downloaded the package from the idris web site (http://www.idris-lang.org/pkgs/idris-current.pkg, http://www.idris-lang.org/download/), 
`MD5 (idris-current.pkg) = dd37b58ca997748b997c5c33e0ec4ecc`

The REPL said 0.99
