### ISSUE TITLE
Idris 0.99: type of Type 1

### ISSUE THREAD

**Issue by bach741974** [idris-lang/Idris-dev#3553]
Hello
In REPL `:t Type` works as expected producing `Type 1` but 

If I try `:t Type 1` I get:

```idris
Idris> :t Type 1
builtin:Type mismatch between
        Type (Type of Type)
and
        _ -> _ (Is Type applied to too many arguments?)
Idris>
```

I use win 64 binary distribution of idris 0.99

Maybe it is expected.
Thanks

**Comment by ahmadsalim** [comment]
This is indeed expected behaviour.
Idris has cumulative universes so the type of `Type` (at level n) is `Type` (at level n + 1), however since Idris handles these coercions automatically behind the scenes using an efficient universe constraint solver, they are usually not shown to the user and so any `Type` at any level is just shown as `Type`.

If we kept this behaviour in general, we would have then had `:t Type` return `Type` which is fine since they are at different levels, but I think people complained about the possibility of Russell's paradox (and thus inconsistencies in Idris) and so `:t Type` was special-cased to return `Type 1`, so people would not complain immediately about that.

**Comment by ahmadsalim** [comment]
I do think that this is a bit confusing and perhaps we should use a different notation for this case, so people don't think that it's possible to explicitly fix universe levels.

**Comment by bach741974** [comment]
Thanks for the detail explanation!
