### ISSUE TITLE
Confusing reduced type signatures in REPL

### ISSUE THREAD

**Issue by jachymb** [idris-lang/Idris-dev#3586]
In Prelude.Nat, there is:

````
total multOneLeftNeutral : (right : Nat) -> 1 * right = right
````

However when I ask for the type in REPL, I get:
````
Idris> :t multOneLeftNeutral 
multOneLeftNeutral : (right : Nat) -> 1 * right = right
Idris> multOneLeftNeutral 
multOneLeftNeutral : (right : Nat) -> plus right 0 = right
````

I understand why it is logically valid, however, it is inconsitent behavior and confusing to the user. The first case obtained by :t is obviously preferred. 

Using Idris 0.99.

**Comment by edwinb** [comment]
This is expected behaviour because the first shows the type from the Prelude, as written, and the second normalises it. In the second case, you're not asking for the type, you're asking for multOneLeftNeutral to be evaluated, and as well as evaluating the expression, it evaluates the type. 

It's not inconsistent because :t and evaluation do different things, so the type shouldn't be expected to be displayed the same way.
