### ISSUE TITLE
readFile is inefficient

### ISSUE THREAD

**Issue by SuprDewd** [idris-lang/Idris-dev#3602]
When reading a large file with many lines (size 35M, 2 million lines in my case) using the readFile function, it seems to take forever. Haskell's readFile takes less than a minute with the same file.

For completeness, here is the specific [file](http://mirror.switch.ch/mirror/sagemath/spkg/upstream/database_odlyzko_zeta/database_odlyzko_zeta-20061209.tar.bz2) (.tar.bz2).

This is likely due to the [string concatenation](https://github.com/idris-lang/Idris-dev/blob/0d3d2d66796b172e9933360aee51993a4abc624d/libs/prelude/Prelude/File.idr#L276) that occurs after each line is read, making the function quadratic instead of linear.

**Comment by jfdm** [comment]
Just for clarification, which `readFile` are you talking about.

**Comment by SuprDewd** [comment]
> Just for clarification, which readFile are you talking about.

Are there many? In any case, it's the one I was pointing to in the link in the description: [Prelude.File.readFile](https://github.com/idris-lang/Idris-dev/blob/0d3d2d66796b172e9933360aee51993a4abc624d/libs/prelude/Prelude/File.idr#L260).

**Comment by edwinb** [comment]
I think this is an instance of the general problem that we haven't really thought about the implementation of `String` functions very much, so we just have all the naive implementations in the rts. I suppose it's time we did.

I suspect (without having measured, so I'm probably wrong) that the problem here is that there'll be an allocation for every concatenation.

**Comment by edwinb** [comment]
I have tried a number of ways of making this much faster, and I can get it loading in a few seconds quite easily. However... the reported length that's coming back is wrong. I see it's a binary file, so I'm wondering if there are null bytes in there somewhere. This would explain it, because readFile is intended for text files only, but I suppose I should add some binary file functions as soon as I can.

**Comment by SuprDewd** [comment]
Excerpts from Edwin Brady's message of March 15, 2017 12:33 pm:
> I have tried a number of ways of making this much faster, and I can get it loading in a few seconds quite easily. However... the reported length that's coming back is wrong. I see it's a binary file, so I'm wondering if there are null bytes in there somewhere. This would explain it, because readFile is intended for text files only, but I suppose I should add some binary file functions as soon as I can.
> 

If you extract the file I linked to (which was a .tar.bz2), you should
get a file called `zeros6`. That was the file I was working with, and it
doesn't contain any null bytes AFAIK. (Sorry for not being more clear.)

**Comment by SuprDewd** [comment]
(Of course it should be possible to read a file containing
null bytes, but that belongs in a new issue, I guess.)

**Comment by edwinb** [comment]
Oh, right, I was using the .tar rather than looking at its contents. I'll make this all work for strings and move on to binary files later.

**Comment by edwinb** [comment]
Okay, this now loads more or less straight away, and I can print the contents successfully and accurately. 

The next related issue is that some things in the library aren't very good at dealing with long strings because they are recursive and blow the stack. I'll move onto this next - string processing is really naive at the minute so I want to fix it asap.
