### ISSUE TITLE
Weird putStrLn behavior

### ISSUE THREAD

**Issue by berdario** [idris-lang/Idris-dev#3610]
Given the following transposeMat definition:

```
createEmpties : Vect n (Vect 0 elem)
createEmpties = replicate _ []

transposeMat : Vect m (Vect n elem) -> Vect n (Vect m elem)
transposeMat [] = createEmpties
transposeMat (x :: xs) = let xsTrans = transposeMat xs
                         in zipWith (::) x xsTrans
```

Running `:exec print $ transposeMat $ the (Vect 2 (Vect _ Nat)) [[1,2,3], [3,4,5]]` in the repl prints an empty string

defining
```
p : IO ()
p = print $ transposeMat $ the (Vect 2 (Vect _ Nat)) [[1,2,3], [3,4,5]]
```

instead, and invoking `:exec p` in the repl works as expected

**Comment by edwinb** [comment]
It looks like erasure analysis does the wrong thing when compiling via :exec - at least, when I look at the generated code, there are things being erased which shouldn't be. This would at least explain why it works fine when you compile it via a complete definition. This is resulting in a silent failure - I will look into this, because this makes :exec not very useful.

**Comment by edwinb** [comment]
It turns out the problem is that there's a missing step when compiling at the REPL which means that Nats don't work. Fix coming shortly.

**Comment by berdario** [comment]
Thanks!
