### ISSUE TITLE
Interface issue ?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3624]
The program
```
> Uninhabited (LT = EQ) where
>   uninhabited Refl impossible
```
type checks fine but
```
> Uninhabited (LT = GT) where
>   uninhabited Refl impossible
```
fails to type check with 
```
- + Errors (1)
 `-- ./Ordering/Properties.lidr line 14 col 2:
     When checking type of Ordering.Properties.(LT = GT) implementation of Prelude.Uninhabited.Uninhabited:
     Can't disambiguate name: Prelude.Interfaces.LT, Prelude.Nat.LT
```
Is this an issue with interfaces? The problem can be circumvented by explicitly qualifying `LT` but the behavior is still quite annoying and certainly unexpected.

**Comment by bach741974** [comment]
Hello,

I suppose it ok. In first case you have EQ as constructor only in Ordering data type:

Idris> :t EQ
EQ : Ordering
and Idris can infer a type on LT
But in last  case Idris cannot make this because LT and GT are defined in different types and interfaces:

Idris> :t LT
Prelude.Interfaces.LT : Ordering
Prelude.Nat.LT : Nat -> Nat -> Type

Idris> :t GT
Prelude.Interfaces.GT : Ordering
Prelude.Nat.GT : Nat -> Nat -> Type

and Idris informs you about this collision:

Can't disambiguate name: Prelude.Interfaces.LT, Prelude.Nat.LT

**Comment by nicolabotta** [comment]
@bach741974 Thanks, that's a good explanation and I am closing the issue!
