### ISSUE TITLE
Setting nested record fields using record update syntax

### ISSUE THREAD

**Issue by timjs** [idris-lang/Idris-dev#3647]
_Note: I don't want to start a flamewar on syntax, just curious about the reasoning. I ask the question here so that it can easily be closed and muted._

Why does record syntax use an arrow `->` to indicate setting nested fields instead of a dot `.`? Dots are consistently used in the language to acces nested objects in modules and namespaces. Arrows always denote function types. Why break this expectation in the (further) very consistent Idris syntax?

Here an example from the book:
```idris
addCorrect : GameState -> GameState
addCorrect = record { score->correct $= (+1)
                    , score->attempted $= (+1) }
```
versus
```idris
addCorrect : GameState -> GameState
addCorrect = record { score.correct $= (+1)
                    , score.attempted $= (+1) }
```

**Comment by ahmadsalim** [comment]
@timjs
Thanks for the question. I understand your well-intention, but optimally these kind of questions should be asked on the [mailing list](https://groups.google.com/forum/#!forum/idris-lang) or on IRC.

I can not answer this question precisely, since I had no partake in the decision making, but I think the reason is as you mentioned to separate it from namespace accesses (i.e., is `score.correct` a nested field `score` and `correct` or a single field `correct` prefixed with field `score`). Furthermore `.` is also used for function composition, so it might create some confusion there as well.
I think that `->` is consistent with C-style record access, and so might make sense to use as an alternative to `.`.

**Comment by timjs** [comment]
Thanks for your quick reaction @ahmadsalim. I wanted to post it on the mailing list first, but syntax discussions can be heavy and threads can be locked here.

I thought about the C influence. It is about the only place where Idris is influenced by it 😉. Namespaces conventionally should start with an upper case letter, so no ambiguity there I think.

I don't understand what you mean by the difference between "`score.correct` being a nested field `score` and `correct` or a single field `correct` prefixed with field `score`". Can you elaborate?

**Comment by ahmadsalim** [comment]
Sorry, it the latter should have been or a single field `correct` prefixed with namespace `score`
