### ISSUE TITLE
Use a higher-level intermediate representation when compiling from JavaScript to increase readability

### ISSUE THREAD

**Issue by be5invis** [idris-lang/Idris-dev#3650]

**Comment by ahmadsalim** [comment]
@be5invis Could you kindly elaborate more on what you mean here?

**Comment by be5invis** [comment]
The current JS backend's output is, well, hard to understand. It looks like directly embedded a stack-based VM, rather than translating Idris’ IRs into JavaScript.

**Comment by ahmadsalim** [comment]
@be5invis OK, I have updated the title. If possible could you please update your original issue description to highlight some of the challenges if someone were to look into it?

**Comment by edwinb** [comment]
This isn't going to happen, sorry. Not unless someone feels like entirely rewriting it, or contributing a new "readable JS" backend or similar. The primary intention of the JS backend isn't to produce JS that's readable, but rather to produce JS that runs.

**Comment by be5invis** [comment]
It is not FAST either.
Maybe I should try to write one. An alternative...

**Comment by edwinb** [comment]
I was careful not to claim anything about how fast it is :). But this is the kind of open ended issue that just lurks there with nothing happening - it's a project rather than an issue. 

If someone contributes a new JS backend, that works and is maintained, that would be great. I would prefer emphasis on efficiency rather than readability myself, but there's no reason not to aspire to both.

I do actually wonder if we should have any backends other than the reference C one as part of the main distribution, given that there isn't any significant maintenance of anything other than that.
