### ISSUE TITLE
Interface parameter with implicits in type

### ISSUE THREAD

**Issue by erisco** [idris-lang/Idris-dev#3683]
Test case:
```
    interface X (r : {a:Type} -> a -> Type) where
```

Output:
```
test.idr:1:11:When checking type of constructor of Main.X:
When checking argument r to Main.X:
        Type mismatch between
                a -> Type (Type of r)
        and
                a1 -> Type (Expected type)

        Specifically:
                Type mismatch between
                        v0 -> Type
                and
                        Type
```

Idris version 0.99.

I do not know if this is a missing feature, bug, or purposefully does not work. If this did work I could abbreviate more code, as implicits do.

**Comment by ahmadsalim** [comment]
@erisco Does it work with explicit types?

**Comment by erisco** [comment]
@ahmadsalim as in `interface X (r : (a:Type) -> a -> Type) where`? Yes, that works. The issue is that Idris will not infer `a` for me and this causes unwanted verbosity.

**Comment by ahmadsalim** [comment]
Thanks, I will tag this as a bug then.

**Comment by erisco** [comment]
This test case succeeds:

`interface X (r : String -> {a:Type} -> a -> Type) where`

There is something strange then about the implicit being the first.

**Comment by edwinb** [comment]
You can see the same effect here:

    Y : (r : {a : Type} -> a -> Type) -> Type
    foo : (r : {a : Type} -> a -> Type) -> Y r

The problem is caused by the rules for the way scoped implicits are elaborated. The elaborator will always add implicit arguments to applications/names, such as `r` here.

When it sees `r` in the type of `foo`, it sees that `r` has an implicit argument and applies it. However, it shouldn't, because the expected type of the argument of `Y` requires that `r` isn't applied to anything.

This at least explains why it works fine when the `{a : Type}` is made explicit - there's no implicit application going on. I'm clearly going to have to rethink scoped implicits, because in an effort to make the implementation simple I have probably gone too far and made it not clear how they work...
