### ISSUE TITLE
Document Control.ST

### ISSUE THREAD

**Issue by be5invis** [idris-lang/Idris-dev#3692]
I saw it was in TODO

**Comment by jfdm** [comment]
There is a lot to infer from the issue's title. @be5invis can you please elaborate more on what you are proposing?

**Comment by be5invis** [comment]
@jfdm 
As we have something like:
```idris
m : Eff a [..., EXCEPTION]
```
we want things like
```idris
... do
    catch m handler
```
that runs m in the current context, and if `m` raises some exception, pass to `handler`.

**Comment by edwinb** [comment]
There's lots of reasons why this turns out to be a bad idea for `Eff`. In fact `Eff` turns out to have a number of annoying limitations which are fixed by `Control.ST`, and therefore it will soon be considered deprecated in favour of `Control.ST`, which can already do this (see `Control.ST.Exception`. 

I haven't written any documentation for `Control.ST` yet, however... I will as soon as I can, and let people know about it.

**Comment by be5invis** [comment]
@edwinb So `ST` is the new version of Effects, or an equivalent to Haskell’s ST?

**Comment by jfdm** [comment]
`Control.ST` is the new version of `Effects`.

**Comment by be5invis** [comment]
@jfdm So...
You have "old effects"
You have "effects"
And now, "ST"
...
This will be the last, right?

**Comment by edwinb** [comment]
All of this will be explained when I document it. We don't generally track TODOs or tasks of this size on the issue tracker, by the way. This is mostly because, given the resources we have available, a lot of large tasks are really just wishful thinking, and even if they are useful they have a tendency to get lost in all the other small things that need fixing. I prefer to use the issue tracker for clearly defined problems with the current implementation.

I think it's more useful to document large tasks on the wiki (e.g. at https://github.com/idris-lang/Idris-dev/wiki/Mini-Projects) or in some other discoverable place. We should try to get better at keeping these up to date.

I promise I will do this one though, because `Eff` is limited and the new `ST` system solves a lot of the issues with it.

**Comment by ahmadsalim** [comment]
I will close the issue then.
