### ISSUE TITLE
Point-Free Style and Totality

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#3693]
Given the below data structure and flattening functions. Idris used to consider `flatten'`, which was written in a point-free style, total. Idris now complains. The non-point free style is total as expected.

```idris
module Temp
%default total

data Foobar : Type where
  Base : Foobar
  Bar : Int -> String -> Foobar
  Break : Bool -> Foobar
  Foo : (Nat -> Foobar) -> Foobar

flatten : Foobar -> Foobar
flatten (Break x) = if x then Base else Bar 1 " "
flatten (Foo f) = Foo (\i => flatten $ f i)
flatten other = other

flatten' : Foobar -> Foobar
flatten' (Break x) = if x then Base else Bar 1 " "
flatten' (Foo f) = Foo (flatten' . f)
flatten' other = other
```

**Comment by edwinb** [comment]
I wouldn't expect this to get past the checker, because it relies on inlining to work. It only worked in the past because we had different versions of case trees for totality checking (very aggressively inlined) and execution (not inlined so much to avoid excessive sharing). However, it turns out that doing this can change the result, because inlining can remove non-terminating things that never get run, so it's unsound in general.

At the moment, you'll need to expand `flatten'` here.

I'm not going to fix this, because I want to keep the totality checker simple and I don't have very much (if any) time to work on making it more complete. If totality checking specifically gets a maintainer that is able to put time and effort into it, and is able to fully document what's going on, that'd be different of course.

**Comment by jfdm** [comment]
Thank you, for explaining what has happened.
