### ISSUE TITLE
Support `Go to definition` and `Find usages` in IDE protocol

### ISSUE THREAD

**Issue by zjhmale** [idris-lang/Idris-dev#3709]
I think we should support the following features in IDE protocol to some degree:

* Go to definition: get the location (file source, line number, column number) for a concrete identifier.
* Find usages: get all the locations (file source, line number, column number) for a concrete identifier.

**Comment by david-christiansen** [comment]
I agree that this would be nice to have, and as REPL commands as well for the Vim users out there.

But we don't typically use the issue tracker for open-ended projects and feature requests like this, because it makes it much harder to keep track of the actual bugs in Idris.

We would enthusiastically accept this as a contribution, however, and I'm happy to answer what questions you might have on how to implement it.

One challenge is that we currently only install .ibc files for libraries, rather than source. A concrete first step towards this would be to get Idris to also install source files for libraries.
