### ISSUE TITLE
Type checking failure with vector

### ISSUE THREAD

**Issue by paulch42** [idris-lang/Idris-dev#3766]
The code
```
  import Data.Vect

  data DataStore : Type where
       MkData : (size : Nat) -> (items : Vect size String) -> DataStore

  size : DataStore -> Nat
  size (MkData size _) = size

  addToStore : DataStore -> String -> DataStore
  addToStore (MkData size items) y = MkData (1+size) ?x
```
type checks ok, and if I ask for the type of the hole I get
```
  size : Nat
  items : Vect size String
  y : String
--------------------------------------
x : Vect (S size) String
```
so the type of expression `items++[y]` is `Vect (S size) String`, but if the last line is replaced by
```
  addToStore (MkData size items) y = MkData (1+size) (items++[y])
```
the result is
```
When checking right hand side of addToStore with expected type
        DataStore

When checking argument items to constructor Main.MkData:
        Type mismatch between
                Vect (size + 1) String (Type of items ++ [y])
        and
                Vect (S size) String (Expected type)
        
        Specifically:
                Type mismatch between
                        plus size 1
                and
                        S size
```
If the line is replaced by
```
  addToStore (MkData size items) y = MkData (S size) ([y]++items)
```
or
```
  addToStore (MkData size items) y = MkData (S size) (y::items)
```
then all is well.

**Comment by ahmadsalim** [comment]
@paulch42 We appreciate your interest in Idris! Next time, please use the mailing list or IRC for questions before opening an issue on the tracker.

This is completely expected behaviour. You can see the type of `++` is:
```idris
Data.Vect.(++) : Vect m a -> Vect n a -> Vect (m + n) a
```

So the resulting type of `items ++ [y]` has the type `Vec (size + 1) String` since `items` has type `Vec size String` and `[y]` has the type `Vec 1 String`. As I answered in #3763, then `1 + size` and `size + 1` are not the same because `+` is defined by recursion on the first argument.
