### ISSUE TITLE
Resource aware types?

### ISSUE THREAD

**Issue by nwmcsween** [idris-lang/Idris-dev#3787]
I'm wondering if it would be possible to have 'types' that are resource aware, similar to raml (resource aware ml)?

**Comment by LeifW** [comment]
Could you give a brief synopsis of what this means / what raml is?

**Comment by nwmcsween** [comment]
The raml website explains it a bit better: http://www.raml.co

**Comment by ahmadsalim** [comment]
@nwmcsween Edwin had made a [Resource DSL](https://edwinb.wordpress.com/2011/09/16/resource-safe-systems-programming-with-embedded-domain-specific-languages/). See also, the [Uniqueness Types](http://docs.idris-lang.org/en/latest/reference/uniqueness-types.html) and Linear Types extensions.

Note: Could you kindly use the mailing list or IRC next time for questions, instead of the issue tracker?
