### ISSUE TITLE
Bad coverage check leading to broken canonicity

### ISSUE THREAD

**Issue by hansbugge** [idris-lang/Idris-dev#3792]
The following code seem to pass type and totality checking in Idris 1.0. However, `f` lacks a case in its definition, which means that we can get a `Nat` which isn't a natural number.

```
module Canonicity
%default total

data ZeroSumList : Integer -> Type where
  Cons : (m : Integer) -> ZeroSumList n -> ZeroSumList (m + n)
  Nil : ZeroSumList 0

f : ZeroSumList 0 -> Nat
f Nil = 0

NaN : Nat
NaN = f (Cons 0 Nil)
```

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue!

In Idris it seems to consider the function covered because the unification issue `n + m =?= 0` fails when having the `Cons m zsl` case, which is wrong since `n + m` could potentially be `0`.
I have tried to encode the same program in Agda, and here it complains about the coverage because it gets 'stuck' on the unification problem `n + m =?= 0` and therefore is unsure whether the function is covered or not.

**Comment by edwinb** [comment]
It's because of the constant 0, which I overlooked when writing the check to see if further information could resolve the unification problem.

So if you see this kind of issue with primitive types, one way to start debugging it is to try replacing the primitive number type with Nat to see if the issue persists (here, it doesn't, which is a useful clue.)

Anyway, I'm adding the case I missed now.
