### ISSUE TITLE
I don‘t want to write Lazy a, I hope Idris automatically add them.

### ISSUE THREAD

**Issue by zaoqi** [idris-lang/Idris-dev#3793]
我不想写Lazy a,我希望Idris自动加上它们。

**Comment by ahmadsalim** [comment]
@zaoqi You already do not need to add 'Force' and 'Delay' explicitly. However, Idris is strict by default, so if you want to have a lazy argument you have to write it (otherwise, how would Idris know that you want one instead of a strict one).

See https://github.com/idris-lang/Idris-dev/wiki/Unofficial-FAQ#why-isnt-idris-lazy .

I have tried to use Google Translate below, so forgive me if it sounds wrong:
@zaoqi你已经不需要添加'Force'和'Delay'了。 但是，Idris在默认情况下是严格的，所以如果你想要一个懒惰的论据，你必须写它（否则，Idris如何知道你想要一个，而不是一个严格的）。

请参阅https://github.com/idris-lang/Idris-dev/wiki/Unofficial-FAQ#why-isnt-idris-lazy。

**Comment by zaoqi** [comment]
@ahmadsalim
like this:
{-# LANGUAGE Lazy #-}
ifThenElse : Bool -> a -> a -> a -- = ifThenElse : Bool -> Lazy a -> Lazy a -> a
ifThenElse True  t e = t
ifThenElse False t e = e

**Comment by ahmadsalim** [comment]
@zaoqi This is fairly non-trivial to do since it requires reconsidering all of the semantics. In any case, you are welcome to discuss this feature request on the mailing list.
