### ISSUE TITLE
Can Idris automatically generate type declaration like Haskell?

### ISSUE THREAD

**Issue by zaoqi** [idris-lang/Idris-dev#3794]
Idris能像Haskell一样自动生成类型声明吗？

module Main
main = putStrLn "你好，世界！"

Automatic generation "main : IO ()"
自动生成 "main : IO ()"

**Comment by ahmadsalim** [comment]
@zaoqi You mean infer the type?

That is generally undecidable for dependent types, but you could try writing:
```idris
  main : ?p 
  main = putStrLn "bla"
```
and then use proof search on `?p` and see if it infers the correct type.

Note: Please use the mailing list or IRC (#idris on Freenode) for questions in the future instead of using the issue tracker.

**Comment by zaoqi** [comment]
@ahmadsalim I can't use mailing list and web interface of IRC because I'm in China.

**Comment by ahmadsalim** [comment]
@zaoqi Does https://webchat.freenode.net/ not work? Or do you mean there are legality issues?

**Comment by zaoqi** [comment]
*.google.* doesn't work on China.So http://webchat.freenode.net/ doesn't work on China.

**Comment by NobbZ** [comment]
About everyone I know about living in China does VPN to circumvent this
limitation, why don't you do as well?

Zaoqi <notifications@github.com> schrieb am Mo., 1. Mai 2017 um 15:03 Uhr:

**Comment by ahmadsalim** [comment]
@NobbZ I am unsure whether that is legal to do, which is why I did not suggest it myself.

**Comment by NobbZ** [comment]
Well, I'm pretty sure it isn't.

But currently I do only see a very small number of possible solutions for
this problem, whereof the VPN and IRC-client are the one which were the
erasiest for everyone (I'd try the client first):

1. VPN
2. Try plain old IRC-Clients (like mIRC) and connect to freenode
3. The OP leaves China
4. Official Chat moves to a network which has an webclient that does not
use any of googles services, the same for mailinglist.

But if we do 4, what happens if China decides to block exactly the chosen
service a day later?

Ahmad Salim Al-Sibahi <notifications@github.com> schrieb am Mi., 3. Mai
2017 um 13:38 Uhr:

**Comment by melted** [comment]
It's not overly onerous for us if issues are used when it's the only convenient method for an idris user to communicate with the project.

**Comment by ahmadsalim** [comment]
@NobbZ The user did end up being able to connect using a classical IRC client (method 2)

@melted Yeah, I agree. But I try when possible to let people use the mailing list or IRC if possible since there are many more people active there that can answer questions, etc.

**Comment by zaoqi** [comment]
@NobbZ I have a Ubuntu server in Seoul and I don't know how to build a VPN server.
