### ISSUE TITLE
0/0 is being compiled as -Infinity, which fails to compile (using the C backend).

### ISSUE THREAD

**Issue by PoroCYon** [idris-lang/Idris-dev#3796]
In the following program, `0 / 0` is compiled as `-Infinity` instead of NaN. The C backend (as well as the JavaScript backend) then emit this as `-Infinity`, which fails to compile. In the REPL, however, `0 / 0` does evaluate to NaN, as it should.

PoC code:
```idris
module Main

main : IO  ()
main = printLn $ 0.0 / 0
```

The C backend emits: (`idris -S -o foo.c foo.idr`)
```c
LOC(4) = MKFLOAT(vm, -Infinity);
```

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.
I am unsure why this happens, but in any case it should not output `-Infinity` to the codegen.

If you are interested in looking into it further, I think the relevant code should be around: https://github.com/idris-lang/Idris-dev/blob/119d964b75bf6a8b8a2f1f7c24450a4951cf26bc/src/Idris/Primitives.hs#L110

**Comment by PoroCYon** [comment]
I'd like to, but I currently don't have the time to look into it, sadly.

**Comment by edmundsmith** [comment]
I think I've got a working patch for this [here](https://github.com/edmundsmith/Idris-dev/commit/59bfe8bdac3f65cfefe970964c4983f5b9d34b26). It works as expected for the test case `main = putStrLn $ show $ 0.0/0.0` (plus others).

The existing Binary instances rely on the library-supplied `instance Binary Double`, but a sift through Data.Binary's source reveals that it uses `encodeFloat` and `decodeFloat` behind the scenes, marshalling doubles into an `(Integer, Int)`. This works for most values, but doesn't respect IEEE NaNs or Infinities. By using the explicit marshalling functions added in `binary-0.8.4`, the IEEE representation is preserved through `Binary` and `encode`/`decode`. 

If upgrading to `binary-0.8.4` is a deal-breaker, IEEE marshalling can take place by using `Word64` `put`/`get`, but this would require reimplementing a `Double -> Word64` conversion, which I assume would be quite unsafe, so I'm not sure how you'd want to organise that to keep the codebase clean.

I hope this is useful/a successful pull req can come from this - this would be my first contribution, which is why I'm being cautious of doing something wrong.

**Comment by edmundsmith** [comment]
I've just remembered that this will also need to adjust the `Fl f` pattern in `src/IRTS/CodegenC.hs: bcc, mkConst` to avoid C errors, as the current `show f` will give `Infinity` and `NaN`, while C (well, `math.h`) uses `INFINITY` and `NAN`. I've got a simple fix using `(map toUpper $ show f)` included as another commit in my issue3796 branch, but I don't know if that's too hacky for mainline or needs a better method.

**Comment by edmundsmith** [comment]
Should this be closed now?
