### ISSUE TITLE
 Rewrite in Do block

### ISSUE THREAD

**Issue by be5invis** [idris-lang/Idris-dev#3840]
It is common to introduce multiple `let`s and `rewrite`s when proofing a theorem. So adding `rewrite` in `do` block would be helpful to reduce nested indentations...

Translation rule:
```
do { rewrite H; ...xs } => rewrite H in do {...xs}
```

**Comment by ahmadsalim** [comment]
@be5invis Thanks for the PR.
I think it is a good idea!
You are welcome to add it if you are interested.

**Comment by be5invis** [comment]
@ahmadsalim 
Just for fun : We can also add `intro` into `do` blocks...
Translation rule:

```idris
do { intro patterns; ...xs } => \pattern_1 => \pattern_2 => ... => do {...xs}
```

**Comment by be5invis** [comment]
I'd like to write another PR after the JS one is finished (currently call specialization is not included yet).

**Comment by ahmadsalim** [comment]
@be5invis I think we should avoid this becoming a tactic system (we already have elaborator reflection which does the same thing). 
I believe `rewrite` is suitable because it is surface syntax which is somehow less accessible in `do` requiring weird syntactic nesting.

**Comment by be5invis** [comment]
@ahmadsalim I said that are just for fun 😄.
Just adding `rewrite`, `intro`ducing abstraction and `apply`ing functions are convenient enough for now, we do not need special syntax for them.

**Comment by ahmadsalim** [comment]
@be5invis I understand that, and I mean it is not my decision if such additional language constructs like `intro` and `apply` will be accepted, because this is a big change in language design.
I understand the excitement of contributing language features 😄, but there is also an issue with adding too many: people may rely on them and then it is hard to change in the future or make good maintenance.
Personally, I think writing `\a,b,c => do ...` or `e $ do ...` is not as bad, because often they do not need to be nested as much, and when they do it is good to be more declarative about it with explicit abstraction and application.
If you are still  interested in adding these, please use the mailing list to start a discussion, potentially including @edwinb.

**Comment by be5invis** [comment]
PR => #3847
