### ISSUE TITLE
Write the type checker in miniKanren

### ISSUE THREAD

**Issue by zaoqi** [idris-lang/Idris-dev#3906]
In order to inferred types

**Comment by ahmadsalim** [comment]
Thank you for the feature request.

However, note that the reason we do not have more inferred types, is not because of the lack of development but rather because it is inherently undecidable to infer types for dependently typed languages and also because that some features (like type-based overloading) depend on the availability of type signatures.

Also, it would be unfeasible to rewrite the elaboration and type checking procedure in miniKanren at this stage, without clear benefits because of the inherent limitations. I will therefore close the issue.
