### ISSUE TITLE
Drop support for GHC <= 7.8.4, Cabal <= 1.20

### ISSUE THREAD

**Issue by geigerzaehler** [idris-lang/Idris-dev#3918]
This would make development a lot easier.
* Because of different versions of `Prelude` on needs to be careful with imports and test them in all environments.
* We reduce the number of travis jobs and get quicker feedback.
* It would enable us to remove a couple of hacks, especially in `Setup.hs`.

I’d be happy to tackle this.

**Comment by melted** [comment]
I think the biggest reason for keeping it at 7.6 was because that was what was stable debian, but that has changed with the release of stretch. So I'm definitely in favor of dropping 7.6 and 7.8.

**Comment by ahmadsalim** [comment]
I am in favor of dropping support for `< GHC 8` as well.

**Comment by melted** [comment]
@ahmadsalim I'd like to keep 7.10, it's the current one on FreeBSD and Ubuntu LTS.

**Comment by david-christiansen** [comment]
We have at least one major user who uses Debian stable, so we should give them a chance to upgrade their systems by announcing this on the mailing list. After that, I'm OK with ditching 7.6 and 7.8, but we should keep 7.10 for the reasons @melted specified.

**Comment by jfdm** [comment]
Agreed. I think it has always been an semi-official policy that we test against versions of ghc/cabal that run on the latest stable versions of the 'major' operating systems out there. 

My personal opinion is that packaging binary builds for OSs is not something we should aim to provide ourselves. Nonetheless, I do think that for a reasonable set of stable OSs we should ensure that Idris can be installed using:

```
cabal update
cabal install idris
```

or

```
stack install idris
```

We would be prudent to remember that not everyone who would like to use Idris is coming from Haskell, knows about Haskell, or about managing their system. Easy install routes are better.

Funnily enough when Debian released stretch I did revisit the set of ghc/cabal that we test against. It turns out: Ubuntu 16.04 LTS has the oldest version of GHC (7.10.3) at the moment. Thus, I too think it would be prudent to stick with that version until the next LTS comes out.
