### ISSUE TITLE
TDDwI challenge vectTake doesn't compile depending on order of args in type specification

### ISSUE THREAD

**Issue by tsdh** [idris-lang/Idris-dev#4064]
I'm enjoying Type-Driven Development with Idris, but now I stared for 15 minutes at my obviously correct code just to find out that commuting the addition between two `Nat`s in the function's type specification makes the thing compile.

Concretely, this does not compile:
```Idris
vectTake : (n : Nat) -> Vect (m + n) a -> Vect n a
vectTake Z _ = []
vectTake (S k) (x :: xs) = x :: vectTake k xs
```
It fails with:
```
- + Errors (1)
 `-- TryIndex.idr line 10 col 0:
     When checking left hand side of vectTake:
     When checking an application of Main.vectTake:
             Type mismatch between
                     Vect (S len) a (Type of x :: xs)
             and
                     Vect (plus m (S k)) a (Expected type)
             
             Specifically:
                     Type mismatch between
                             S len
                     and
                             plus m (S k)
```
But just swapping `m + n` to `n + m` compiles just fine:
```Idris
vectTake : (n : Nat) -> Vect (n + m) a -> Vect n a
vectTake Z _ = []
vectTake (S k) (x :: xs) = x :: vectTake k xs
```
Why is that?  I'm using Idris version 1.1.0.

**Comment by msmorgan** [comment]
There's nothing intrinsic about addition (or an operator called "+") that means it's commutative.

However, it is possible to prove to Idris that a function is commutative. There is a function defined in `Prelude.Nat` called `plusCommutative` that proves this, for any two inputs `m` and `n`. Here is its definition:

```idris
total plusCommutative : (left : Nat) -> (right : Nat) ->
  left + right = right + left
plusCommutative Z        right = rewrite plusZeroRightNeutral right in Refl
plusCommutative (S left) right =
  let inductiveHypothesis = plusCommutative left right in
    rewrite inductiveHypothesis in
      rewrite plusSuccRightSucc right left in Refl
```

As you can see, it's a non-trivial inductive proof, so changing the order of `m` and `n` is not something Idris will do without prompting. It's possible to use the proof returned by `plusCommutative` to to write your function with the commuted signature, but it's usually preferred to give your function a type that requires the minimum number of explicit proofs and rewrites.

**Comment by david-christiansen** [comment]
To expand on @msmorgan's great answer:

Let's step through what Idris needs to do to check:
```
vectTake : (n : Nat) -> Vect (n + m) a -> Vect n a
vectTake Z _ = []
vectTake (S k) (x :: xs) = x :: vectTake k xs
```

The first thing that must be done is to expand the type signature, figuring out that there's extra hidden arguments `a` and `m`:
```
vectTake : {a : Type} -> {m : Nat} -> (n : Nat) -> Vect (n + m) a -> Vect n a
```

Then, it goes through and checks that this type really is a type, in the process figuring out that it uses the `Num` implementation for `Nat` to find out what `+` means in this context, which is equivalent to:
```
(+) : Nat -> Nat -> Nat
Z + m = m
(S k) + m = S (k + m)
```

Now, each case must be checked. In the zero case, we get:
```
vectTake {a} {m} Z xs = []
```
after making all the hidden stuff explicit. Idris needs to check that `xs` has the type `Vect (Z + m) a`. Luckily, the `Nat` in this type matches the first pattern for `+`, so Idris can reduce it to `Vect m a`, which is the right type for `xs` already.

If it had instead needed to check that it was a `Vect (m + Z) a`, then that essential reduction step couldn't occur, because `+` pattern matches only on the first argument. Even if we added a case to the end of `+`, like:
```
Z + m = m
(S k) + m = S (k + m)
n + Z = m
```
Idris would still not be able to reduce it, because pattern-matching goes from top to bottom and there would be no reason to rule out the first pattern yet.

Generally, please ask technical support questions like this on the mailing list or in the IRC channel, rather than as issues on Github, because we already struggle to keep track of the actual bugs in this database, and having lots of issues that aren't actual issues in Idris makes this task more difficult.

**Comment by tsdh** [comment]
@david-christiansen @msmorgan Thank you both for the great explanation.  And my apologies, I'll use the mailinglist next time.

**Comment by david-christiansen** [comment]
No worries, lots of projects use an issue tracker for tech support. It just doesn't work well for us.
