### ISSUE TITLE
'reachable postulates' errors for Decidable.Equality.Int

### ISSUE THREAD

**Issue by jdevuyst** [idris-lang/Idris-dev#4090]
I get the following compile error:

```
reachable postulates:
  Decidable.Equality.Decidable.Equality.Int implementation of Decidable.Equality.DecEq, method decEq, primitiveNotEq
```

when I try to compile the file https://gist.github.com/jdevuyst/1598490bfb1db7e812cb2157963ad9fc

Some context:
- Part I of the code is an implementation of `Ordered` for `Int`
- Part II of the code in the gist was previously discussed in issue #4049. There is some failure in erasure analysis in this part of the code.
- Part III is a simple operation that triggers the `reachable postulates` error. The operation is an `Int`-based counterpart of the example discussed in #4049.

The code can be made to run fine by defining `DecEq Int` as follows:

```
implementation DecEq Int where
    decEq x y = case x == y of -- Blocks if x or y not concrete
                     True => Yes primitiveEq
                     False => No primitiveNotEq
       where primitiveEq : x = y
             primitiveEq = really_believe_me (Refl {x})
             primitiveNotEq : x = y -> Void
             primitiveNotEq _ = really_believe_me ()
```

(whereas currently `primitiveNotEq` is defined as `postulate primitiveNotEq : x = y -> Void`)

I'm not sure if redefining `primitiveNotEq` like this is an option. Naively I do find it surprising that a program would fail to compile due to a failure in erasure analysis.

**Comment by ahmadsalim** [comment]
To be honest, I am wondering whether we should instead have decidable equality as a primitive. @edwinb Any thoughts on this?

**Comment by ahmadsalim** [comment]
@jdevuyst But your PR is of course appreciated in the mean time!

**Comment by jdevuyst** [comment]
This problem has resurfaced due to https://github.com/idris-lang/Idris-dev/commit/3b35e39eb964396f6ff0aaf313007cebc45fd7c4

**Comment by edwinb** [comment]
Argh. I wonder why we didn't add something to catch this to the tests. It's odd that it's reachable though, since it's returning something of type Void so should never be called... the problem with using "really_believe_me" is that the proof it comes up with is the wrong type, and this can break type checking in other places. (We shouldn't have 'really_believe_me' anyway, it's a hack for a different problem ages ago...)

I suspect @ahmadsalim's suggested solution of having decidable equality as primitives is a better one.

**Comment by edwinb** [comment]
Okay, I'm going to put it back in with `believe_me` (rather than `really_believe_me`) because the former doesn't reduce and therefore doesn't cause the same type checking issues. But I'm going to think more carefully about how to do this for Blodwen. It might involve primitives for decidable equality.

**Comment by ahmadsalim** [comment]
@edwinb While this is on topic.

I was discussing this a bit once with @david-christiansen on the IRC channel, but there seem to be a lot of interesting design space regarding primitives.  E.g., it might be nice to able to have some way to prove properties about primitives, and test those properties on possible backends.
I recall he had some interesting ideas on how to solve this, but I can't remember them.

Maybe this is something to consider for Blodwen as well?
