### ISSUE TITLE
Idris should be able to prove obvious inequality automatically

### ISSUE THREAD

**Issue by 2426021684** [idris-lang/Idris-dev#4096]
# Steps to Reproduce

Try to compile
```idris
a : {auto p : Not (Int = String)} -> ()
a = ()

b : ()
b = a
```
# Expected Behavior

The code compiles with no error

# Observed Behavior

```
When checking right hand side of b with expected type
        ()

When checking argument p to function Main.a:
        Can't find a value of type
                Not (Int = String)
Holes: Main.b
```

**Comment by david-christiansen** [comment]
This is Idris behaving as expected. Proving inequalities of types is not actually such a trivial thing to do, and that's also not what `auto` means in Idris.

**Comment by 2426021684** [comment]
@david-christiansen Doesn't `(\Refl impossible)` prove inequalities of types? Why would proving inequality be any harder than proving equality (which auto is capable of)? Is there something I should use instead of auto? I encountered this problem when trying to prove that two lists are disjoint.

**Comment by david-christiansen** [comment]
`auto` currently only searches for constructors, and does not create any auxiliary pattern-matching helpers. It would act similarly if the goal were `Not (True = False)`.  In this case, the thing to do is to write the lambdas in explicitly here.

The difficulty with letting `\(Refl) impossible` solve the goal `Not (Int = String)` is that it's actually hard to see that this proof technique is really valid. (It may work in Idris as-is, but the semantics of it are suspect). This is because we know that the _only_ ways to construct a datatype are its constructors, so it makes sense to do induction on them, but there are potentially infinitely many ways of building types (one can always define a new datatype).  Pattern matching should ultimately be justified by some underlying math, but I don't know what that would be here.

**Comment by ahmadsalim** [comment]
@david-christiansen I guess you can rely on the type constructors (`Int` and `String`) being different in this case, but it is far from trivial for more complex types.

**Comment by 2426021684** [comment]
Is it possible to write an elaborator reflector script to prove it?

**Comment by david-christiansen** [comment]
@ahmadsalim in the case of Idris, which has K and thus is inconsistent with univalence, this argument probably works, but I don't know how it would be justified using something like eliminators nonetheless. We should be suspicious of patterns of elimination that we don't know how to phrase in eliminators, I think...

**Comment by david-christiansen** [comment]
@2426021684 If you can do it with pattern matching, then you can do it with `Elab`. The way to do it would be to explicitly generate a helper function.
