### ISSUE TITLE
:exec power 10 100000 prints 0 as the output

### ISSUE THREAD

**Issue by lpadukana** [idris-lang/Idris-dev#4311]
# Steps to Reproduce

```
~/code/play/idris $ idris --nobanner
Idris> :exec power 10 100000
0
```

# Expected Behavior

### One of the following

- Prints `1` followed by `100000` zeros
- Produces a stack trace in case it fails

# Observed Behavior

Prints `0`, which is wrong

**Comment by ahmadsalim** [comment]
Thanks for reporting the issue.

**Comment by yanok** [comment]
This seems to be a mini-gmp related issue. If I build Idris with libgmp I can't reproduce it. This also seems to be unrelated to #4312: I can reproduce this even with the tail-recursive `power` implementation.
It also fails for smaller numbers: I've found that `:exec power 10 12467` returns something looking like correct answer, both `:exec power 10 12468` and `:exec power 10 12469` result in segmentation fault, while `:exec power 10 12470` returns `0`.
It looks like the problem is in the `mpz_get_str` function: computing `power 10 12468` and then dividing by ten gives something equal to `power 10 12467`, so I guess the broken part is conversion to a string.

**Comment by yanok** [comment]
I tried updating to the latest mini-gmp version but with no luck.

**Comment by ahmadsalim** [comment]
@yanok Thank you for looking into this. Please consider reporting a bug in miniGMP https://gmplib.org/manual/Reporting-Bugs.html

**Comment by yanok** [comment]
@ahmadsalim Unfortunately I can't reproduce it with just miniGMP and plain C code. Might be the root cause is the interplay between miniGMP and Idris RTS (the GC?). In fact, if I comment out `init_gmpalloc()` call in `idris_main.c` thus letting miniGMP allocate memory using plain `malloc`, the issue disappears.

**Comment by ahmadsalim** [comment]
@yanok Maybe it is because of the hack mentioned here: https://github.com/idris-lang/Idris-dev/blob/1ecb649ca65450bb4da8d0fa253d1bc6f70aa7d9/rts/idris_gmp.c#L10 ?

**Comment by yanok** [comment]
I've tracked this down to `mpz_sizeinbase` function that does alloc/free for every decimal character, eventually triggering the GC and making `mpz_t` pointer `mpz_get_str` function holds invalid.
This comment in `idris_gmp.c` seems related:
```c
// TMP HACK! Require this much space in the heap before a GMP operation
// so it doesn't garbage collect in the middle.
// This is highly dodgy and needs to be done better because who knows if
// GMP will need to allocate more than 64k... better to work out how
// much space is needed (or find another way of preventing copying)
#define IDRIS_MAXGMP 65536
```

I wonder why it works with the full libgmp...

Knowing nothing about how Idris GC works, I have no idea how to fix this...

**Comment by yanok** [comment]
@ahmadsalim yes, I believe that hack is related. And libgmp works because of smarter algorithm of counting size that doesn't do allocations.
In fact, I've patched miniGMP to avoid repeated allocations and it works now. But now I'm in doubt how to proceed with this. Should I:
 - send the PR against the version of miniGMP currently present in Idris?
 - or first bump the miniGMP version in Idris to the current one and then patch it?
 - or try to convince libgmp guys to accept my patch and then send PR to update Idris to the patched version?

**Comment by ahmadsalim** [comment]
@yanok You are welcome to bump the miniGMP version and patch it in Idris.
You are also welcome to convince the libgmp people!
