### ISSUE TITLE
:exec power 10 1000000 returns with no output and does not report error

### ISSUE THREAD

**Issue by lpadukana** [idris-lang/Idris-dev#4312]
# Steps to Reproduce

```
~/code/play/idris $ idris --nobanner
Idris> :exec power 10 1000000
Idris>
```

# Expected Behavior

### One of the following

- Prints `1` followed by `1000000` zeros
- Produces a stack trace in case it fails

# Observed Behavior

Prints nothing, which is wrong

**Comment by lpadukana** [comment]
Symptom is very similar to #4311

**Comment by ahmadsalim** [comment]
@lpadukana Thanks for reporting the issue, but can you please collect them all in #4311 since they are related?

**Comment by lpadukana** [comment]
I reported separately because although the symptoms are similar, I thought they might have different root causes. Ex: this one might be due to a loop terminating prematurely vs the other might be something to do with the type system. Perfectly fine to collect them together if that helps.

**Comment by yanok** [comment]
Well, this one is simple: compiled executable crashes with Segmentation fault because `power` is implemented as naive recursion. So I guess there should be two issues: one to catch and reported crashes from `:exec` and another one to re-implement power using tail recursion (even better using logarithmic power algorithm but it's not structurally recursive).
