### ISSUE TITLE
Question: Type checker bug?

### ISSUE THREAD

**Issue by SamuraiJack** [idris-lang/Idris-dev#4438]
The definition of "my" in this gits does not type check: https://gist.github.com/SamuraiJack/f42dd2204fe87054b831cabee810b3c3 because of the Functor constraint on `f`. When removing the constraint all typechecks.

Is this a bug, or I am missing some theory?

**Comment by clayrat** [comment]
It will typecheck if you:
* pass the f explicitly:
`my = Algebra {f=ExprF} ExprF Int`
* or put the constraint after the parameter in the definition: 
`Algebra : (f : Type -> Type) -> Functor f => (carrier : Type) -> Type`

**Comment by SamuraiJack** [comment]
Hm.. So everything works as expected?

**Comment by howtonotwin** [comment]
Yes. In

    Algebra : Functor f => (f : _) -> _

`f` is not in scope in time for the constraint, so it actually gets bound as an implicit

    Algebra : .{f : _} -> Functor f => (f : _) -> _

The fix is, of course, not using `f` before it is declared.

It might be worth emitting a warning if the compiler sees likely errors like this.

**Comment by SamuraiJack** [comment]
@howtonotwin Why it works for term-level declarations like this then?:
```idris
some : Functor f => (f : Type -> Type) -> Nat -> Nat
```

**Comment by howtonotwin** [comment]
It does?

```
Idris> :let Algebra : Functor f => (f : Type -> Type) -> (carrier : Type) -> Type
Idris> Algebra List Int
Can't find implementation for Functor f
Idris> :let some : Functor f => (f : Type -> Type) -> Nat -> Nat
Idris> some List Z
Can't find implementation for Functor f
Idris> :unlet Algebra some
Undefined some,Algebra.
Idris> :let Algebra : (f : Type -> Type) -> Functor f => (carrier : Type) -> Type
Idris> Algebra List Int
Algebra List Int : Type
Idris> :let some : (f : Type -> Type) -> Functor f => Nat -> Nat
Idris> some List Z
some List 0 : Nat
```

**Comment by SamuraiJack** [comment]
This is weird, because this code definitely typechecks fine for me:
```idris
module AlgebraParam

some : Functor f => (f : Type -> Type) -> Nat -> Nat

some f k = ?zz
```

**Comment by howtonotwin** [comment]
Well, yes, that typechecks fine. In `zz`, you have an unbound implicit parameter `f0 : Type -> Type`, an instance `Functor f0`, an explicit argument `f : Type -> Type`, which doesn't have a `Functor` instance, and `z : Nat`. The declaration typechecks perfectly fine and in the same way for both `Algebra` and `some` (and good thing, or else there must be dark magicks at work). But the type declarations are still wrong, and it's just coincidence that the actual definition doesn't trigger the error itself.

The *usage* of `Algebra` or `some` triggers the error. *Not* their *definition*. That's my point: maybe we should emit a warning when we see type declarations that look like this, because they are probably wrong.

**Comment by SamuraiJack** [comment]
Hm.. But why f0 and f are considered different variables? The constraints section in the function declaration  uses separate naming scope?

**Comment by howtonotwin** [comment]
I already said it:

> In 
>
> ```idris
> Algebra : Functor f => (f : _) -> _
> ```
>
> `f` is not in scope in time for the constraint, so it actually gets bound as an implicit
> 
> ```idris
> Algebra : .{f : _} -> Functor f => (f : _) -> _
> ```
>
> The fix is, of course, not using f before it is declared.
> 
> It might be worth emitting a warning if the compiler sees likely errors like this.

To reiterate: the variable bound by an arrow is only bound on the right side (which is the only sane way). The constraint `Functor f` falls outside the scope of the `f` bound by the `->`. Instead of emitting an error, we use the usual rule for unbound lowercase identifiers: we bind them implicitly. You then have one binding for `f`, which is implicit, a constraint on that `f`, and then another binding for `f` that shadows the first one. Putting the constraint, which is meant to use `f` after the point where `f` is bound fixes everything.

**Comment by SamuraiJack** [comment]
Hm.. A bit unexpected I'd say. I was always thinking that constraints (things on the left side from => in the type declaration) shares the same naming scope with the right side - isn't how that is done in Haskell?

But please feel free to close this one if you are sure everything is correct.

**Comment by david-christiansen** [comment]
In Haskell, there is an implicit binding site for all the type variables at the far left of the type signature. So `Functor f => (a -> b) -> f a -> f b` is an abbreviation for something like `forall (f :: * -> *) (a :: *) (b :: *) . Functor f => (a -> b) -> f a -> f b`.

Idris doesn't have a separation between `forall` and `->`. In Idris, any function argument can have a name, and that name is in scope for the rest of the type. So the equivalent of the above would be `{f : Type -> Type} -> {a : Type} -> {b : Type} -> Functor f => (a -> b) -> f a -> f b`. If one were to write `{f : Type -> Type} -> {a : Type} -> {b : Type} -> Functor f => (f : a -> b) -> f a -> f b`, it would no longer work, because the second `f` shadows the first. This is analogous to your example.
