### ISSUE TITLE
"assert_total" does not enforce totality

### ISSUE THREAD

**Issue by SamuraiJack** [idris-lang/Idris-dev#4454]
Consider this output from REPL:
```idris
*Playground> :r
Type checking ./Playground.idr
/home/nickolay/workspace/Idris/horn/src/Language.idr:235:5-236:26:
    |
235 |     noColsProof p (Because {ast} {prf=singleColProof}) = assert_total $ case singleColProof of
    |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ...
Language.noColsProof is possibly not total due to: Language.QueryHasExactlyOneColumn.Because

/home/nickolay/workspace/Idris/horn/src/Language.idr:239:5-240:26:
    |
239 |     twoAndMoreProof p (Because {ast} {prf=singleColProof}) = assert_total $ case singleColProof of
    |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ...
Language.twoAndMoreProof is possibly not total due to: Language.QueryHasExactlyOneColumn.Because
```

Note, how both functions are marked with "assert_total" but still, a compilation warning occurs. I believe this is because of the data declaration being not strictly positive:
```idris
    namespace QueryHasExactlyOneColumn
        data QueryHasExactlyOneColumn : (ast : QueryAbstractSyntaxTree) -> Type where
            Because     : { ast : QueryAbstractSyntaxTree}
                -> { auto prf : ListHasExactlyOneElement AnyColumnExpression' (fields ast) }
                -> QueryHasExactlyOneColumn ast
```
But shouldn't the "assert_total", as explicit indication by user, takes precedence?

**Comment by howtonotwin** [comment]
The offending pattern match is occurring outside of the `assert_total`.

```idris
noColsProof p (Because {ast} {prf=singleColProof}) = assert_total $ _
```

Means

```idris
noColsProof p arg2 = case arg2 of
                          Because {ast} {prf=singleColProof} -> assert_total $ _
```

The not-total thing is the pattern match on `Because`, but said match is outside of the `assert_total`, so it is unaffected. `assert_total` is supposed to be limited in scope, because that means you can write a function where *most* of it is total and only cheat in a few places. Here, it is working against you. This is expected behavior, but perhaps it should be documented somewhere.

You should be able to float the `assert_total` out.

```idris
noColsProof p prf = assert_total $ case prf of -> _
```

**Comment by SamuraiJack** [comment]
@howtonotwin That worked, thanks a lot! I didn't realize I'm pattern matching outside of the "assert_total". Closing this one.
