### ISSUE TITLE
Idris cannot find simple proof for uncurry function

### ISSUE THREAD

**Issue by ReedOei** [idris-lang/Idris-dev#4567]
I was trying out writing very basic functions in Idris (e.g., `curry`, `flip`, `uncurry`), which worked, except for `uncurry`. Here is the source code:
```
uncurry : (a -> b -> c) -> (a,b) -> c
uncurry f (a, b) = f ?a ?b
```

I'm using version 1.3.0

# Steps to Reproduce
Load the file containing the above code, using Vim extension (I presume that any other Idris-enabled editor will function exactly the same). Do obvious proof search on `?a` and `?b` (in vim, `\o` with cursor over the holes).

# Expected Behavior
When doing obvious proof search (`\o` on Vim) for `?a`, Idris should be able to find `a`, and similarly for `?b`, it should find `b`.

# Observed Behavior
Idris cannot find any replacement (the Vim extension replaces `?a` with `?a1`).

**Comment by msmorgan** [comment]
This fails because you have re-used `a` and `b` to refer to the types of the arguments as well as their values. You can avoid this by changing the second line to `uncurry f (x, y) = f ?a ?b` (the names of the holes don't matter). Using the same name to refer to different things currently causes the elaborator to become stuck.

**Comment by ReedOei** [comment]
I see. I was under the impression that it will only refer to things from the type if I wrote something like `uncurry {a} {b} ...`

Thanks!
