### ISSUE TITLE
Operations on big literals hang compiler

### ISSUE THREAD

**Issue by mjgpy3** [idris-lang/Idris-dev#4615]
The following code seems to hang when trying to compile using `idris file.idr -o output`
```idris
module Main

main : IO ()
main = print $ 50000000000 - 1
```

I actually ran into this one while trying to subtract big literals in the REPL while solving an advent of code challenge for this year. I think I understand why it happens there (I've heard that the REPL doesn't optimize `Nat` so it'll try to construct a 50billion value). But I wouldn't have expected this in the compiler.

**Comment by jfdm** [comment]
I would believe this is expected behaviour.

If your code Idris has to work out the type of the literals you are using. 

It is not clear what their type is, and I think Idris' default guess in the compiler and REPL are that they are of Nat.

Have you tried using a type annotation (the `the` function) to see what happens when either operand is told to be an Int.

Jan

**Comment by mjgpy3** [comment]
@jfdm, I see what you mean. Is `(-)` triggering this? If I remove `- 1` it compiles just fine.

**Comment by mjgpy3** [comment]
@jfdm thanks for the explanation.
