### ISSUE TITLE
getWitness function doesn't work with Dependent Pairs

### ISSUE THREAD

**Issue by Phiroc** [idris-lang/Idris-dev#4715]
In the video entitled _David Christiansen - Coding for Types: The Universe Patern in Idris - Curry On_ (cf. https://www.youtube.com/results?search_query=david+thrane+christiansen),
David used the _getWitness_ function as follows

# Steps to Reproduce

```
answer : (ts : List Type ** HList ts)
answer = ([String, Nat] ** ["The answer is ", 42])

getWitness answer
```
# Expected Behavior

```
[String, Nat] : List Type
```

# Observed Behavior
```
Can't disambiguate since no name has a suitable type: 
        Prelude.Pairs.Exists.getWitness, Prelude.Pairs.Subset.getWitness
```

NB: the Sigma Type (which has a getWitness function) can't be found by Idris.

```
:doc Sigma
No documentation for Sigma
```

**Comment by Phiroc** [comment]
Language : Idris 1.31
OS : MacOSX 10.14.4

**Comment by LeifW** [comment]
`Sigma` has since been renamed to `DPair` - http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#dependent-pairs

It used to be a record with `getWitness` and another field I forget the name of. Now, there's overloaded versions of `fst` and `snd` you can use on it, as if it's a regular tuple.
