### ISSUE TITLE
Build failed with GHC 8.8

### ISSUE THREAD

**Issue by felixonmars** [idris-lang/Idris-dev#4807]
# Steps to Reproduce
Build idris with GHC 8.8 (Cabal 3.0)

# Expected Behavior
Build passes

# Observed Behavior
```
Setup.hs:356:6: error: Not in scope: ‘preSDist’
    |
356 |    , preSDist = idrisPreSDist
    |      ^^^^^^^^

Setup.hs:357:6: error: Not in scope: ‘sDistHook’
    |
357 |    , sDistHook = idrisSDist (sDistHook simpleUserHooks)
    |      ^^^^^^^^^

Setup.hs:358:6: error: Not in scope: ‘postSDist’
    |
358 |    , postSDist = idrisPostSDist
    |      ^^^^^^^^^
```

**Comment by melted** [comment]
The new style builds will not function, because hooks we use are removed and the replacement functionality doesn't work for us: https://github.com/idris-lang/Idris-dev/issues/4757

So you will have to use `cabal v1-install`. Last I tried, and it was a while ago, the build fell down on dependencies that weresn't 8.8 ready. But I guess it's time to sort that out.

**Comment by melted** [comment]
So, I'm trying again with `cabal v1-install --allow-newer`

**Comment by melted** [comment]
Ah, it fails at cheapskate again, not weird as that is unmaintained. I guess we could submit a PR anyway. Or fork it. Or just vendor it.

**Comment by melted** [comment]
Ok, and now we get there, hmm, has the sdist hooks been removed for v1 builds too. 

Well, that's terrible, that means putting all the files in the cabal files again. And we would have to rename all the test shellscripts because cabal has overly restrictive rules for wildcards: https://github.com/haskell/cabal/issues/5883.

**Comment by melted** [comment]
To build it's possible to remove the hooks. The dist generation breaks with that, but I guess I can at least fix the compilation errors.

**Comment by melted** [comment]
https://github.com/idris-lang/Idris-dev/pull/4808

**Comment by melted** [comment]
Fixed
