### ISSUE TITLE
The --ibcsubdir flag doesn't generate the output uniformly

### ISSUE THREAD

**Issue by gabrielmc** [idris-lang/Idris-dev#499]
While trying to refactor the build to output everything into 'dist' (for #311), I noticed that `--ibcsubdir` doesn't actually work correctly when passed as a flag for building packages. For instance:

```bash
mkdir tmp
cd effects
sed -i '' -e 's#lib"#lib --ibcsubdir ../tmp"#' effects/effects.ipkg
idris --build effects.ipkg
```
will put the top-level Effects.ibc in place, but generate a new tmp directory in the effects directory for everything else.

I think this actually raises a larger issue of whether packages should be built by a different executable.

**Comment by jfdm** [comment]
@gabrielmc sorry this has taken so so so so so so long to address. However, the root of the problem is that idris package build tooling does not use the option `ibcsubdir`, and appears to ignore it completely. Thus, there is a straightforward fix to the problem you highlighted. Update the package build tooling to be aware of the option. I'll try and get round to it when I have time...
