### ISSUE TITLE
Category and Functor should permit categories whose objects are not types

### ISSUE THREAD

**Issue by JasonGross** [idris-lang/Idris-dev#707]
Idris is a dependently typed language, so there's no need to copy Haskell and pretend that the only category in existence is `Type`.  I suspect you'd want something like https://github.com/JasonGross/Idris-dev/commit/a5dfae3d48ccbb6903f9bdbc54b67bb6dec26c44, but I can't seem to make it compile.  (There's also the question of which things should be arguments and which things should be fields.)

**Comment by edwinb** [comment]
I think so much has changed in Idris, the example code, and particularly unification and the way type classes are resolved, that it's hard to tell if this code would work now or not. 

So, I'm going to close this issue, and if there are problems, please open as a new issue with new example code.

As far as the library design question goes, we should continue to experiment with new ways of doing things and stick them in contrib before moving to the Prelude if it turns out they work well.
